package testcases.CWE129_Improper_Validation_of_Array_Index.s03;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12029()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12028()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11981()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11980()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11777()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11776()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11917()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11916()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11923()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11922()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12069()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12068()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12031()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12030()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11975()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11974()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12009()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12008()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11947()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11946()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12059()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12058()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11835()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11834()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11937()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11936()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11983()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11982()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11921()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11920()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12109()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12108()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11825()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11824()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11905()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11904()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11969()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11968()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11897()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11896()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12035()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12034()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11843()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11842()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11967()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11966()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11871()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11870()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12017()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12016()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11875()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11874()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11903()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11902()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11769()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11768()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12003()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12002()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12103()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12102()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11827()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11826()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11869()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11868()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11867()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11866()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12057()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12056()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11957()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11956()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11809()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11808()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11779()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11778()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11791()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11790()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11999()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11998()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12077()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12076()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11873()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11872()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11881()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11880()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11993()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11992()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11861()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11860()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11971()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11970()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11789()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11788()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12045()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12044()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11819()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11818()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11899()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11898()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12075()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12074()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12089()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12088()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12095()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12094()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12101()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12100()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11909()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11908()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12025()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12024()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11857()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11856()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12043()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12042()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11925()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11924()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11935()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11934()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12033()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12032()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11879()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11878()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11965()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11964()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11995()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11994()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11797()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11796()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12021()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12020()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11887()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11886()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12085()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12084()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11787()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11786()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11833()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11832()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11801()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11800()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11989()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11988()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11931()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11930()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11775()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11774()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11793()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11792()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11949()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11948()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12047()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12046()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11859()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11858()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12111()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12110()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11837()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11836()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11907()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11906()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12091()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12090()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11929()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11928()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12053()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12052()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11963()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11962()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11845()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11844()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12037()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12036()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12005()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12004()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11889()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11888()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11919()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11918()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12107()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12106()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12015()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12014()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11839()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11838()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12105()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12104()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12041()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12040()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11997()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11996()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11893()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11892()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11821()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11820()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11977()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11976()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12061()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12060()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11883()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11882()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11953()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11952()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12063()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12062()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11951()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11950()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11761()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11760()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11911()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11910()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11941()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11940()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12013()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12012()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11891()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11890()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11771()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11770()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12023()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12022()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11901()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11900()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12051()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12050()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12067()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12066()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11807()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11806()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11773()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11772()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11943()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11942()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11915()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11914()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11855()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11854()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12093()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12092()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12001()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12000()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11955()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11954()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12081()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12080()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12099()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12098()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11877()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11876()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12071()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12070()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11895()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11894()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11823()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11822()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11795()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11794()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12065()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12064()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12027()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12026()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11933()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11932()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11961()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11960()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12083()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12082()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11979()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11978()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11781()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11780()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11763()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11762()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11945()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11944()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12007()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12006()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11841()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11840()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11813()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11812()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11847()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11846()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11803()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11802()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11991()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11990()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12039()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12038()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11959()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11958()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11927()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11926()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12097()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12096()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11865()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11864()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11805()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11804()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11815()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11814()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12079()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12078()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11799()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11798()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12011()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12010()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11767()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11766()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11973()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11972()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11939()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11938()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_max_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11863()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11862()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11851()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11850()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12055()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12054()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11831()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11830()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11885()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11884()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11853()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11852()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11913()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11912()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_write_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11811()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11810()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11987()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11986()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11785()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11784()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11817()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11816()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12049()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12048()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11829()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11828()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11783()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11782()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12073()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12072()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11849()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11848()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12019()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12018()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11985()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11984()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_read_check_min_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12087()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J12086()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11765()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s03.J11764()).runTest("CWE129_Improper_Validation_of_Array_Index__large_fixed_array_read_check_min_03_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
