package testcases.CWE78_OS_Command_Injection;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */
        (new testcases.CWE78_OS_Command_Injection.J20589()).runTest("CWE78_OS_Command_Injection__Environment_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20588()).runTest("CWE78_OS_Command_Injection__Environment_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20933()).runTest("CWE78_OS_Command_Injection__URLConnection_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20932()).runTest("CWE78_OS_Command_Injection__URLConnection_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20617()).runTest("CWE78_OS_Command_Injection__File_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20616()).runTest("CWE78_OS_Command_Injection__File_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20441()).runTest("CWE78_OS_Command_Injection__connect_tcp_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20440()).runTest("CWE78_OS_Command_Injection__connect_tcp_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20497()).runTest("CWE78_OS_Command_Injection__console_readLine_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20496()).runTest("CWE78_OS_Command_Injection__console_readLine_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20813()).runTest("CWE78_OS_Command_Injection__listen_tcp_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20812()).runTest("CWE78_OS_Command_Injection__listen_tcp_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20425()).runTest("CWE78_OS_Command_Injection__connect_tcp_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20424()).runTest("CWE78_OS_Command_Injection__connect_tcp_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20893()).runTest("CWE78_OS_Command_Injection__Property_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20892()).runTest("CWE78_OS_Command_Injection__Property_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20493()).runTest("CWE78_OS_Command_Injection__console_readLine_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20492()).runTest("CWE78_OS_Command_Injection__console_readLine_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20869()).runTest("CWE78_OS_Command_Injection__Property_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20868()).runTest("CWE78_OS_Command_Injection__Property_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20453()).runTest("CWE78_OS_Command_Injection__connect_tcp_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20452()).runTest("CWE78_OS_Command_Injection__connect_tcp_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20791()).runTest("CWE78_OS_Command_Injection__listen_tcp_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20790()).runTest("CWE78_OS_Command_Injection__listen_tcp_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20541()).runTest("CWE78_OS_Command_Injection__database_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20540()).runTest("CWE78_OS_Command_Injection__database_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20623()).runTest("CWE78_OS_Command_Injection__File_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20622()).runTest("CWE78_OS_Command_Injection__File_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20881()).runTest("CWE78_OS_Command_Injection__Property_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20880()).runTest("CWE78_OS_Command_Injection__Property_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20799()).runTest("CWE78_OS_Command_Injection__listen_tcp_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20798()).runTest("CWE78_OS_Command_Injection__listen_tcp_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20457()).runTest("CWE78_OS_Command_Injection__connect_tcp_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20456()).runTest("CWE78_OS_Command_Injection__connect_tcp_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20495()).runTest("CWE78_OS_Command_Injection__console_readLine_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20494()).runTest("CWE78_OS_Command_Injection__console_readLine_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20873()).runTest("CWE78_OS_Command_Injection__Property_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20872()).runTest("CWE78_OS_Command_Injection__Property_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20581()).runTest("CWE78_OS_Command_Injection__Environment_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20580()).runTest("CWE78_OS_Command_Injection__Environment_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20903()).runTest("CWE78_OS_Command_Injection__Property_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20902()).runTest("CWE78_OS_Command_Injection__Property_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20943()).runTest("CWE78_OS_Command_Injection__URLConnection_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20942()).runTest("CWE78_OS_Command_Injection__URLConnection_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20825()).runTest("CWE78_OS_Command_Injection__PropertiesFile_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20824()).runTest("CWE78_OS_Command_Injection__PropertiesFile_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20899()).runTest("CWE78_OS_Command_Injection__Property_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20898()).runTest("CWE78_OS_Command_Injection__Property_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20835()).runTest("CWE78_OS_Command_Injection__PropertiesFile_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20834()).runTest("CWE78_OS_Command_Injection__PropertiesFile_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20501()).runTest("CWE78_OS_Command_Injection__console_readLine_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20500()).runTest("CWE78_OS_Command_Injection__console_readLine_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20463()).runTest("CWE78_OS_Command_Injection__connect_tcp_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20462()).runTest("CWE78_OS_Command_Injection__connect_tcp_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20921()).runTest("CWE78_OS_Command_Injection__URLConnection_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20920()).runTest("CWE78_OS_Command_Injection__URLConnection_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20615()).runTest("CWE78_OS_Command_Injection__File_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20614()).runTest("CWE78_OS_Command_Injection__File_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20431()).runTest("CWE78_OS_Command_Injection__connect_tcp_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20430()).runTest("CWE78_OS_Command_Injection__connect_tcp_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20919()).runTest("CWE78_OS_Command_Injection__URLConnection_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20918()).runTest("CWE78_OS_Command_Injection__URLConnection_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20577()).runTest("CWE78_OS_Command_Injection__Environment_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20576()).runTest("CWE78_OS_Command_Injection__Environment_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20641()).runTest("CWE78_OS_Command_Injection__File_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20640()).runTest("CWE78_OS_Command_Injection__File_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20535()).runTest("CWE78_OS_Command_Injection__database_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20534()).runTest("CWE78_OS_Command_Injection__database_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20531()).runTest("CWE78_OS_Command_Injection__database_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20530()).runTest("CWE78_OS_Command_Injection__database_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20789()).runTest("CWE78_OS_Command_Injection__listen_tcp_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20788()).runTest("CWE78_OS_Command_Injection__listen_tcp_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20557()).runTest("CWE78_OS_Command_Injection__Environment_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20556()).runTest("CWE78_OS_Command_Injection__Environment_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20883()).runTest("CWE78_OS_Command_Injection__Property_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20882()).runTest("CWE78_OS_Command_Injection__Property_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20857()).runTest("CWE78_OS_Command_Injection__PropertiesFile_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20856()).runTest("CWE78_OS_Command_Injection__PropertiesFile_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20511()).runTest("CWE78_OS_Command_Injection__database_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20510()).runTest("CWE78_OS_Command_Injection__database_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20855()).runTest("CWE78_OS_Command_Injection__PropertiesFile_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20854()).runTest("CWE78_OS_Command_Injection__PropertiesFile_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20815()).runTest("CWE78_OS_Command_Injection__listen_tcp_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20814()).runTest("CWE78_OS_Command_Injection__listen_tcp_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20949()).runTest("CWE78_OS_Command_Injection__URLConnection_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20948()).runTest("CWE78_OS_Command_Injection__URLConnection_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20603()).runTest("CWE78_OS_Command_Injection__File_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20602()).runTest("CWE78_OS_Command_Injection__File_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20939()).runTest("CWE78_OS_Command_Injection__URLConnection_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20938()).runTest("CWE78_OS_Command_Injection__URLConnection_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20435()).runTest("CWE78_OS_Command_Injection__connect_tcp_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20434()).runTest("CWE78_OS_Command_Injection__connect_tcp_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20443()).runTest("CWE78_OS_Command_Injection__connect_tcp_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20442()).runTest("CWE78_OS_Command_Injection__connect_tcp_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20545()).runTest("CWE78_OS_Command_Injection__database_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20544()).runTest("CWE78_OS_Command_Injection__database_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20637()).runTest("CWE78_OS_Command_Injection__File_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20636()).runTest("CWE78_OS_Command_Injection__File_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20469()).runTest("CWE78_OS_Command_Injection__console_readLine_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20468()).runTest("CWE78_OS_Command_Injection__console_readLine_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20579()).runTest("CWE78_OS_Command_Injection__Environment_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20578()).runTest("CWE78_OS_Command_Injection__Environment_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20783()).runTest("CWE78_OS_Command_Injection__listen_tcp_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20782()).runTest("CWE78_OS_Command_Injection__listen_tcp_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20537()).runTest("CWE78_OS_Command_Injection__database_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20536()).runTest("CWE78_OS_Command_Injection__database_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20947()).runTest("CWE78_OS_Command_Injection__URLConnection_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20946()).runTest("CWE78_OS_Command_Injection__URLConnection_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20465()).runTest("CWE78_OS_Command_Injection__connect_tcp_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20464()).runTest("CWE78_OS_Command_Injection__connect_tcp_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20599()).runTest("CWE78_OS_Command_Injection__File_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20598()).runTest("CWE78_OS_Command_Injection__File_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20887()).runTest("CWE78_OS_Command_Injection__Property_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20886()).runTest("CWE78_OS_Command_Injection__Property_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20863()).runTest("CWE78_OS_Command_Injection__Property_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20862()).runTest("CWE78_OS_Command_Injection__Property_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20839()).runTest("CWE78_OS_Command_Injection__PropertiesFile_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20838()).runTest("CWE78_OS_Command_Injection__PropertiesFile_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20551()).runTest("CWE78_OS_Command_Injection__database_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20550()).runTest("CWE78_OS_Command_Injection__database_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20797()).runTest("CWE78_OS_Command_Injection__listen_tcp_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20796()).runTest("CWE78_OS_Command_Injection__listen_tcp_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20895()).runTest("CWE78_OS_Command_Injection__Property_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20894()).runTest("CWE78_OS_Command_Injection__Property_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20423()).runTest("CWE78_OS_Command_Injection__connect_tcp_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20422()).runTest("CWE78_OS_Command_Injection__connect_tcp_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20505()).runTest("CWE78_OS_Command_Injection__console_readLine_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20504()).runTest("CWE78_OS_Command_Injection__console_readLine_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20915()).runTest("CWE78_OS_Command_Injection__URLConnection_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20914()).runTest("CWE78_OS_Command_Injection__URLConnection_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20515()).runTest("CWE78_OS_Command_Injection__database_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20514()).runTest("CWE78_OS_Command_Injection__database_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20897()).runTest("CWE78_OS_Command_Injection__Property_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20896()).runTest("CWE78_OS_Command_Injection__Property_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20449()).runTest("CWE78_OS_Command_Injection__connect_tcp_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20448()).runTest("CWE78_OS_Command_Injection__connect_tcp_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20523()).runTest("CWE78_OS_Command_Injection__database_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20522()).runTest("CWE78_OS_Command_Injection__database_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20573()).runTest("CWE78_OS_Command_Injection__Environment_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20572()).runTest("CWE78_OS_Command_Injection__Environment_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20777()).runTest("CWE78_OS_Command_Injection__listen_tcp_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20776()).runTest("CWE78_OS_Command_Injection__listen_tcp_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20571()).runTest("CWE78_OS_Command_Injection__Environment_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20570()).runTest("CWE78_OS_Command_Injection__Environment_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20811()).runTest("CWE78_OS_Command_Injection__listen_tcp_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20810()).runTest("CWE78_OS_Command_Injection__listen_tcp_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20859()).runTest("CWE78_OS_Command_Injection__PropertiesFile_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20858()).runTest("CWE78_OS_Command_Injection__PropertiesFile_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20793()).runTest("CWE78_OS_Command_Injection__listen_tcp_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20792()).runTest("CWE78_OS_Command_Injection__listen_tcp_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20593()).runTest("CWE78_OS_Command_Injection__Environment_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20592()).runTest("CWE78_OS_Command_Injection__Environment_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20875()).runTest("CWE78_OS_Command_Injection__Property_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20874()).runTest("CWE78_OS_Command_Injection__Property_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20821()).runTest("CWE78_OS_Command_Injection__PropertiesFile_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20820()).runTest("CWE78_OS_Command_Injection__PropertiesFile_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20927()).runTest("CWE78_OS_Command_Injection__URLConnection_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20926()).runTest("CWE78_OS_Command_Injection__URLConnection_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20527()).runTest("CWE78_OS_Command_Injection__database_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20526()).runTest("CWE78_OS_Command_Injection__database_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20539()).runTest("CWE78_OS_Command_Injection__database_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20538()).runTest("CWE78_OS_Command_Injection__database_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20865()).runTest("CWE78_OS_Command_Injection__Property_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20864()).runTest("CWE78_OS_Command_Injection__Property_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20819()).runTest("CWE78_OS_Command_Injection__PropertiesFile_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20818()).runTest("CWE78_OS_Command_Injection__PropertiesFile_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20817()).runTest("CWE78_OS_Command_Injection__listen_tcp_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20816()).runTest("CWE78_OS_Command_Injection__listen_tcp_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20519()).runTest("CWE78_OS_Command_Injection__database_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20518()).runTest("CWE78_OS_Command_Injection__database_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20529()).runTest("CWE78_OS_Command_Injection__database_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20528()).runTest("CWE78_OS_Command_Injection__database_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20607()).runTest("CWE78_OS_Command_Injection__File_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20606()).runTest("CWE78_OS_Command_Injection__File_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20625()).runTest("CWE78_OS_Command_Injection__File_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20624()).runTest("CWE78_OS_Command_Injection__File_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20525()).runTest("CWE78_OS_Command_Injection__database_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20524()).runTest("CWE78_OS_Command_Injection__database_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20931()).runTest("CWE78_OS_Command_Injection__URLConnection_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20930()).runTest("CWE78_OS_Command_Injection__URLConnection_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20841()).runTest("CWE78_OS_Command_Injection__PropertiesFile_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20840()).runTest("CWE78_OS_Command_Injection__PropertiesFile_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20445()).runTest("CWE78_OS_Command_Injection__connect_tcp_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20444()).runTest("CWE78_OS_Command_Injection__connect_tcp_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20837()).runTest("CWE78_OS_Command_Injection__PropertiesFile_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20836()).runTest("CWE78_OS_Command_Injection__PropertiesFile_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20829()).runTest("CWE78_OS_Command_Injection__PropertiesFile_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20828()).runTest("CWE78_OS_Command_Injection__PropertiesFile_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20621()).runTest("CWE78_OS_Command_Injection__File_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20620()).runTest("CWE78_OS_Command_Injection__File_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20471()).runTest("CWE78_OS_Command_Injection__console_readLine_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20470()).runTest("CWE78_OS_Command_Injection__console_readLine_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20513()).runTest("CWE78_OS_Command_Injection__database_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20512()).runTest("CWE78_OS_Command_Injection__database_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20553()).runTest("CWE78_OS_Command_Injection__database_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20552()).runTest("CWE78_OS_Command_Injection__database_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20429()).runTest("CWE78_OS_Command_Injection__connect_tcp_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20428()).runTest("CWE78_OS_Command_Injection__connect_tcp_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20491()).runTest("CWE78_OS_Command_Injection__console_readLine_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20490()).runTest("CWE78_OS_Command_Injection__console_readLine_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20917()).runTest("CWE78_OS_Command_Injection__URLConnection_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20916()).runTest("CWE78_OS_Command_Injection__URLConnection_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20585()).runTest("CWE78_OS_Command_Injection__Environment_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20584()).runTest("CWE78_OS_Command_Injection__Environment_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20909()).runTest("CWE78_OS_Command_Injection__URLConnection_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20908()).runTest("CWE78_OS_Command_Injection__URLConnection_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20935()).runTest("CWE78_OS_Command_Injection__URLConnection_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20934()).runTest("CWE78_OS_Command_Injection__URLConnection_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20923()).runTest("CWE78_OS_Command_Injection__URLConnection_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20922()).runTest("CWE78_OS_Command_Injection__URLConnection_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20629()).runTest("CWE78_OS_Command_Injection__File_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20628()).runTest("CWE78_OS_Command_Injection__File_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20567()).runTest("CWE78_OS_Command_Injection__Environment_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20566()).runTest("CWE78_OS_Command_Injection__Environment_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20861()).runTest("CWE78_OS_Command_Injection__PropertiesFile_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20860()).runTest("CWE78_OS_Command_Injection__PropertiesFile_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20889()).runTest("CWE78_OS_Command_Injection__Property_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20888()).runTest("CWE78_OS_Command_Injection__Property_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20601()).runTest("CWE78_OS_Command_Injection__File_02_good");
        (new testcases.CWE78_OS_Command_Injection.J20600()).runTest("CWE78_OS_Command_Injection__File_02_bad");
        (new testcases.CWE78_OS_Command_Injection.J20891()).runTest("CWE78_OS_Command_Injection__Property_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20890()).runTest("CWE78_OS_Command_Injection__Property_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20533()).runTest("CWE78_OS_Command_Injection__database_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20532()).runTest("CWE78_OS_Command_Injection__database_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20635()).runTest("CWE78_OS_Command_Injection__File_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20634()).runTest("CWE78_OS_Command_Injection__File_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20517()).runTest("CWE78_OS_Command_Injection__database_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20516()).runTest("CWE78_OS_Command_Injection__database_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20945()).runTest("CWE78_OS_Command_Injection__URLConnection_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20944()).runTest("CWE78_OS_Command_Injection__URLConnection_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20503()).runTest("CWE78_OS_Command_Injection__console_readLine_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20502()).runTest("CWE78_OS_Command_Injection__console_readLine_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20563()).runTest("CWE78_OS_Command_Injection__Environment_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20562()).runTest("CWE78_OS_Command_Injection__Environment_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20473()).runTest("CWE78_OS_Command_Injection__console_readLine_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20472()).runTest("CWE78_OS_Command_Injection__console_readLine_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20849()).runTest("CWE78_OS_Command_Injection__PropertiesFile_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20848()).runTest("CWE78_OS_Command_Injection__PropertiesFile_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20461()).runTest("CWE78_OS_Command_Injection__connect_tcp_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20460()).runTest("CWE78_OS_Command_Injection__connect_tcp_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20851()).runTest("CWE78_OS_Command_Injection__PropertiesFile_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20850()).runTest("CWE78_OS_Command_Injection__PropertiesFile_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20509()).runTest("CWE78_OS_Command_Injection__console_readLine_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20508()).runTest("CWE78_OS_Command_Injection__console_readLine_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20555()).runTest("CWE78_OS_Command_Injection__Environment_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20554()).runTest("CWE78_OS_Command_Injection__Environment_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20845()).runTest("CWE78_OS_Command_Injection__PropertiesFile_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20844()).runTest("CWE78_OS_Command_Injection__PropertiesFile_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20481()).runTest("CWE78_OS_Command_Injection__console_readLine_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20480()).runTest("CWE78_OS_Command_Injection__console_readLine_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20807()).runTest("CWE78_OS_Command_Injection__listen_tcp_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20806()).runTest("CWE78_OS_Command_Injection__listen_tcp_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20867()).runTest("CWE78_OS_Command_Injection__Property_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20866()).runTest("CWE78_OS_Command_Injection__Property_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20609()).runTest("CWE78_OS_Command_Injection__File_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20608()).runTest("CWE78_OS_Command_Injection__File_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20853()).runTest("CWE78_OS_Command_Injection__PropertiesFile_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20852()).runTest("CWE78_OS_Command_Injection__PropertiesFile_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20547()).runTest("CWE78_OS_Command_Injection__database_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20546()).runTest("CWE78_OS_Command_Injection__database_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20459()).runTest("CWE78_OS_Command_Injection__connect_tcp_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20458()).runTest("CWE78_OS_Command_Injection__connect_tcp_31_bad");
        (new testcases.CWE78_OS_Command_Injection.J20905()).runTest("CWE78_OS_Command_Injection__Property_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20904()).runTest("CWE78_OS_Command_Injection__Property_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20569()).runTest("CWE78_OS_Command_Injection__Environment_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20568()).runTest("CWE78_OS_Command_Injection__Environment_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20565()).runTest("CWE78_OS_Command_Injection__Environment_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20564()).runTest("CWE78_OS_Command_Injection__Environment_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20439()).runTest("CWE78_OS_Command_Injection__connect_tcp_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20438()).runTest("CWE78_OS_Command_Injection__connect_tcp_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20479()).runTest("CWE78_OS_Command_Injection__console_readLine_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20478()).runTest("CWE78_OS_Command_Injection__console_readLine_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20775()).runTest("CWE78_OS_Command_Injection__listen_tcp_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20774()).runTest("CWE78_OS_Command_Injection__listen_tcp_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20843()).runTest("CWE78_OS_Command_Injection__PropertiesFile_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20842()).runTest("CWE78_OS_Command_Injection__PropertiesFile_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20507()).runTest("CWE78_OS_Command_Injection__console_readLine_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20506()).runTest("CWE78_OS_Command_Injection__console_readLine_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20847()).runTest("CWE78_OS_Command_Injection__PropertiesFile_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20846()).runTest("CWE78_OS_Command_Injection__PropertiesFile_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20489()).runTest("CWE78_OS_Command_Injection__console_readLine_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20488()).runTest("CWE78_OS_Command_Injection__console_readLine_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20803()).runTest("CWE78_OS_Command_Injection__listen_tcp_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20802()).runTest("CWE78_OS_Command_Injection__listen_tcp_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20929()).runTest("CWE78_OS_Command_Injection__URLConnection_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20928()).runTest("CWE78_OS_Command_Injection__URLConnection_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20831()).runTest("CWE78_OS_Command_Injection__PropertiesFile_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20830()).runTest("CWE78_OS_Command_Injection__PropertiesFile_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20433()).runTest("CWE78_OS_Command_Injection__connect_tcp_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20432()).runTest("CWE78_OS_Command_Injection__connect_tcp_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20787()).runTest("CWE78_OS_Command_Injection__listen_tcp_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20786()).runTest("CWE78_OS_Command_Injection__listen_tcp_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20785()).runTest("CWE78_OS_Command_Injection__listen_tcp_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20784()).runTest("CWE78_OS_Command_Injection__listen_tcp_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20543()).runTest("CWE78_OS_Command_Injection__database_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20542()).runTest("CWE78_OS_Command_Injection__database_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20795()).runTest("CWE78_OS_Command_Injection__listen_tcp_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20794()).runTest("CWE78_OS_Command_Injection__listen_tcp_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20885()).runTest("CWE78_OS_Command_Injection__Property_12_good");
        (new testcases.CWE78_OS_Command_Injection.J20884()).runTest("CWE78_OS_Command_Injection__Property_12_bad");
        (new testcases.CWE78_OS_Command_Injection.J20451()).runTest("CWE78_OS_Command_Injection__connect_tcp_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20450()).runTest("CWE78_OS_Command_Injection__connect_tcp_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20485()).runTest("CWE78_OS_Command_Injection__console_readLine_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20484()).runTest("CWE78_OS_Command_Injection__console_readLine_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20809()).runTest("CWE78_OS_Command_Injection__listen_tcp_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20808()).runTest("CWE78_OS_Command_Injection__listen_tcp_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20907()).runTest("CWE78_OS_Command_Injection__URLConnection_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20906()).runTest("CWE78_OS_Command_Injection__URLConnection_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20801()).runTest("CWE78_OS_Command_Injection__listen_tcp_14_good");
        (new testcases.CWE78_OS_Command_Injection.J20800()).runTest("CWE78_OS_Command_Injection__listen_tcp_14_bad");
        (new testcases.CWE78_OS_Command_Injection.J20877()).runTest("CWE78_OS_Command_Injection__Property_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20876()).runTest("CWE78_OS_Command_Injection__Property_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20871()).runTest("CWE78_OS_Command_Injection__Property_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20870()).runTest("CWE78_OS_Command_Injection__Property_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20613()).runTest("CWE78_OS_Command_Injection__File_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20612()).runTest("CWE78_OS_Command_Injection__File_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20639()).runTest("CWE78_OS_Command_Injection__File_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20638()).runTest("CWE78_OS_Command_Injection__File_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20937()).runTest("CWE78_OS_Command_Injection__URLConnection_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20936()).runTest("CWE78_OS_Command_Injection__URLConnection_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20587()).runTest("CWE78_OS_Command_Injection__Environment_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20586()).runTest("CWE78_OS_Command_Injection__Environment_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20475()).runTest("CWE78_OS_Command_Injection__console_readLine_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20474()).runTest("CWE78_OS_Command_Injection__console_readLine_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20583()).runTest("CWE78_OS_Command_Injection__Environment_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20582()).runTest("CWE78_OS_Command_Injection__Environment_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20549()).runTest("CWE78_OS_Command_Injection__database_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20548()).runTest("CWE78_OS_Command_Injection__database_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20575()).runTest("CWE78_OS_Command_Injection__Environment_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20574()).runTest("CWE78_OS_Command_Injection__Environment_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20781()).runTest("CWE78_OS_Command_Injection__listen_tcp_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20780()).runTest("CWE78_OS_Command_Injection__listen_tcp_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20823()).runTest("CWE78_OS_Command_Injection__PropertiesFile_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20822()).runTest("CWE78_OS_Command_Injection__PropertiesFile_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20595()).runTest("CWE78_OS_Command_Injection__Environment_42_good");
        (new testcases.CWE78_OS_Command_Injection.J20594()).runTest("CWE78_OS_Command_Injection__Environment_42_bad");
        (new testcases.CWE78_OS_Command_Injection.J20427()).runTest("CWE78_OS_Command_Injection__connect_tcp_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20426()).runTest("CWE78_OS_Command_Injection__connect_tcp_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20447()).runTest("CWE78_OS_Command_Injection__connect_tcp_13_good");
        (new testcases.CWE78_OS_Command_Injection.J20446()).runTest("CWE78_OS_Command_Injection__connect_tcp_13_bad");
        (new testcases.CWE78_OS_Command_Injection.J20467()).runTest("CWE78_OS_Command_Injection__console_readLine_01_good");
        (new testcases.CWE78_OS_Command_Injection.J20466()).runTest("CWE78_OS_Command_Injection__console_readLine_01_bad");
        (new testcases.CWE78_OS_Command_Injection.J20805()).runTest("CWE78_OS_Command_Injection__listen_tcp_16_good");
        (new testcases.CWE78_OS_Command_Injection.J20804()).runTest("CWE78_OS_Command_Injection__listen_tcp_16_bad");
        (new testcases.CWE78_OS_Command_Injection.J20779()).runTest("CWE78_OS_Command_Injection__listen_tcp_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20778()).runTest("CWE78_OS_Command_Injection__listen_tcp_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20597()).runTest("CWE78_OS_Command_Injection__Environment_45_good");
        (new testcases.CWE78_OS_Command_Injection.J20596()).runTest("CWE78_OS_Command_Injection__Environment_45_bad");
        (new testcases.CWE78_OS_Command_Injection.J20911()).runTest("CWE78_OS_Command_Injection__URLConnection_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20910()).runTest("CWE78_OS_Command_Injection__URLConnection_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20941()).runTest("CWE78_OS_Command_Injection__URLConnection_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20940()).runTest("CWE78_OS_Command_Injection__URLConnection_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20561()).runTest("CWE78_OS_Command_Injection__Environment_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20560()).runTest("CWE78_OS_Command_Injection__Environment_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20437()).runTest("CWE78_OS_Command_Injection__connect_tcp_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20436()).runTest("CWE78_OS_Command_Injection__connect_tcp_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20833()).runTest("CWE78_OS_Command_Injection__PropertiesFile_08_good");
        (new testcases.CWE78_OS_Command_Injection.J20832()).runTest("CWE78_OS_Command_Injection__PropertiesFile_08_bad");
        (new testcases.CWE78_OS_Command_Injection.J20483()).runTest("CWE78_OS_Command_Injection__console_readLine_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20482()).runTest("CWE78_OS_Command_Injection__console_readLine_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20925()).runTest("CWE78_OS_Command_Injection__URLConnection_10_good");
        (new testcases.CWE78_OS_Command_Injection.J20924()).runTest("CWE78_OS_Command_Injection__URLConnection_10_bad");
        (new testcases.CWE78_OS_Command_Injection.J20605()).runTest("CWE78_OS_Command_Injection__File_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20604()).runTest("CWE78_OS_Command_Injection__File_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20901()).runTest("CWE78_OS_Command_Injection__Property_41_good");
        (new testcases.CWE78_OS_Command_Injection.J20900()).runTest("CWE78_OS_Command_Injection__Property_41_bad");
        (new testcases.CWE78_OS_Command_Injection.J20627()).runTest("CWE78_OS_Command_Injection__File_15_good");
        (new testcases.CWE78_OS_Command_Injection.J20626()).runTest("CWE78_OS_Command_Injection__File_15_bad");
        (new testcases.CWE78_OS_Command_Injection.J20619()).runTest("CWE78_OS_Command_Injection__File_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20618()).runTest("CWE78_OS_Command_Injection__File_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20913()).runTest("CWE78_OS_Command_Injection__URLConnection_04_good");
        (new testcases.CWE78_OS_Command_Injection.J20912()).runTest("CWE78_OS_Command_Injection__URLConnection_04_bad");
        (new testcases.CWE78_OS_Command_Injection.J20487()).runTest("CWE78_OS_Command_Injection__console_readLine_11_good");
        (new testcases.CWE78_OS_Command_Injection.J20486()).runTest("CWE78_OS_Command_Injection__console_readLine_11_bad");
        (new testcases.CWE78_OS_Command_Injection.J20879()).runTest("CWE78_OS_Command_Injection__Property_09_good");
        (new testcases.CWE78_OS_Command_Injection.J20878()).runTest("CWE78_OS_Command_Injection__Property_09_bad");
        (new testcases.CWE78_OS_Command_Injection.J20631()).runTest("CWE78_OS_Command_Injection__File_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20630()).runTest("CWE78_OS_Command_Injection__File_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20499()).runTest("CWE78_OS_Command_Injection__console_readLine_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20498()).runTest("CWE78_OS_Command_Injection__console_readLine_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20559()).runTest("CWE78_OS_Command_Injection__Environment_03_good");
        (new testcases.CWE78_OS_Command_Injection.J20558()).runTest("CWE78_OS_Command_Injection__Environment_03_bad");
        (new testcases.CWE78_OS_Command_Injection.J20633()).runTest("CWE78_OS_Command_Injection__File_21_good");
        (new testcases.CWE78_OS_Command_Injection.J20632()).runTest("CWE78_OS_Command_Injection__File_21_bad");
        (new testcases.CWE78_OS_Command_Injection.J20521()).runTest("CWE78_OS_Command_Injection__database_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20520()).runTest("CWE78_OS_Command_Injection__database_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20611()).runTest("CWE78_OS_Command_Injection__File_07_good");
        (new testcases.CWE78_OS_Command_Injection.J20610()).runTest("CWE78_OS_Command_Injection__File_07_bad");
        (new testcases.CWE78_OS_Command_Injection.J20455()).runTest("CWE78_OS_Command_Injection__connect_tcp_17_good");
        (new testcases.CWE78_OS_Command_Injection.J20454()).runTest("CWE78_OS_Command_Injection__connect_tcp_17_bad");
        (new testcases.CWE78_OS_Command_Injection.J20477()).runTest("CWE78_OS_Command_Injection__console_readLine_06_good");
        (new testcases.CWE78_OS_Command_Injection.J20476()).runTest("CWE78_OS_Command_Injection__console_readLine_06_bad");
        (new testcases.CWE78_OS_Command_Injection.J20827()).runTest("CWE78_OS_Command_Injection__PropertiesFile_05_good");
        (new testcases.CWE78_OS_Command_Injection.J20826()).runTest("CWE78_OS_Command_Injection__PropertiesFile_05_bad");
        (new testcases.CWE78_OS_Command_Injection.J20591()).runTest("CWE78_OS_Command_Injection__Environment_31_good");
        (new testcases.CWE78_OS_Command_Injection.J20590()).runTest("CWE78_OS_Command_Injection__Environment_31_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
