package testcases.CWE190_Integer_Overflow.s06;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s06.J1285()).runTest("CWE190_Integer_Overflow__byte_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1284()).runTest("CWE190_Integer_Overflow__byte_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1313()).runTest("CWE190_Integer_Overflow__int_random_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1312()).runTest("CWE190_Integer_Overflow__int_random_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1315()).runTest("CWE190_Integer_Overflow__int_URLConnection_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1314()).runTest("CWE190_Integer_Overflow__int_URLConnection_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1289()).runTest("CWE190_Integer_Overflow__int_connect_tcp_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1288()).runTest("CWE190_Integer_Overflow__int_connect_tcp_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1287()).runTest("CWE190_Integer_Overflow__byte_rand_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1286()).runTest("CWE190_Integer_Overflow__byte_rand_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1293()).runTest("CWE190_Integer_Overflow__int_database_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1292()).runTest("CWE190_Integer_Overflow__int_database_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1305()).runTest("CWE190_Integer_Overflow__int_listen_tcp_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1304()).runTest("CWE190_Integer_Overflow__int_listen_tcp_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1295()).runTest("CWE190_Integer_Overflow__int_Environment_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1294()).runTest("CWE190_Integer_Overflow__int_Environment_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1283()).runTest("CWE190_Integer_Overflow__byte_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1282()).runTest("CWE190_Integer_Overflow__byte_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1321()).runTest("CWE190_Integer_Overflow__long_rand_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1320()).runTest("CWE190_Integer_Overflow__long_rand_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1311()).runTest("CWE190_Integer_Overflow__int_Property_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1310()).runTest("CWE190_Integer_Overflow__int_Property_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1323()).runTest("CWE190_Integer_Overflow__short_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1322()).runTest("CWE190_Integer_Overflow__short_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1309()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1308()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1317()).runTest("CWE190_Integer_Overflow__long_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1316()).runTest("CWE190_Integer_Overflow__long_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1291()).runTest("CWE190_Integer_Overflow__int_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1290()).runTest("CWE190_Integer_Overflow__int_console_readLine_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1307()).runTest("CWE190_Integer_Overflow__int_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1306()).runTest("CWE190_Integer_Overflow__int_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1297()).runTest("CWE190_Integer_Overflow__int_File_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1296()).runTest("CWE190_Integer_Overflow__int_File_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1319()).runTest("CWE190_Integer_Overflow__long_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1318()).runTest("CWE190_Integer_Overflow__long_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1325()).runTest("CWE190_Integer_Overflow__short_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1324()).runTest("CWE190_Integer_Overflow__short_max_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1327()).runTest("CWE190_Integer_Overflow__short_rand_postinc_01");
        (new testcases.CWE190_Integer_Overflow.s06.J1326()).runTest("CWE190_Integer_Overflow__short_rand_postinc_01");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
