package testcases.CWE476_NULL_Pointer_Dereference;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */
        (new testcases.CWE476_NULL_Pointer_Dereference.J19541()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19540()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19595()).runTest("CWE476_NULL_Pointer_Dereference__Integer_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19594()).runTest("CWE476_NULL_Pointer_Dereference__Integer_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19619()).runTest("CWE476_NULL_Pointer_Dereference__int_array_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19618()).runTest("CWE476_NULL_Pointer_Dereference__int_array_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19585()).runTest("CWE476_NULL_Pointer_Dereference__Integer_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19584()).runTest("CWE476_NULL_Pointer_Dereference__Integer_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19561()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19560()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19545()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19544()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19709()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19708()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19583()).runTest("CWE476_NULL_Pointer_Dereference__Integer_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19582()).runTest("CWE476_NULL_Pointer_Dereference__Integer_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19707()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19706()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19509()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19508()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19733()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_41_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19732()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_41_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19567()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19566()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19771()).runTest("CWE476_NULL_Pointer_Dereference__String_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19770()).runTest("CWE476_NULL_Pointer_Dereference__String_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19719()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19718()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19513()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19512()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19747()).runTest("CWE476_NULL_Pointer_Dereference__String_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19746()).runTest("CWE476_NULL_Pointer_Dereference__String_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19727()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19726()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19671()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19670()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19675()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19674()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19625()).runTest("CWE476_NULL_Pointer_Dereference__int_array_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19624()).runTest("CWE476_NULL_Pointer_Dereference__int_array_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19621()).runTest("CWE476_NULL_Pointer_Dereference__int_array_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19620()).runTest("CWE476_NULL_Pointer_Dereference__int_array_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19569()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19568()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19527()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19526()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19639()).runTest("CWE476_NULL_Pointer_Dereference__int_array_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19638()).runTest("CWE476_NULL_Pointer_Dereference__int_array_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19741()).runTest("CWE476_NULL_Pointer_Dereference__String_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19740()).runTest("CWE476_NULL_Pointer_Dereference__String_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19711()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19710()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19655()).runTest("CWE476_NULL_Pointer_Dereference__int_array_41_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19654()).runTest("CWE476_NULL_Pointer_Dereference__int_array_41_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19667()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19666()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19577()).runTest("CWE476_NULL_Pointer_Dereference__Integer_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19576()).runTest("CWE476_NULL_Pointer_Dereference__Integer_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19735()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_42_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19734()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_42_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19573()).runTest("CWE476_NULL_Pointer_Dereference__Integer_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19572()).runTest("CWE476_NULL_Pointer_Dereference__Integer_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19563()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19562()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19505()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19504()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19759()).runTest("CWE476_NULL_Pointer_Dereference__String_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19758()).runTest("CWE476_NULL_Pointer_Dereference__String_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19757()).runTest("CWE476_NULL_Pointer_Dereference__String_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19756()).runTest("CWE476_NULL_Pointer_Dereference__String_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19685()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19684()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19665()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19664()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19657()).runTest("CWE476_NULL_Pointer_Dereference__int_array_42_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19656()).runTest("CWE476_NULL_Pointer_Dereference__int_array_42_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19571()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19570()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19521()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19520()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19523()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19522()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19547()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19546()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19593()).runTest("CWE476_NULL_Pointer_Dereference__Integer_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19592()).runTest("CWE476_NULL_Pointer_Dereference__Integer_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19729()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_21_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19728()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_21_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19697()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19696()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19663()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19662()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19519()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19518()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19677()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19676()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19597()).runTest("CWE476_NULL_Pointer_Dereference__Integer_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19596()).runTest("CWE476_NULL_Pointer_Dereference__Integer_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19769()).runTest("CWE476_NULL_Pointer_Dereference__String_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19768()).runTest("CWE476_NULL_Pointer_Dereference__String_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19613()).runTest("CWE476_NULL_Pointer_Dereference__Integer_42_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19612()).runTest("CWE476_NULL_Pointer_Dereference__Integer_42_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19761()).runTest("CWE476_NULL_Pointer_Dereference__String_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19760()).runTest("CWE476_NULL_Pointer_Dereference__String_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19755()).runTest("CWE476_NULL_Pointer_Dereference__String_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19754()).runTest("CWE476_NULL_Pointer_Dereference__String_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19659()).runTest("CWE476_NULL_Pointer_Dereference__int_array_45_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19658()).runTest("CWE476_NULL_Pointer_Dereference__int_array_45_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19717()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19716()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19763()).runTest("CWE476_NULL_Pointer_Dereference__String_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19762()).runTest("CWE476_NULL_Pointer_Dereference__String_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19623()).runTest("CWE476_NULL_Pointer_Dereference__int_array_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19622()).runTest("CWE476_NULL_Pointer_Dereference__int_array_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19701()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19700()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19673()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19672()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19781()).runTest("CWE476_NULL_Pointer_Dereference__String_45_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19780()).runTest("CWE476_NULL_Pointer_Dereference__String_45_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19533()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19532()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19609()).runTest("CWE476_NULL_Pointer_Dereference__Integer_31_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19608()).runTest("CWE476_NULL_Pointer_Dereference__Integer_31_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19749()).runTest("CWE476_NULL_Pointer_Dereference__String_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19748()).runTest("CWE476_NULL_Pointer_Dereference__String_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19723()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19722()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19559()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19558()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19779()).runTest("CWE476_NULL_Pointer_Dereference__String_42_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19778()).runTest("CWE476_NULL_Pointer_Dereference__String_42_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19611()).runTest("CWE476_NULL_Pointer_Dereference__Integer_41_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19610()).runTest("CWE476_NULL_Pointer_Dereference__Integer_41_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19627()).runTest("CWE476_NULL_Pointer_Dereference__int_array_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19626()).runTest("CWE476_NULL_Pointer_Dereference__int_array_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19517()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19516()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19605()).runTest("CWE476_NULL_Pointer_Dereference__Integer_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19604()).runTest("CWE476_NULL_Pointer_Dereference__Integer_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19633()).runTest("CWE476_NULL_Pointer_Dereference__int_array_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19632()).runTest("CWE476_NULL_Pointer_Dereference__int_array_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19743()).runTest("CWE476_NULL_Pointer_Dereference__String_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19742()).runTest("CWE476_NULL_Pointer_Dereference__String_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19581()).runTest("CWE476_NULL_Pointer_Dereference__Integer_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19580()).runTest("CWE476_NULL_Pointer_Dereference__Integer_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19531()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19530()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19737()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_45_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19736()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_45_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19637()).runTest("CWE476_NULL_Pointer_Dereference__int_array_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19636()).runTest("CWE476_NULL_Pointer_Dereference__int_array_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19629()).runTest("CWE476_NULL_Pointer_Dereference__int_array_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19628()).runTest("CWE476_NULL_Pointer_Dereference__int_array_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19511()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19510()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19649()).runTest("CWE476_NULL_Pointer_Dereference__int_array_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19648()).runTest("CWE476_NULL_Pointer_Dereference__int_array_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19557()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19556()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19599()).runTest("CWE476_NULL_Pointer_Dereference__Integer_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19598()).runTest("CWE476_NULL_Pointer_Dereference__Integer_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19617()).runTest("CWE476_NULL_Pointer_Dereference__int_array_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19616()).runTest("CWE476_NULL_Pointer_Dereference__int_array_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19687()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19686()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19731()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_31_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19730()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_31_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19653()).runTest("CWE476_NULL_Pointer_Dereference__int_array_31_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19652()).runTest("CWE476_NULL_Pointer_Dereference__int_array_31_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19615()).runTest("CWE476_NULL_Pointer_Dereference__Integer_45_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19614()).runTest("CWE476_NULL_Pointer_Dereference__Integer_45_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19645()).runTest("CWE476_NULL_Pointer_Dereference__int_array_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19644()).runTest("CWE476_NULL_Pointer_Dereference__int_array_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19555()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19554()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19543()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19542()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19669()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19668()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19681()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19680()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19575()).runTest("CWE476_NULL_Pointer_Dereference__Integer_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19574()).runTest("CWE476_NULL_Pointer_Dereference__Integer_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19591()).runTest("CWE476_NULL_Pointer_Dereference__Integer_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19590()).runTest("CWE476_NULL_Pointer_Dereference__Integer_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19693()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19692()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19775()).runTest("CWE476_NULL_Pointer_Dereference__String_31_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19774()).runTest("CWE476_NULL_Pointer_Dereference__String_31_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19777()).runTest("CWE476_NULL_Pointer_Dereference__String_41_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19776()).runTest("CWE476_NULL_Pointer_Dereference__String_41_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19641()).runTest("CWE476_NULL_Pointer_Dereference__int_array_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19640()).runTest("CWE476_NULL_Pointer_Dereference__int_array_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19745()).runTest("CWE476_NULL_Pointer_Dereference__String_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19744()).runTest("CWE476_NULL_Pointer_Dereference__String_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19607()).runTest("CWE476_NULL_Pointer_Dereference__Integer_21_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19606()).runTest("CWE476_NULL_Pointer_Dereference__Integer_21_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19679()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19678()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19721()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19720()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19661()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19660()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19699()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19698()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19767()).runTest("CWE476_NULL_Pointer_Dereference__String_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19766()).runTest("CWE476_NULL_Pointer_Dereference__String_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19705()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19704()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19507()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19506()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19549()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19548()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19725()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19724()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19589()).runTest("CWE476_NULL_Pointer_Dereference__Integer_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19588()).runTest("CWE476_NULL_Pointer_Dereference__Integer_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19713()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19712()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19529()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19528()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19691()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19690()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19553()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19552()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19587()).runTest("CWE476_NULL_Pointer_Dereference__Integer_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19586()).runTest("CWE476_NULL_Pointer_Dereference__Integer_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19715()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19714()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19539()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19538()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19579()).runTest("CWE476_NULL_Pointer_Dereference__Integer_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19578()).runTest("CWE476_NULL_Pointer_Dereference__Integer_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19515()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_06_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19514()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_06_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19525()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19524()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19551()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19550()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19703()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_05_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19702()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_05_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19601()).runTest("CWE476_NULL_Pointer_Dereference__Integer_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19600()).runTest("CWE476_NULL_Pointer_Dereference__Integer_15_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19683()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19682()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19751()).runTest("CWE476_NULL_Pointer_Dereference__String_07_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19750()).runTest("CWE476_NULL_Pointer_Dereference__String_07_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19739()).runTest("CWE476_NULL_Pointer_Dereference__String_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19738()).runTest("CWE476_NULL_Pointer_Dereference__String_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19765()).runTest("CWE476_NULL_Pointer_Dereference__String_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19764()).runTest("CWE476_NULL_Pointer_Dereference__String_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19773()).runTest("CWE476_NULL_Pointer_Dereference__String_21_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19772()).runTest("CWE476_NULL_Pointer_Dereference__String_21_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19603()).runTest("CWE476_NULL_Pointer_Dereference__Integer_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19602()).runTest("CWE476_NULL_Pointer_Dereference__Integer_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19643()).runTest("CWE476_NULL_Pointer_Dereference__int_array_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19642()).runTest("CWE476_NULL_Pointer_Dereference__int_array_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19695()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19694()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19753()).runTest("CWE476_NULL_Pointer_Dereference__String_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19752()).runTest("CWE476_NULL_Pointer_Dereference__String_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19647()).runTest("CWE476_NULL_Pointer_Dereference__int_array_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19646()).runTest("CWE476_NULL_Pointer_Dereference__int_array_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19631()).runTest("CWE476_NULL_Pointer_Dereference__int_array_08_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19630()).runTest("CWE476_NULL_Pointer_Dereference__int_array_08_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19635()).runTest("CWE476_NULL_Pointer_Dereference__int_array_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19634()).runTest("CWE476_NULL_Pointer_Dereference__int_array_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19535()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_16_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19534()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_16_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19651()).runTest("CWE476_NULL_Pointer_Dereference__int_array_21_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19650()).runTest("CWE476_NULL_Pointer_Dereference__int_array_21_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19565()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19564()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19537()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19536()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19689()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19688()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_b");
        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
