package testcases.CWE476_NULL_Pointer_Dereference;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */
        (new testcases.CWE476_NULL_Pointer_Dereference.J19509()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19508()).runTest("CWE476_NULL_Pointer_Dereference__binary_if_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19741()).runTest("CWE476_NULL_Pointer_Dereference__String_02_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19740()).runTest("CWE476_NULL_Pointer_Dereference__String_02_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19667()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19666()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19759()).runTest("CWE476_NULL_Pointer_Dereference__String_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19758()).runTest("CWE476_NULL_Pointer_Dereference__String_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19685()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19684()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19761()).runTest("CWE476_NULL_Pointer_Dereference__String_12_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19760()).runTest("CWE476_NULL_Pointer_Dereference__String_12_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19743()).runTest("CWE476_NULL_Pointer_Dereference__String_03_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19742()).runTest("CWE476_NULL_Pointer_Dereference__String_03_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19737()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_45_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19736()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_45_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19649()).runTest("CWE476_NULL_Pointer_Dereference__int_array_17_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19648()).runTest("CWE476_NULL_Pointer_Dereference__int_array_17_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19557()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_10_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19556()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_10_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19687()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19686()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19731()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_31_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19730()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_31_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19555()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19554()).runTest("CWE476_NULL_Pointer_Dereference__deref_after_check_09_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19681()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19680()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19721()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_14_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19720()).runTest("CWE476_NULL_Pointer_Dereference__StringBuilder_14_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19661()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19660()).runTest("CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_b");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19589()).runTest("CWE476_NULL_Pointer_Dereference__Integer_09_gd");
        (new testcases.CWE476_NULL_Pointer_Dereference.J19588()).runTest("CWE476_NULL_Pointer_Dereference__Integer_09_b");
        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
