package testcases.CWE129_Improper_Validation_of_Array_Index.s02;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11055()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11054()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10717()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10716()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10805()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10804()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11027()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11026()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10945()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10944()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10939()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10938()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11039()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11038()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10817()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10816()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10907()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10906()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10803()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10802()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10709()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10708()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11049()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11048()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10955()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10954()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10991()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10990()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10847()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10846()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10989()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10988()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10971()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10970()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10725()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10724()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10765()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10764()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10997()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10996()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10861()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10860()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10927()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10926()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11037()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11036()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10825()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10824()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10959()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10958()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11005()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11004()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10721()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10720()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10795()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10794()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10749()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10748()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11041()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11040()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11077()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11076()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11035()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11034()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10707()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10706()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10855()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10854()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11029()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11028()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10973()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10972()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10983()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10982()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10713()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10712()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11067()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11066()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11013()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11012()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11075()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11074()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10901()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10900()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10943()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10942()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11001()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11000()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10999()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10998()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10935()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10934()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10867()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10866()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10761()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10760()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11061()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11060()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10881()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10880()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10913()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10912()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10773()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10772()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11087()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11086()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10897()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10896()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11063()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11062()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11093()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11092()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10929()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10928()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10849()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10848()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11025()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11024()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11079()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11078()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10789()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10788()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10953()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10952()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10859()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10858()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11015()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11014()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11019()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11018()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10925()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10924()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10715()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10714()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10723()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10722()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10885()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10884()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10937()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10936()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10779()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10778()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10963()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10962()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11007()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11006()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10829()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10828()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10879()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10878()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11095()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11094()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10975()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10974()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10827()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10826()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10947()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10946()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10891()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10890()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10799()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10798()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10909()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10908()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11031()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11030()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10819()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10818()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11069()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11068()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10777()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10776()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10993()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10992()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10759()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10758()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10987()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10986()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10919()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10918()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11053()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11052()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11009()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11008()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11071()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11070()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11017()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11016()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10821()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10820()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11045()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11044()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10745()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10744()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10729()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10728()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11023()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11022()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10877()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10876()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10949()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10948()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10915()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10914()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10931()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10930()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10957()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10956()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10967()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10966()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10961()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10960()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10933()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10932()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10743()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10742()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10747()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10746()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10739()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10738()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11081()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11080()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10831()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10830()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10807()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10806()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10843()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10842()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10857()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10856()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10733()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10732()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10755()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10754()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10875()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10874()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11057()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11056()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10981()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10980()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10737()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10736()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10815()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10814()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10757()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10756()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10977()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10976()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10813()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10812()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10785()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10784()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11065()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11064()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10969()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10968()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11003()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11002()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11011()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11010()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11099()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11098()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10995()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10994()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11083()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11082()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10921()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10920()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10833()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10832()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10711()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10710()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10811()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10810()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11033()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11032()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10753()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10752()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10979()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10978()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10941()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10940()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10923()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10922()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10871()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10870()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10705()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10704()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10887()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10886()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10889()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10888()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10793()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10792()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10731()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10730()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10895()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10894()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10841()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10840()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10769()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10768()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11021()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11020()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10853()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10852()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10735()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10734()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10903()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10902()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10763()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10762()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10837()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10836()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10873()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10872()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10911()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10910()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10767()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10766()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10869()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10868()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11089()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11088()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10787()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10786()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10951()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10950()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10835()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10834()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10893()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10892()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10783()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10782()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10801()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10800()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10741()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10740()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10823()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10822()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10781()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10780()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10917()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10916()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11051()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11050()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10845()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10844()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11091()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11090()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10839()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10838()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10985()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10984()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10727()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10726()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11047()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11046()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10965()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10964()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_min_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11043()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11042()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10865()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10864()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10797()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10796()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10751()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10750()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11085()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11084()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10899()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10898()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11059()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11058()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10883()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10882()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10905()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10904()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_read_check_max_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11073()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11072()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10791()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10790()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10775()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10774()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10771()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10770()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10809()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10808()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11097()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J11096()).runTest("CWE129_Improper_Validation_of_Array_Index__File_array_write_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10851()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10850()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10863()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10862()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_write_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10719()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s02.J10718()).runTest("CWE129_Improper_Validation_of_Array_Index__Environment_array_read_check_min_08_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
