package testcases.CWE89_SQL_Injection.s02;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_08_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_08_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_16_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_16_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_03_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_03_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_17_good()).runTest("CWE89_SQL_Injection__File_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_17_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_13_good()).runTest("CWE89_SQL_Injection__File_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_13_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_03_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_03_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_15_good()).runTest("CWE89_SQL_Injection__File_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_15_bad()).runTest("CWE89_SQL_Injection__File_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_05_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_05_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_41_good()).runTest("CWE89_SQL_Injection__Environment_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_41_bad()).runTest("CWE89_SQL_Injection__Environment_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_05_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_05_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_41_good()).runTest("CWE89_SQL_Injection__File_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_41_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_01_good()).runTest("CWE89_SQL_Injection__Environment_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_01_bad()).runTest("CWE89_SQL_Injection__Environment_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_13_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_13_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_10_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_10_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_10_good()).runTest("CWE89_SQL_Injection__Environment_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_10_bad()).runTest("CWE89_SQL_Injection__Environment_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_11_good()).runTest("CWE89_SQL_Injection__Environment_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_11_bad()).runTest("CWE89_SQL_Injection__Environment_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_05_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_05_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_12_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_12_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_13_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_13_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_02_good()).runTest("CWE89_SQL_Injection__File_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_02_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_05_good()).runTest("CWE89_SQL_Injection__Environment_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_05_bad()).runTest("CWE89_SQL_Injection__Environment_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_14_good()).runTest("CWE89_SQL_Injection__File_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_14_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_31_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_31_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_41_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_41_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_09_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_09_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_12_good()).runTest("CWE89_SQL_Injection__File_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_12_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_07_good()).runTest("CWE89_SQL_Injection__Environment_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_07_bad()).runTest("CWE89_SQL_Injection__Environment_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_21_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_21_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_04_good()).runTest("CWE89_SQL_Injection__Environment_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_04_bad()).runTest("CWE89_SQL_Injection__Environment_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_02_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_02_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_09_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_09_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_10_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_10_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_04_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_04_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_06_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_06_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_02_good()).runTest("CWE89_SQL_Injection__Environment_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_02_bad()).runTest("CWE89_SQL_Injection__Environment_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_16_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_16_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_15_good()).runTest("CWE89_SQL_Injection__File_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_15_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_15_good()).runTest("CWE89_SQL_Injection__Environment_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_15_bad()).runTest("CWE89_SQL_Injection__Environment_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_42_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_42_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_41_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_41_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_04_good()).runTest("CWE89_SQL_Injection__File_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_04_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_10_good()).runTest("CWE89_SQL_Injection__File_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_10_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_45_good()).runTest("CWE89_SQL_Injection__File_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_45_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_03_good()).runTest("CWE89_SQL_Injection__File_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_03_bad()).runTest("CWE89_SQL_Injection__File_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_01_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_01_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_17_good()).runTest("CWE89_SQL_Injection__File_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_17_bad()).runTest("CWE89_SQL_Injection__File_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_16_good()).runTest("CWE89_SQL_Injection__File_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_16_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_02_good()).runTest("CWE89_SQL_Injection__File_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_02_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_31_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_31_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_17_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_17_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_17_good()).runTest("CWE89_SQL_Injection__File_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_17_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_42_good()).runTest("CWE89_SQL_Injection__File_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_42_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_45_good()).runTest("CWE89_SQL_Injection__File_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_45_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_10_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_10_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_01_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_01_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_12_good()).runTest("CWE89_SQL_Injection__Environment_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_12_bad()).runTest("CWE89_SQL_Injection__Environment_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_41_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_41_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_04_good()).runTest("CWE89_SQL_Injection__File_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_04_bad()).runTest("CWE89_SQL_Injection__File_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_11_good()).runTest("CWE89_SQL_Injection__File_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_11_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_14_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_14_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_02_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_02_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_06_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_06_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_07_good()).runTest("CWE89_SQL_Injection__File_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_07_bad()).runTest("CWE89_SQL_Injection__File_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_09_good()).runTest("CWE89_SQL_Injection__Environment_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_09_bad()).runTest("CWE89_SQL_Injection__Environment_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_13_good()).runTest("CWE89_SQL_Injection__Environment_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_13_bad()).runTest("CWE89_SQL_Injection__Environment_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_16_good()).runTest("CWE89_SQL_Injection__File_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_16_bad()).runTest("CWE89_SQL_Injection__File_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_21_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_21_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_06_good()).runTest("CWE89_SQL_Injection__Environment_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_06_bad()).runTest("CWE89_SQL_Injection__Environment_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_08_good()).runTest("CWE89_SQL_Injection__File_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_08_bad()).runTest("CWE89_SQL_Injection__File_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_12_good()).runTest("CWE89_SQL_Injection__File_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_12_bad()).runTest("CWE89_SQL_Injection__File_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_16_good()).runTest("CWE89_SQL_Injection__Environment_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_16_bad()).runTest("CWE89_SQL_Injection__Environment_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_45_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_45_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_41_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_41_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_14_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_14_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_21_good()).runTest("CWE89_SQL_Injection__File_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_21_bad()).runTest("CWE89_SQL_Injection__File_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_31_good()).runTest("CWE89_SQL_Injection__File_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_31_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_03_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_03_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_09_good()).runTest("CWE89_SQL_Injection__File_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_09_bad()).runTest("CWE89_SQL_Injection__File_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_15_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_15_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_12_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_12_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_17_good()).runTest("CWE89_SQL_Injection__Environment_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_17_bad()).runTest("CWE89_SQL_Injection__Environment_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_13_good()).runTest("CWE89_SQL_Injection__File_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_13_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_07_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_07_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_09_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_09_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_12_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_12_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_05_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_05_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_01_good()).runTest("CWE89_SQL_Injection__File_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_01_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_16_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_16_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_05_good()).runTest("CWE89_SQL_Injection__File_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_05_bad()).runTest("CWE89_SQL_Injection__File_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_13_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_13_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_08_good()).runTest("CWE89_SQL_Injection__File_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_08_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_13_good()).runTest("CWE89_SQL_Injection__File_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_13_bad()).runTest("CWE89_SQL_Injection__File_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_42_good()).runTest("CWE89_SQL_Injection__File_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_42_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_31_good()).runTest("CWE89_SQL_Injection__Environment_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_31_bad()).runTest("CWE89_SQL_Injection__Environment_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_08_good()).runTest("CWE89_SQL_Injection__File_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_08_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_08_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_08_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_04_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_04_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_11_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_11_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_21_good()).runTest("CWE89_SQL_Injection__File_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_21_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_04_good()).runTest("CWE89_SQL_Injection__File_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_04_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_31_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_31_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_04_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_04_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_10_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_10_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_15_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_15_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_03_good()).runTest("CWE89_SQL_Injection__Environment_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_03_bad()).runTest("CWE89_SQL_Injection__Environment_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_13_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_13_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_31_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_31_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_09_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_09_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_09_good()).runTest("CWE89_SQL_Injection__File_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_09_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_45_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_45_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_03_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_03_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_13_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_13_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_14_good()).runTest("CWE89_SQL_Injection__File_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_14_bad()).runTest("CWE89_SQL_Injection__File_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_06_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_06_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_45_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_45_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_16_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_16_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_11_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_11_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_14_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_14_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_45_good()).runTest("CWE89_SQL_Injection__Environment_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_45_bad()).runTest("CWE89_SQL_Injection__Environment_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_21_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_21_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_21_good()).runTest("CWE89_SQL_Injection__Environment_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_21_bad()).runTest("CWE89_SQL_Injection__Environment_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_03_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_03_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_03_good()).runTest("CWE89_SQL_Injection__File_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_03_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_15_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_15_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_15_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_15_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_21_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_21_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_07_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_07_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_17_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_17_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_17_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_17_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_08_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_08_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_11_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_11_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_41_good()).runTest("CWE89_SQL_Injection__File_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_41_bad()).runTest("CWE89_SQL_Injection__File_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_11_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_11_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_07_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_07_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_04_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_04_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_06_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_06_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_07_good()).runTest("CWE89_SQL_Injection__File_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_07_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_42_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_42_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_12_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_12_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_11_good()).runTest("CWE89_SQL_Injection__File_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_11_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_41_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_41_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_14_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_14_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_10_good()).runTest("CWE89_SQL_Injection__File_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_10_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_10_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_10_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_01_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_01_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_16_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_16_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_08_good()).runTest("CWE89_SQL_Injection__Environment_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_08_bad()).runTest("CWE89_SQL_Injection__Environment_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_02_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_02_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_17_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_17_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_14_good()).runTest("CWE89_SQL_Injection__Environment_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_14_bad()).runTest("CWE89_SQL_Injection__Environment_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_31_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_31_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_10_good()).runTest("CWE89_SQL_Injection__File_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_10_bad()).runTest("CWE89_SQL_Injection__File_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_45_good()).runTest("CWE89_SQL_Injection__File_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_45_bad()).runTest("CWE89_SQL_Injection__File_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_06_good()).runTest("CWE89_SQL_Injection__File_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_06_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_21_good()).runTest("CWE89_SQL_Injection__File_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_21_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_42_good()).runTest("CWE89_SQL_Injection__File_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_42_bad()).runTest("CWE89_SQL_Injection__File_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_12_good()).runTest("CWE89_SQL_Injection__File_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_12_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_07_good()).runTest("CWE89_SQL_Injection__File_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_07_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_42_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_42_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_42_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_42_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_31_good()).runTest("CWE89_SQL_Injection__File_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_31_bad()).runTest("CWE89_SQL_Injection__File_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_41_good()).runTest("CWE89_SQL_Injection__File_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_41_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_14_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_14_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_02_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_02_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_01_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_01_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_01_good()).runTest("CWE89_SQL_Injection__File_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_01_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_17_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_17_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_06_good()).runTest("CWE89_SQL_Injection__File_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_06_bad()).runTest("CWE89_SQL_Injection__File_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_02_good()).runTest("CWE89_SQL_Injection__File_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_02_bad()).runTest("CWE89_SQL_Injection__File_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_21_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_21_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_03_good()).runTest("CWE89_SQL_Injection__File_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_03_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_07_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_07_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_01_good()).runTest("CWE89_SQL_Injection__File_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_01_bad()).runTest("CWE89_SQL_Injection__File_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_06_good()).runTest("CWE89_SQL_Injection__File_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_06_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_08_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_08_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_05_good()).runTest("CWE89_SQL_Injection__File_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_05_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_15_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_15_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_42_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_42_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_08_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_08_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_45_good()).runTest("CWE89_SQL_Injection__Environment_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeQuery_45_bad()).runTest("CWE89_SQL_Injection__Environment_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_31_good()).runTest("CWE89_SQL_Injection__File_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_31_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_02_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_02_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_11_good()).runTest("CWE89_SQL_Injection__File_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_execute_11_bad()).runTest("CWE89_SQL_Injection__File_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_16_good()).runTest("CWE89_SQL_Injection__File_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_16_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_07_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_07_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_04_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_04_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_01_good()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_prepareStatement_01_bad()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_15_good()).runTest("CWE89_SQL_Injection__File_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_15_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_42_good()).runTest("CWE89_SQL_Injection__Environment_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_execute_42_bad()).runTest("CWE89_SQL_Injection__Environment_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_09_good()).runTest("CWE89_SQL_Injection__File_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_09_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_09_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_09_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_06_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_06_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_14_good()).runTest("CWE89_SQL_Injection__File_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeQuery_14_bad()).runTest("CWE89_SQL_Injection__File_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_05_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_05_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_05_good()).runTest("CWE89_SQL_Injection__File_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeBatch_05_bad()).runTest("CWE89_SQL_Injection__File_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_11_good()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__Environment_executeUpdate_11_bad()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_12_good()).runTest("CWE89_SQL_Injection__File_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_prepareStatement_12_bad()).runTest("CWE89_SQL_Injection__File_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_45_good()).runTest("CWE89_SQL_Injection__File_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s02.CWE89_SQL_Injection__File_executeUpdate_45_bad()).runTest("CWE89_SQL_Injection__File_executeUpdate_45_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
