package testcases.CWE89_SQL_Injection.s02;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s02.J23605()).runTest("CWE89_SQL_Injection__File_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23604()).runTest("CWE89_SQL_Injection__File_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23533()).runTest("CWE89_SQL_Injection__File_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23532()).runTest("CWE89_SQL_Injection__File_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23595()).runTest("CWE89_SQL_Injection__File_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23594()).runTest("CWE89_SQL_Injection__File_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23491()).runTest("CWE89_SQL_Injection__File_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23490()).runTest("CWE89_SQL_Injection__File_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23483()).runTest("CWE89_SQL_Injection__File_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23482()).runTest("CWE89_SQL_Injection__File_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23375()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23374()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23575()).runTest("CWE89_SQL_Injection__File_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23574()).runTest("CWE89_SQL_Injection__File_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23291()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23290()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23365()).runTest("CWE89_SQL_Injection__Environment_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23364()).runTest("CWE89_SQL_Injection__Environment_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23247()).runTest("CWE89_SQL_Injection__Environment_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23246()).runTest("CWE89_SQL_Injection__Environment_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23497()).runTest("CWE89_SQL_Injection__File_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23496()).runTest("CWE89_SQL_Injection__File_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23327()).runTest("CWE89_SQL_Injection__Environment_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23326()).runTest("CWE89_SQL_Injection__Environment_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23615()).runTest("CWE89_SQL_Injection__File_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23614()).runTest("CWE89_SQL_Injection__File_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23521()).runTest("CWE89_SQL_Injection__File_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23520()).runTest("CWE89_SQL_Injection__File_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23345()).runTest("CWE89_SQL_Injection__Environment_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23344()).runTest("CWE89_SQL_Injection__Environment_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23347()).runTest("CWE89_SQL_Injection__Environment_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23346()).runTest("CWE89_SQL_Injection__Environment_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23599()).runTest("CWE89_SQL_Injection__File_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23598()).runTest("CWE89_SQL_Injection__File_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23261()).runTest("CWE89_SQL_Injection__Environment_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23260()).runTest("CWE89_SQL_Injection__Environment_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23263()).runTest("CWE89_SQL_Injection__Environment_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23262()).runTest("CWE89_SQL_Injection__Environment_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23461()).runTest("CWE89_SQL_Injection__File_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23460()).runTest("CWE89_SQL_Injection__File_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23335()).runTest("CWE89_SQL_Injection__Environment_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23334()).runTest("CWE89_SQL_Injection__Environment_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23441()).runTest("CWE89_SQL_Injection__File_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23440()).runTest("CWE89_SQL_Injection__File_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23275()).runTest("CWE89_SQL_Injection__Environment_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23274()).runTest("CWE89_SQL_Injection__Environment_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23541()).runTest("CWE89_SQL_Injection__File_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23540()).runTest("CWE89_SQL_Injection__File_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23387()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23386()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23481()).runTest("CWE89_SQL_Injection__File_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23480()).runTest("CWE89_SQL_Injection__File_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23339()).runTest("CWE89_SQL_Injection__Environment_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23338()).runTest("CWE89_SQL_Injection__Environment_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23273()).runTest("CWE89_SQL_Injection__Environment_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23272()).runTest("CWE89_SQL_Injection__Environment_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23333()).runTest("CWE89_SQL_Injection__Environment_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23332()).runTest("CWE89_SQL_Injection__Environment_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23593()).runTest("CWE89_SQL_Injection__File_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23592()).runTest("CWE89_SQL_Injection__File_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23299()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23298()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23301()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23300()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23289()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23288()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23293()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23292()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23329()).runTest("CWE89_SQL_Injection__Environment_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23328()).runTest("CWE89_SQL_Injection__Environment_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23313()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23312()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23443()).runTest("CWE89_SQL_Injection__File_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23442()).runTest("CWE89_SQL_Injection__File_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23355()).runTest("CWE89_SQL_Injection__Environment_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23354()).runTest("CWE89_SQL_Injection__Environment_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23631()).runTest("CWE89_SQL_Injection__File_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23630()).runTest("CWE89_SQL_Injection__File_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23277()).runTest("CWE89_SQL_Injection__Environment_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23276()).runTest("CWE89_SQL_Injection__Environment_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23421()).runTest("CWE89_SQL_Injection__File_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23420()).runTest("CWE89_SQL_Injection__File_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23477()).runTest("CWE89_SQL_Injection__File_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23476()).runTest("CWE89_SQL_Injection__File_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23501()).runTest("CWE89_SQL_Injection__File_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23500()).runTest("CWE89_SQL_Injection__File_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23551()).runTest("CWE89_SQL_Injection__File_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23550()).runTest("CWE89_SQL_Injection__File_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23283()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23282()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23579()).runTest("CWE89_SQL_Injection__File_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23578()).runTest("CWE89_SQL_Injection__File_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23489()).runTest("CWE89_SQL_Injection__File_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23488()).runTest("CWE89_SQL_Injection__File_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23417()).runTest("CWE89_SQL_Injection__File_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23416()).runTest("CWE89_SQL_Injection__File_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23539()).runTest("CWE89_SQL_Injection__File_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23538()).runTest("CWE89_SQL_Injection__File_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23623()).runTest("CWE89_SQL_Injection__File_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23622()).runTest("CWE89_SQL_Injection__File_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23447()).runTest("CWE89_SQL_Injection__File_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23446()).runTest("CWE89_SQL_Injection__File_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23455()).runTest("CWE89_SQL_Injection__File_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23454()).runTest("CWE89_SQL_Injection__File_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23457()).runTest("CWE89_SQL_Injection__File_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23456()).runTest("CWE89_SQL_Injection__File_executeBatch_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23609()).runTest("CWE89_SQL_Injection__File_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23608()).runTest("CWE89_SQL_Injection__File_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23239()).runTest("CWE89_SQL_Injection__Environment_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23238()).runTest("CWE89_SQL_Injection__Environment_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23349()).runTest("CWE89_SQL_Injection__Environment_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23348()).runTest("CWE89_SQL_Injection__Environment_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23629()).runTest("CWE89_SQL_Injection__File_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23628()).runTest("CWE89_SQL_Injection__File_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23553()).runTest("CWE89_SQL_Injection__File_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23552()).runTest("CWE89_SQL_Injection__File_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23479()).runTest("CWE89_SQL_Injection__File_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23478()).runTest("CWE89_SQL_Injection__File_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23397()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23396()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23373()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23372()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23381()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23380()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23559()).runTest("CWE89_SQL_Injection__File_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23558()).runTest("CWE89_SQL_Injection__File_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23343()).runTest("CWE89_SQL_Injection__Environment_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23342()).runTest("CWE89_SQL_Injection__Environment_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23351()).runTest("CWE89_SQL_Injection__Environment_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23350()).runTest("CWE89_SQL_Injection__Environment_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23577()).runTest("CWE89_SQL_Injection__File_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23576()).runTest("CWE89_SQL_Injection__File_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23537()).runTest("CWE89_SQL_Injection__File_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23536()).runTest("CWE89_SQL_Injection__File_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23337()).runTest("CWE89_SQL_Injection__Environment_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23336()).runTest("CWE89_SQL_Injection__Environment_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23561()).runTest("CWE89_SQL_Injection__File_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23560()).runTest("CWE89_SQL_Injection__File_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23569()).runTest("CWE89_SQL_Injection__File_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23568()).runTest("CWE89_SQL_Injection__File_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23357()).runTest("CWE89_SQL_Injection__Environment_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23356()).runTest("CWE89_SQL_Injection__Environment_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23633()).runTest("CWE89_SQL_Injection__File_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23632()).runTest("CWE89_SQL_Injection__File_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23321()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23320()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23617()).runTest("CWE89_SQL_Injection__File_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23616()).runTest("CWE89_SQL_Injection__File_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23581()).runTest("CWE89_SQL_Injection__File_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23580()).runTest("CWE89_SQL_Injection__File_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23495()).runTest("CWE89_SQL_Injection__File_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23494()).runTest("CWE89_SQL_Injection__File_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23243()).runTest("CWE89_SQL_Injection__Environment_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23242()).runTest("CWE89_SQL_Injection__Environment_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23563()).runTest("CWE89_SQL_Injection__File_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23562()).runTest("CWE89_SQL_Injection__File_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23531()).runTest("CWE89_SQL_Injection__File_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23530()).runTest("CWE89_SQL_Injection__File_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23525()).runTest("CWE89_SQL_Injection__File_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23524()).runTest("CWE89_SQL_Injection__File_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23359()).runTest("CWE89_SQL_Injection__Environment_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23358()).runTest("CWE89_SQL_Injection__Environment_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23439()).runTest("CWE89_SQL_Injection__File_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23438()).runTest("CWE89_SQL_Injection__File_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23603()).runTest("CWE89_SQL_Injection__File_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23602()).runTest("CWE89_SQL_Injection__File_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23255()).runTest("CWE89_SQL_Injection__Environment_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23254()).runTest("CWE89_SQL_Injection__Environment_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23393()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23392()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23379()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23378()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23415()).runTest("CWE89_SQL_Injection__File_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23414()).runTest("CWE89_SQL_Injection__File_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23269()).runTest("CWE89_SQL_Injection__Environment_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23268()).runTest("CWE89_SQL_Injection__Environment_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23555()).runTest("CWE89_SQL_Injection__File_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23554()).runTest("CWE89_SQL_Injection__File_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23307()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23306()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23473()).runTest("CWE89_SQL_Injection__File_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23472()).runTest("CWE89_SQL_Injection__File_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23571()).runTest("CWE89_SQL_Injection__File_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23570()).runTest("CWE89_SQL_Injection__File_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23499()).runTest("CWE89_SQL_Injection__File_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23498()).runTest("CWE89_SQL_Injection__File_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23363()).runTest("CWE89_SQL_Injection__Environment_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23362()).runTest("CWE89_SQL_Injection__Environment_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23429()).runTest("CWE89_SQL_Injection__File_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23428()).runTest("CWE89_SQL_Injection__File_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23385()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23384()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23597()).runTest("CWE89_SQL_Injection__File_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23596()).runTest("CWE89_SQL_Injection__File_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23523()).runTest("CWE89_SQL_Injection__File_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23522()).runTest("CWE89_SQL_Injection__File_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23493()).runTest("CWE89_SQL_Injection__File_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23492()).runTest("CWE89_SQL_Injection__File_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23465()).runTest("CWE89_SQL_Injection__File_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23464()).runTest("CWE89_SQL_Injection__File_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23319()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23318()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23245()).runTest("CWE89_SQL_Injection__Environment_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23244()).runTest("CWE89_SQL_Injection__Environment_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23389()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23388()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23267()).runTest("CWE89_SQL_Injection__Environment_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23266()).runTest("CWE89_SQL_Injection__Environment_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23331()).runTest("CWE89_SQL_Injection__Environment_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23330()).runTest("CWE89_SQL_Injection__Environment_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23527()).runTest("CWE89_SQL_Injection__File_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23526()).runTest("CWE89_SQL_Injection__File_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23407()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23406()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23607()).runTest("CWE89_SQL_Injection__File_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23606()).runTest("CWE89_SQL_Injection__File_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23431()).runTest("CWE89_SQL_Injection__File_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23430()).runTest("CWE89_SQL_Injection__File_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23413()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23412()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23507()).runTest("CWE89_SQL_Injection__File_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23506()).runTest("CWE89_SQL_Injection__File_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23395()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s02.J23394()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23573()).runTest("CWE89_SQL_Injection__File_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23572()).runTest("CWE89_SQL_Injection__File_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23513()).runTest("CWE89_SQL_Injection__File_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23512()).runTest("CWE89_SQL_Injection__File_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23325()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23324()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23401()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23400()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23611()).runTest("CWE89_SQL_Injection__File_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23610()).runTest("CWE89_SQL_Injection__File_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23265()).runTest("CWE89_SQL_Injection__Environment_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23264()).runTest("CWE89_SQL_Injection__Environment_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23369()).runTest("CWE89_SQL_Injection__Environment_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23368()).runTest("CWE89_SQL_Injection__Environment_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23405()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23404()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23361()).runTest("CWE89_SQL_Injection__Environment_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23360()).runTest("CWE89_SQL_Injection__Environment_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23287()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23286()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23419()).runTest("CWE89_SQL_Injection__File_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23418()).runTest("CWE89_SQL_Injection__File_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23619()).runTest("CWE89_SQL_Injection__File_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23618()).runTest("CWE89_SQL_Injection__File_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23311()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23310()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23625()).runTest("CWE89_SQL_Injection__File_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23624()).runTest("CWE89_SQL_Injection__File_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23295()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23294()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23315()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23314()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23271()).runTest("CWE89_SQL_Injection__Environment_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23270()).runTest("CWE89_SQL_Injection__Environment_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23517()).runTest("CWE89_SQL_Injection__File_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23516()).runTest("CWE89_SQL_Injection__File_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23259()).runTest("CWE89_SQL_Injection__Environment_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23258()).runTest("CWE89_SQL_Injection__Environment_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23585()).runTest("CWE89_SQL_Injection__File_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23584()).runTest("CWE89_SQL_Injection__File_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23391()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23390()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23251()).runTest("CWE89_SQL_Injection__Environment_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23250()).runTest("CWE89_SQL_Injection__Environment_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23377()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23376()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23249()).runTest("CWE89_SQL_Injection__Environment_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23248()).runTest("CWE89_SQL_Injection__Environment_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23427()).runTest("CWE89_SQL_Injection__File_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23426()).runTest("CWE89_SQL_Injection__File_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23411()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23410()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23305()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23304()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23435()).runTest("CWE89_SQL_Injection__File_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23434()).runTest("CWE89_SQL_Injection__File_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23409()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23408()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23309()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23308()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23433()).runTest("CWE89_SQL_Injection__File_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23432()).runTest("CWE89_SQL_Injection__File_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23257()).runTest("CWE89_SQL_Injection__Environment_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23256()).runTest("CWE89_SQL_Injection__Environment_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23591()).runTest("CWE89_SQL_Injection__File_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23590()).runTest("CWE89_SQL_Injection__File_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23621()).runTest("CWE89_SQL_Injection__File_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23620()).runTest("CWE89_SQL_Injection__File_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23341()).runTest("CWE89_SQL_Injection__Environment_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23340()).runTest("CWE89_SQL_Injection__Environment_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23241()).runTest("CWE89_SQL_Injection__Environment_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23240()).runTest("CWE89_SQL_Injection__Environment_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23403()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23402()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23353()).runTest("CWE89_SQL_Injection__Environment_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23352()).runTest("CWE89_SQL_Injection__Environment_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23627()).runTest("CWE89_SQL_Injection__File_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23626()).runTest("CWE89_SQL_Injection__File_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23565()).runTest("CWE89_SQL_Injection__File_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s02.J23564()).runTest("CWE89_SQL_Injection__File_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23589()).runTest("CWE89_SQL_Injection__File_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23588()).runTest("CWE89_SQL_Injection__File_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23425()).runTest("CWE89_SQL_Injection__File_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23424()).runTest("CWE89_SQL_Injection__File_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23449()).runTest("CWE89_SQL_Injection__File_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23448()).runTest("CWE89_SQL_Injection__File_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23587()).runTest("CWE89_SQL_Injection__File_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23586()).runTest("CWE89_SQL_Injection__File_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23437()).runTest("CWE89_SQL_Injection__File_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23436()).runTest("CWE89_SQL_Injection__File_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23471()).runTest("CWE89_SQL_Injection__File_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23470()).runTest("CWE89_SQL_Injection__File_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23279()).runTest("CWE89_SQL_Injection__Environment_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23278()).runTest("CWE89_SQL_Injection__Environment_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23543()).runTest("CWE89_SQL_Injection__File_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23542()).runTest("CWE89_SQL_Injection__File_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23583()).runTest("CWE89_SQL_Injection__File_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23582()).runTest("CWE89_SQL_Injection__File_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23453()).runTest("CWE89_SQL_Injection__File_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s02.J23452()).runTest("CWE89_SQL_Injection__File_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23529()).runTest("CWE89_SQL_Injection__File_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23528()).runTest("CWE89_SQL_Injection__File_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23285()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23284()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23503()).runTest("CWE89_SQL_Injection__File_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23502()).runTest("CWE89_SQL_Injection__File_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23459()).runTest("CWE89_SQL_Injection__File_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23458()).runTest("CWE89_SQL_Injection__File_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23535()).runTest("CWE89_SQL_Injection__File_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s02.J23534()).runTest("CWE89_SQL_Injection__File_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23557()).runTest("CWE89_SQL_Injection__File_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23556()).runTest("CWE89_SQL_Injection__File_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23549()).runTest("CWE89_SQL_Injection__File_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23548()).runTest("CWE89_SQL_Injection__File_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23317()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s02.J23316()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23463()).runTest("CWE89_SQL_Injection__File_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s02.J23462()).runTest("CWE89_SQL_Injection__File_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23383()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23382()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23547()).runTest("CWE89_SQL_Injection__File_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23546()).runTest("CWE89_SQL_Injection__File_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23469()).runTest("CWE89_SQL_Injection__File_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23468()).runTest("CWE89_SQL_Injection__File_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23253()).runTest("CWE89_SQL_Injection__Environment_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23252()).runTest("CWE89_SQL_Injection__Environment_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23467()).runTest("CWE89_SQL_Injection__File_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23466()).runTest("CWE89_SQL_Injection__File_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23399()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23398()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23323()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23322()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23297()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s02.J23296()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23281()).runTest("CWE89_SQL_Injection__Environment_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23280()).runTest("CWE89_SQL_Injection__Environment_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23451()).runTest("CWE89_SQL_Injection__File_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s02.J23450()).runTest("CWE89_SQL_Injection__File_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23505()).runTest("CWE89_SQL_Injection__File_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s02.J23504()).runTest("CWE89_SQL_Injection__File_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23567()).runTest("CWE89_SQL_Injection__File_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23566()).runTest("CWE89_SQL_Injection__File_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23445()).runTest("CWE89_SQL_Injection__File_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s02.J23444()).runTest("CWE89_SQL_Injection__File_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23515()).runTest("CWE89_SQL_Injection__File_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s02.J23514()).runTest("CWE89_SQL_Injection__File_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23509()).runTest("CWE89_SQL_Injection__File_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s02.J23508()).runTest("CWE89_SQL_Injection__File_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23371()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s02.J23370()).runTest("CWE89_SQL_Injection__Environment_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23487()).runTest("CWE89_SQL_Injection__File_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s02.J23486()).runTest("CWE89_SQL_Injection__File_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23367()).runTest("CWE89_SQL_Injection__Environment_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s02.J23366()).runTest("CWE89_SQL_Injection__Environment_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23475()).runTest("CWE89_SQL_Injection__File_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23474()).runTest("CWE89_SQL_Injection__File_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23519()).runTest("CWE89_SQL_Injection__File_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s02.J23518()).runTest("CWE89_SQL_Injection__File_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23601()).runTest("CWE89_SQL_Injection__File_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s02.J23600()).runTest("CWE89_SQL_Injection__File_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23485()).runTest("CWE89_SQL_Injection__File_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s02.J23484()).runTest("CWE89_SQL_Injection__File_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23511()).runTest("CWE89_SQL_Injection__File_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23510()).runTest("CWE89_SQL_Injection__File_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23423()).runTest("CWE89_SQL_Injection__File_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s02.J23422()).runTest("CWE89_SQL_Injection__File_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23303()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s02.J23302()).runTest("CWE89_SQL_Injection__Environment_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23613()).runTest("CWE89_SQL_Injection__File_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s02.J23612()).runTest("CWE89_SQL_Injection__File_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s02.J23545()).runTest("CWE89_SQL_Injection__File_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s02.J23544()).runTest("CWE89_SQL_Injection__File_executeUpdate_45_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
