package testcases.CWE89_SQL_Injection.s02;

import javax.servlet.http.*;

public class ServletMain extends HttpServlet {

    private static final long serialVersionUID = 1L; /* needed since Servlets are serializable */


    public void doPost(HttpServletRequest request, HttpServletResponse response) {
        doGet(request, response);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        doGetCWE1(request, response);
        doGetCWE2(request, response);
        doGetCWE3(request, response);
        doGetCWE4(request, response);
        doGetCWE5(request, response);
        doGetCWE6(request, response);
        doGetCWE7(request, response);
        doGetCWE8(request, response);
        doGetCWE9(request, response);
    }

    private static void doGetCWE1(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-1 */

            /* END-AUTOGENERATED-SERVLET-TESTS-1 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE1 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE2(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-2 */

            /* END-AUTOGENERATED-SERVLET-TESTS-2 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE2 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

            /* END-AUTOGENERATED-SERVLET-TESTS-3 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE3 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE4(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-4 */

            /* END-AUTOGENERATED-SERVLET-TESTS-4 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE4 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE5(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-5 */

            /* END-AUTOGENERATED-SERVLET-TESTS-5 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE5 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {

                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE6(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-6 */

            /* END-AUTOGENERATED-SERVLET-TESTS-6 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE6 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

            /* END-AUTOGENERATED-SERVLET-TESTS-7 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE7 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE8(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-8 */
            (new testcases.CWE89_SQL_Injection.s02.J23915()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23914()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23723()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23722()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23911()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23910()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23751()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23750()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23783()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23782()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23813()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23812()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23809()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23808()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23711()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23710()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23791()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23790()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23935()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23934()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23737()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23736()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23685()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23684()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23745()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23744()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23671()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23670()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23691()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23690()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23937()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23936()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23795()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23794()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23921()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23920()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23821()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23820()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23771()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23770()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23853()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23852()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23713()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23712()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23743()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23742()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23893()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23892()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23849()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23848()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23869()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23868()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23655()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23654()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23677()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23676()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23801()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23800()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23831()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23830()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23833()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23832()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23637()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23636()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23759()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23758()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23733()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23732()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23709()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23708()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23909()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23908()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23639()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23638()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23787()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23786()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23649()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23648()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23749()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23748()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23851()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23850()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23675()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23674()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23847()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23846()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23805()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23804()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23825()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23824()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23699()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23698()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23865()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23864()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23781()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23780()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23727()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23726()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23873()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23872()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23635()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23634()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23757()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23756()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23789()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23788()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23667()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23666()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23763()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23762()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23747()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23746()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23835()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23834()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23891()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23890()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23697()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23696()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23703()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23702()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23899()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23898()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23863()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23862()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23939()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23938()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23663()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23662()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23845()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23844()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23857()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23856()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23651()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23650()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23777()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23776()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23913()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23912()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23661()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23660()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23701()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23700()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23883()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23882()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23815()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23814()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23897()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23896()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23861()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23860()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23695()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23694()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23817()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23816()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23859()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23858()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23719()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23718()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23775()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23774()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23837()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23836()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23721()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23720()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23761()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23760()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23919()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23918()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23753()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23752()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23717()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23716()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23739()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23738()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23653()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23652()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23931()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23930()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23929()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23928()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23879()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23878()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23683()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23682()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23903()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23902()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23707()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23706()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23731()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23730()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23741()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23740()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23659()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23658()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23769()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23768()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23829()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23828()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23715()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23714()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23729()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23728()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23681()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23680()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23665()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23664()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23941()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23940()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23923()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23922()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23803()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23802()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23807()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23806()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23705()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23704()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23887()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23886()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23895()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23894()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23827()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23826()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23669()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23668()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23877()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23876()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23767()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23766()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23643()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23642()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23855()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23854()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23725()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23724()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23765()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23764()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23905()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23904()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23693()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23692()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23933()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23932()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23881()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23880()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23645()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23644()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23673()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23672()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23689()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23688()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23657()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23656()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23799()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23798()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23871()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23870()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23907()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23906()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23687()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23686()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23841()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23840()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23755()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23754()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23875()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23874()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23839()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23838()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23889()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23888()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23647()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23646()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23867()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23866()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23927()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23926()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23773()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23772()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23793()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23792()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23811()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23810()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23925()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23924()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23917()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23916()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23735()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23734()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23679()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23678()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23843()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23842()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23885()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23884()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23641()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23640()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23797()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23796()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23785()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23784()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23901()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23900()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23819()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23818()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23779()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23778()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23823()).runTest(request, response);
            (new testcases.CWE89_SQL_Injection.s02.J23822()).runTest(request, response);
            /* END-AUTOGENERATED-SERVLET-TESTS-8 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE8 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE9(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-9 */

            /* END-AUTOGENERATED-SERVLET-TESTS-9 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE9 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }
}

