package testcases.CWE89_SQL_Injection.s03;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s03.J24485()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24484()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24403()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24402()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24413()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24412()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24347()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24346()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24497()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24496()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24465()).runTest("CWE89_SQL_Injection__listen_tcp_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24464()).runTest("CWE89_SQL_Injection__listen_tcp_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24611()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24610()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24309()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24308()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24521()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24520()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24357()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24356()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24315()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24314()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24349()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24348()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24527()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24526()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24311()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24310()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24547()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24546()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24505()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24504()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24571()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24570()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24377()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24376()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24463()).runTest("CWE89_SQL_Injection__listen_tcp_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24462()).runTest("CWE89_SQL_Injection__listen_tcp_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24501()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24500()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24443()).runTest("CWE89_SQL_Injection__listen_tcp_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24442()).runTest("CWE89_SQL_Injection__listen_tcp_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24555()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24554()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24543()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24542()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24477()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24476()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24433()).runTest("CWE89_SQL_Injection__listen_tcp_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24432()).runTest("CWE89_SQL_Injection__listen_tcp_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24541()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24540()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24323()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24322()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24441()).runTest("CWE89_SQL_Injection__listen_tcp_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24440()).runTest("CWE89_SQL_Injection__listen_tcp_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24535()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24534()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24617()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24616()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24503()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24502()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24545()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24544()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24525()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24524()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24519()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24518()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24381()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24380()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24559()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24558()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24305()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24304()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24341()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24340()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24405()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24404()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24623()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24622()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24475()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24474()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24643()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24642()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24467()).runTest("CWE89_SQL_Injection__listen_tcp_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24466()).runTest("CWE89_SQL_Injection__listen_tcp_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24337()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24336()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24511()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24510()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24561()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24560()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24645()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24644()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24439()).runTest("CWE89_SQL_Injection__listen_tcp_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24438()).runTest("CWE89_SQL_Injection__listen_tcp_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24479()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24478()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24353()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24352()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24409()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24408()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24605()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24604()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24351()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24350()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24333()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24332()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24423()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24422()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24373()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24372()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24457()).runTest("CWE89_SQL_Injection__listen_tcp_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24456()).runTest("CWE89_SQL_Injection__listen_tcp_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24455()).runTest("CWE89_SQL_Injection__listen_tcp_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24454()).runTest("CWE89_SQL_Injection__listen_tcp_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24379()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24378()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24389()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24388()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24607()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24606()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24417()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24416()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24313()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24312()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24615()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24614()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24331()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24330()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24539()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24538()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24325()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24324()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24579()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24578()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24533()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24532()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24361()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24360()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24609()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24608()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24639()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24638()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24513()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24512()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24481()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24480()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24531()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24530()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24383()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24382()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24599()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24598()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24469()).runTest("CWE89_SQL_Injection__listen_tcp_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24468()).runTest("CWE89_SQL_Injection__listen_tcp_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24411()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24410()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24551()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24550()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24407()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24406()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24515()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24514()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24297()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24296()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24425()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24424()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24329()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24328()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24459()).runTest("CWE89_SQL_Injection__listen_tcp_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24458()).runTest("CWE89_SQL_Injection__listen_tcp_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24299()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24298()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24549()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24548()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24589()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24588()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24399()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24398()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24445()).runTest("CWE89_SQL_Injection__listen_tcp_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24444()).runTest("CWE89_SQL_Injection__listen_tcp_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24367()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24366()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24471()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24470()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24621()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24620()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24635()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24634()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24447()).runTest("CWE89_SQL_Injection__listen_tcp_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24446()).runTest("CWE89_SQL_Injection__listen_tcp_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24507()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24506()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24397()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24396()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24419()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24418()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24489()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24488()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24553()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24552()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24583()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24582()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24483()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24482()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24401()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24400()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24307()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24306()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24575()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24574()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24375()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24374()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24391()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24390()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24629()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24628()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24429()).runTest("CWE89_SQL_Injection__listen_tcp_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24428()).runTest("CWE89_SQL_Injection__listen_tcp_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24317()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24316()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24303()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24302()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24601()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24600()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24431()).runTest("CWE89_SQL_Injection__listen_tcp_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24430()).runTest("CWE89_SQL_Injection__listen_tcp_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24473()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24472()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24631()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24630()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24613()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24612()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24641()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24640()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24493()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24492()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24385()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24384()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24359()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24358()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24517()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s03.J24516()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24509()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24508()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24343()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24342()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24395()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s03.J24394()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24435()).runTest("CWE89_SQL_Injection__listen_tcp_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24434()).runTest("CWE89_SQL_Injection__listen_tcp_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24537()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24536()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24637()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24636()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24319()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24318()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24365()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24364()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24619()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24618()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24355()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24354()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24415()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24414()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24437()).runTest("CWE89_SQL_Injection__listen_tcp_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24436()).runTest("CWE89_SQL_Injection__listen_tcp_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24491()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s03.J24490()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24345()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24344()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24453()).runTest("CWE89_SQL_Injection__listen_tcp_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24452()).runTest("CWE89_SQL_Injection__listen_tcp_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24335()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s03.J24334()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24387()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24386()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24565()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24564()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24461()).runTest("CWE89_SQL_Injection__listen_tcp_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24460()).runTest("CWE89_SQL_Injection__listen_tcp_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24595()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s03.J24594()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24581()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24580()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24371()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24370()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24625()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24624()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24327()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24326()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24427()).runTest("CWE89_SQL_Injection__listen_tcp_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24426()).runTest("CWE89_SQL_Injection__listen_tcp_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24523()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24522()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24451()).runTest("CWE89_SQL_Injection__listen_tcp_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24450()).runTest("CWE89_SQL_Injection__listen_tcp_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24573()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24572()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24295()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24294()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24301()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s03.J24300()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24603()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24602()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24593()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s03.J24592()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24369()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24368()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24421()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24420()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24567()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s03.J24566()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24449()).runTest("CWE89_SQL_Injection__listen_tcp_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s03.J24448()).runTest("CWE89_SQL_Injection__listen_tcp_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24339()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s03.J24338()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24487()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s03.J24486()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24495()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24494()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24585()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24584()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24569()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24568()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24321()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s03.J24320()).runTest("CWE89_SQL_Injection__listen_tcp_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24577()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s03.J24576()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24393()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s03.J24392()).runTest("CWE89_SQL_Injection__listen_tcp_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24563()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s03.J24562()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24597()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s03.J24596()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24591()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s03.J24590()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24363()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24362()).runTest("CWE89_SQL_Injection__listen_tcp_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24557()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s03.J24556()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_45_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24529()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s03.J24528()).runTest("CWE89_SQL_Injection__PropertiesFile_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24633()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s03.J24632()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24499()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24498()).runTest("CWE89_SQL_Injection__listen_tcp_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24627()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s03.J24626()).runTest("CWE89_SQL_Injection__PropertiesFile_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s03.J24587()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s03.J24586()).runTest("CWE89_SQL_Injection__PropertiesFile_executeQuery_15_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
