package testcases.CWE321_Hard_Coded_Cryptographic_Key;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_01_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_01_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_01_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_01_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_07_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_07_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_07_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_07_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_05_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_05_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_05_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_05_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_13_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_13_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_13_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_13_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_06_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_06_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_06_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_06_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_08_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_08_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_08_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_08_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_09_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_09_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_09_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_09_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_16_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_16_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_16_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_16_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_45_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_45_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_45_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_45_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_31_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_31_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_31_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_31_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_10_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_10_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_10_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_10_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_02_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_02_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_02_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_02_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_42_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_42_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_42_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_42_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_15_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_15_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_15_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_15_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_17_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_17_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_17_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_17_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_41_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_41_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_41_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_41_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_11_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_11_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_11_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_11_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_12_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_12_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_12_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_12_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_04_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_04_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_04_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_04_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_03_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_03_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_03_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_03_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_21_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_21_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_21_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_21_bad");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_14_good()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_14_good");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.CWE321_Hard_Coded_Cryptographic_Key__basic_14_bad()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_14_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
