package testcases.CWE321_Hard_Coded_Cryptographic_Key;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18933()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_01_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18932()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_01_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18945()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_07_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18944()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_07_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18941()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_05_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18940()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_05_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18957()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_13_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18956()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_13_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18943()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_06_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18942()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_06_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18949()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_09_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18948()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_09_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18975()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_45_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18974()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_45_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18969()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_31_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18968()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_31_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18951()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_10_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18950()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_10_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18935()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_02_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18934()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_02_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18973()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_42_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18972()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_42_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18961()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_15_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18960()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_15_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18971()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_41_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18970()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_41_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18955()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_12_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18954()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_12_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18939()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_04_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18938()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_04_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18937()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_03_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18936()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_03_b");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18967()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_21_gd");
        (new testcases.CWE321_Hard_Coded_Cryptographic_Key.J18966()).runTest("CWE321_Hard_Coded_Cryptographic_Key__basic_21_b");
        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
