package testcases.CWE190_Integer_Overflow.s04;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s04.J15925()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15924()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15553()).runTest("CWE190_Integer_Overflow__long_max_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15552()).runTest("CWE190_Integer_Overflow__long_max_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15949()).runTest("CWE190_Integer_Overflow__short_max_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15948()).runTest("CWE190_Integer_Overflow__short_max_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15915()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15914()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15511()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15510()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15419()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15418()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15517()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15516()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15831()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15830()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15635()).runTest("CWE190_Integer_Overflow__long_max_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15634()).runTest("CWE190_Integer_Overflow__long_max_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15357()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15356()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15777()).runTest("CWE190_Integer_Overflow__long_rand_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15776()).runTest("CWE190_Integer_Overflow__long_rand_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15305()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15304()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15497()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15496()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15681()).runTest("CWE190_Integer_Overflow__long_rand_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15680()).runTest("CWE190_Integer_Overflow__long_rand_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15465()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15464()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15335()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15334()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15665()).runTest("CWE190_Integer_Overflow__long_max_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15664()).runTest("CWE190_Integer_Overflow__long_max_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15761()).runTest("CWE190_Integer_Overflow__long_rand_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15760()).runTest("CWE190_Integer_Overflow__long_rand_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15963()).runTest("CWE190_Integer_Overflow__short_max_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15962()).runTest("CWE190_Integer_Overflow__short_max_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15771()).runTest("CWE190_Integer_Overflow__long_rand_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15770()).runTest("CWE190_Integer_Overflow__long_rand_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15945()).runTest("CWE190_Integer_Overflow__short_max_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15944()).runTest("CWE190_Integer_Overflow__short_max_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15401()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15400()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15689()).runTest("CWE190_Integer_Overflow__long_rand_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15688()).runTest("CWE190_Integer_Overflow__long_rand_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15281()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15280()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15693()).runTest("CWE190_Integer_Overflow__long_rand_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15692()).runTest("CWE190_Integer_Overflow__long_rand_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15457()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15456()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15409()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15408()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15579()).runTest("CWE190_Integer_Overflow__long_max_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15578()).runTest("CWE190_Integer_Overflow__long_max_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15675()).runTest("CWE190_Integer_Overflow__long_max_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15674()).runTest("CWE190_Integer_Overflow__long_max_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15413()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15412()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15765()).runTest("CWE190_Integer_Overflow__long_rand_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15764()).runTest("CWE190_Integer_Overflow__long_rand_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15947()).runTest("CWE190_Integer_Overflow__short_max_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15946()).runTest("CWE190_Integer_Overflow__short_max_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15931()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15930()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15573()).runTest("CWE190_Integer_Overflow__long_max_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15572()).runTest("CWE190_Integer_Overflow__long_max_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15545()).runTest("CWE190_Integer_Overflow__long_max_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15544()).runTest("CWE190_Integer_Overflow__long_max_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15709()).runTest("CWE190_Integer_Overflow__long_rand_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15708()).runTest("CWE190_Integer_Overflow__long_rand_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15785()).runTest("CWE190_Integer_Overflow__long_rand_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15784()).runTest("CWE190_Integer_Overflow__long_rand_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15429()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15428()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15439()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15438()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15849()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15848()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15759()).runTest("CWE190_Integer_Overflow__long_rand_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15758()).runTest("CWE190_Integer_Overflow__long_rand_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15411()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15410()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15623()).runTest("CWE190_Integer_Overflow__long_max_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15622()).runTest("CWE190_Integer_Overflow__long_max_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15407()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15406()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15867()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15866()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15707()).runTest("CWE190_Integer_Overflow__long_rand_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15706()).runTest("CWE190_Integer_Overflow__long_rand_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15449()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15448()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15657()).runTest("CWE190_Integer_Overflow__long_max_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15656()).runTest("CWE190_Integer_Overflow__long_max_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15649()).runTest("CWE190_Integer_Overflow__long_max_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15648()).runTest("CWE190_Integer_Overflow__long_max_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15899()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15898()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15873()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15872()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15673()).runTest("CWE190_Integer_Overflow__long_max_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15672()).runTest("CWE190_Integer_Overflow__long_max_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15885()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15884()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15667()).runTest("CWE190_Integer_Overflow__long_max_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15666()).runTest("CWE190_Integer_Overflow__long_max_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15619()).runTest("CWE190_Integer_Overflow__long_max_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15618()).runTest("CWE190_Integer_Overflow__long_max_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15283()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15282()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15543()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15542()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15605()).runTest("CWE190_Integer_Overflow__long_max_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15604()).runTest("CWE190_Integer_Overflow__long_max_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15329()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15328()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15557()).runTest("CWE190_Integer_Overflow__long_max_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15556()).runTest("CWE190_Integer_Overflow__long_max_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15683()).runTest("CWE190_Integer_Overflow__long_rand_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15682()).runTest("CWE190_Integer_Overflow__long_rand_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15897()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15896()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15639()).runTest("CWE190_Integer_Overflow__long_max_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15638()).runTest("CWE190_Integer_Overflow__long_max_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15861()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15860()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15503()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15502()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15881()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15880()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15835()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15834()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15647()).runTest("CWE190_Integer_Overflow__long_max_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15646()).runTest("CWE190_Integer_Overflow__long_max_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15541()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15540()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15617()).runTest("CWE190_Integer_Overflow__long_max_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15616()).runTest("CWE190_Integer_Overflow__long_max_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15961()).runTest("CWE190_Integer_Overflow__short_max_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15960()).runTest("CWE190_Integer_Overflow__short_max_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15595()).runTest("CWE190_Integer_Overflow__long_max_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15594()).runTest("CWE190_Integer_Overflow__long_max_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15857()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15856()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15307()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15306()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15297()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15296()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15891()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15890()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15583()).runTest("CWE190_Integer_Overflow__long_max_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15582()).runTest("CWE190_Integer_Overflow__long_max_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15719()).runTest("CWE190_Integer_Overflow__long_rand_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15718()).runTest("CWE190_Integer_Overflow__long_rand_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15953()).runTest("CWE190_Integer_Overflow__short_max_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15952()).runTest("CWE190_Integer_Overflow__short_max_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15521()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15520()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15531()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15530()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15309()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15308()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15833()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15832()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15395()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15394()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15455()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15454()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15731()).runTest("CWE190_Integer_Overflow__long_rand_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15730()).runTest("CWE190_Integer_Overflow__long_rand_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15417()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15416()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15893()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15892()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15801()).runTest("CWE190_Integer_Overflow__long_rand_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15800()).runTest("CWE190_Integer_Overflow__long_rand_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15909()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15908()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15523()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15522()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15477()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15476()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15525()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15524()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15887()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15886()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15711()).runTest("CWE190_Integer_Overflow__long_rand_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15710()).runTest("CWE190_Integer_Overflow__long_rand_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15561()).runTest("CWE190_Integer_Overflow__long_max_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15560()).runTest("CWE190_Integer_Overflow__long_max_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15451()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15450()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15509()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15508()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15535()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15534()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15361()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15360()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15359()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15358()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15957()).runTest("CWE190_Integer_Overflow__short_max_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15956()).runTest("CWE190_Integer_Overflow__short_max_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15923()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15922()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15423()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15422()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15399()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15398()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15513()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15512()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15651()).runTest("CWE190_Integer_Overflow__long_max_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15650()).runTest("CWE190_Integer_Overflow__long_max_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15663()).runTest("CWE190_Integer_Overflow__long_max_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15662()).runTest("CWE190_Integer_Overflow__long_max_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15539()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15538()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15943()).runTest("CWE190_Integer_Overflow__short_max_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15942()).runTest("CWE190_Integer_Overflow__short_max_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15435()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15434()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15555()).runTest("CWE190_Integer_Overflow__long_max_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15554()).runTest("CWE190_Integer_Overflow__long_max_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15827()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15826()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15971()).runTest("CWE190_Integer_Overflow__short_max_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15970()).runTest("CWE190_Integer_Overflow__short_max_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15769()).runTest("CWE190_Integer_Overflow__long_rand_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15768()).runTest("CWE190_Integer_Overflow__long_rand_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15331()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15330()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15877()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15876()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15415()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15414()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15597()).runTest("CWE190_Integer_Overflow__long_max_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15596()).runTest("CWE190_Integer_Overflow__long_max_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15559()).runTest("CWE190_Integer_Overflow__long_max_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15558()).runTest("CWE190_Integer_Overflow__long_max_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15313()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15312()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15637()).runTest("CWE190_Integer_Overflow__long_max_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15636()).runTest("CWE190_Integer_Overflow__long_max_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15805()).runTest("CWE190_Integer_Overflow__long_rand_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15804()).runTest("CWE190_Integer_Overflow__long_rand_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15549()).runTest("CWE190_Integer_Overflow__long_max_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15548()).runTest("CWE190_Integer_Overflow__long_max_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15791()).runTest("CWE190_Integer_Overflow__long_rand_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15790()).runTest("CWE190_Integer_Overflow__long_rand_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15743()).runTest("CWE190_Integer_Overflow__long_rand_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15742()).runTest("CWE190_Integer_Overflow__long_rand_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15501()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15500()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15491()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15490()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15389()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15388()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15485()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15484()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15879()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15878()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15599()).runTest("CWE190_Integer_Overflow__long_max_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15598()).runTest("CWE190_Integer_Overflow__long_max_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15631()).runTest("CWE190_Integer_Overflow__long_max_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15630()).runTest("CWE190_Integer_Overflow__long_max_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15729()).runTest("CWE190_Integer_Overflow__long_rand_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15728()).runTest("CWE190_Integer_Overflow__long_rand_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15347()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15346()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15303()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15302()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15349()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15348()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15661()).runTest("CWE190_Integer_Overflow__long_max_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15660()).runTest("CWE190_Integer_Overflow__long_max_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15977()).runTest("CWE190_Integer_Overflow__short_max_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15976()).runTest("CWE190_Integer_Overflow__short_max_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15571()).runTest("CWE190_Integer_Overflow__long_max_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15570()).runTest("CWE190_Integer_Overflow__long_max_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15763()).runTest("CWE190_Integer_Overflow__long_rand_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15762()).runTest("CWE190_Integer_Overflow__long_rand_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15851()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15850()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15625()).runTest("CWE190_Integer_Overflow__long_max_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15624()).runTest("CWE190_Integer_Overflow__long_max_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15431()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15430()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15813()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15812()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15721()).runTest("CWE190_Integer_Overflow__long_rand_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15720()).runTest("CWE190_Integer_Overflow__long_rand_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15981()).runTest("CWE190_Integer_Overflow__short_max_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15980()).runTest("CWE190_Integer_Overflow__short_max_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15405()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15404()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15339()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15338()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15519()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15518()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15515()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15514()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15547()).runTest("CWE190_Integer_Overflow__long_max_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15546()).runTest("CWE190_Integer_Overflow__long_max_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15871()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15870()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15653()).runTest("CWE190_Integer_Overflow__long_max_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15652()).runTest("CWE190_Integer_Overflow__long_max_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15875()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15874()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15343()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15342()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15865()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15864()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15315()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15314()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15299()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15298()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15659()).runTest("CWE190_Integer_Overflow__long_max_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15658()).runTest("CWE190_Integer_Overflow__long_max_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15697()).runTest("CWE190_Integer_Overflow__long_rand_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15696()).runTest("CWE190_Integer_Overflow__long_rand_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15593()).runTest("CWE190_Integer_Overflow__long_max_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15592()).runTest("CWE190_Integer_Overflow__long_max_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15319()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15318()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15471()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15470()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15483()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15482()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15799()).runTest("CWE190_Integer_Overflow__long_rand_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15798()).runTest("CWE190_Integer_Overflow__long_rand_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15427()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15426()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15699()).runTest("CWE190_Integer_Overflow__long_rand_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15698()).runTest("CWE190_Integer_Overflow__long_rand_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15687()).runTest("CWE190_Integer_Overflow__long_rand_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15686()).runTest("CWE190_Integer_Overflow__long_rand_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15333()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15332()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15747()).runTest("CWE190_Integer_Overflow__long_rand_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15746()).runTest("CWE190_Integer_Overflow__long_rand_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15755()).runTest("CWE190_Integer_Overflow__long_rand_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15754()).runTest("CWE190_Integer_Overflow__long_rand_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15569()).runTest("CWE190_Integer_Overflow__long_max_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15568()).runTest("CWE190_Integer_Overflow__long_max_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15735()).runTest("CWE190_Integer_Overflow__long_rand_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15734()).runTest("CWE190_Integer_Overflow__long_rand_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15655()).runTest("CWE190_Integer_Overflow__long_max_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15654()).runTest("CWE190_Integer_Overflow__long_max_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15753()).runTest("CWE190_Integer_Overflow__long_rand_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15752()).runTest("CWE190_Integer_Overflow__long_rand_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15529()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15528()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15691()).runTest("CWE190_Integer_Overflow__long_rand_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15690()).runTest("CWE190_Integer_Overflow__long_rand_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15941()).runTest("CWE190_Integer_Overflow__short_max_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15940()).runTest("CWE190_Integer_Overflow__short_max_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15843()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15842()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15817()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15816()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15983()).runTest("CWE190_Integer_Overflow__short_max_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15982()).runTest("CWE190_Integer_Overflow__short_max_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15695()).runTest("CWE190_Integer_Overflow__long_rand_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15694()).runTest("CWE190_Integer_Overflow__long_rand_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15845()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15844()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15927()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15926()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15587()).runTest("CWE190_Integer_Overflow__long_max_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15586()).runTest("CWE190_Integer_Overflow__long_max_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15739()).runTest("CWE190_Integer_Overflow__long_rand_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15738()).runTest("CWE190_Integer_Overflow__long_rand_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15589()).runTest("CWE190_Integer_Overflow__long_max_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15588()).runTest("CWE190_Integer_Overflow__long_max_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15725()).runTest("CWE190_Integer_Overflow__long_rand_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15724()).runTest("CWE190_Integer_Overflow__long_rand_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15627()).runTest("CWE190_Integer_Overflow__long_max_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15626()).runTest("CWE190_Integer_Overflow__long_max_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15327()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15326()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15311()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15310()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15325()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15324()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15469()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15468()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15669()).runTest("CWE190_Integer_Overflow__long_max_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15668()).runTest("CWE190_Integer_Overflow__long_max_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15921()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15920()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15441()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15440()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15883()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15882()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15965()).runTest("CWE190_Integer_Overflow__short_max_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15964()).runTest("CWE190_Integer_Overflow__short_max_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15575()).runTest("CWE190_Integer_Overflow__long_max_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15574()).runTest("CWE190_Integer_Overflow__long_max_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15863()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15862()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15951()).runTest("CWE190_Integer_Overflow__short_max_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15950()).runTest("CWE190_Integer_Overflow__short_max_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15975()).runTest("CWE190_Integer_Overflow__short_max_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15974()).runTest("CWE190_Integer_Overflow__short_max_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15563()).runTest("CWE190_Integer_Overflow__long_max_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15562()).runTest("CWE190_Integer_Overflow__long_max_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15815()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15814()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15869()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15868()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15565()).runTest("CWE190_Integer_Overflow__long_max_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15564()).runTest("CWE190_Integer_Overflow__long_max_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15901()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15900()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15317()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15316()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15749()).runTest("CWE190_Integer_Overflow__long_rand_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15748()).runTest("CWE190_Integer_Overflow__long_rand_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15615()).runTest("CWE190_Integer_Overflow__long_max_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15614()).runTest("CWE190_Integer_Overflow__long_max_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15369()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15368()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15955()).runTest("CWE190_Integer_Overflow__short_max_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15954()).runTest("CWE190_Integer_Overflow__short_max_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15577()).runTest("CWE190_Integer_Overflow__long_max_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15576()).runTest("CWE190_Integer_Overflow__long_max_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15341()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15340()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15403()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15402()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15345()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15344()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15895()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15894()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15907()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15906()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15591()).runTest("CWE190_Integer_Overflow__long_max_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15590()).runTest("CWE190_Integer_Overflow__long_max_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15461()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15460()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15365()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15364()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15919()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15918()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15929()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15928()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15839()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15838()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15611()).runTest("CWE190_Integer_Overflow__long_max_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15610()).runTest("CWE190_Integer_Overflow__long_max_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15323()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15322()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15903()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15902()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15291()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15290()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15979()).runTest("CWE190_Integer_Overflow__short_max_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15978()).runTest("CWE190_Integer_Overflow__short_max_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15567()).runTest("CWE190_Integer_Overflow__long_max_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15566()).runTest("CWE190_Integer_Overflow__long_max_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15385()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15384()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15853()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15852()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15705()).runTest("CWE190_Integer_Overflow__long_rand_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15704()).runTest("CWE190_Integer_Overflow__long_rand_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15375()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15374()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15937()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15936()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15527()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15526()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15889()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15888()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15679()).runTest("CWE190_Integer_Overflow__long_rand_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15678()).runTest("CWE190_Integer_Overflow__long_rand_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15911()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15910()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15585()).runTest("CWE190_Integer_Overflow__long_max_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15584()).runTest("CWE190_Integer_Overflow__long_max_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15819()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15818()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15855()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15854()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15847()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15846()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15337()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15336()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15811()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15810()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15825()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15824()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15475()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15474()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15495()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15494()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15367()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15366()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15959()).runTest("CWE190_Integer_Overflow__short_max_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15958()).runTest("CWE190_Integer_Overflow__short_max_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15371()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15370()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15671()).runTest("CWE190_Integer_Overflow__long_max_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15670()).runTest("CWE190_Integer_Overflow__long_max_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15609()).runTest("CWE190_Integer_Overflow__long_max_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15608()).runTest("CWE190_Integer_Overflow__long_max_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15629()).runTest("CWE190_Integer_Overflow__long_max_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15628()).runTest("CWE190_Integer_Overflow__long_max_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15713()).runTest("CWE190_Integer_Overflow__long_rand_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15712()).runTest("CWE190_Integer_Overflow__long_rand_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15487()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15486()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15701()).runTest("CWE190_Integer_Overflow__long_rand_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15700()).runTest("CWE190_Integer_Overflow__long_rand_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15445()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15444()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15837()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15836()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15775()).runTest("CWE190_Integer_Overflow__long_rand_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15774()).runTest("CWE190_Integer_Overflow__long_rand_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15459()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15458()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15685()).runTest("CWE190_Integer_Overflow__long_rand_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15684()).runTest("CWE190_Integer_Overflow__long_rand_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15717()).runTest("CWE190_Integer_Overflow__long_rand_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15716()).runTest("CWE190_Integer_Overflow__long_rand_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15533()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15532()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15443()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15442()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15789()).runTest("CWE190_Integer_Overflow__long_rand_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15788()).runTest("CWE190_Integer_Overflow__long_rand_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15733()).runTest("CWE190_Integer_Overflow__long_rand_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15732()).runTest("CWE190_Integer_Overflow__long_rand_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15393()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15392()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15727()).runTest("CWE190_Integer_Overflow__long_rand_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15726()).runTest("CWE190_Integer_Overflow__long_rand_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15355()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15354()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15391()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15390()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15643()).runTest("CWE190_Integer_Overflow__long_max_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15642()).runTest("CWE190_Integer_Overflow__long_max_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15933()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15932()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15377()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15376()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15803()).runTest("CWE190_Integer_Overflow__long_rand_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15802()).runTest("CWE190_Integer_Overflow__long_rand_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15757()).runTest("CWE190_Integer_Overflow__long_rand_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15756()).runTest("CWE190_Integer_Overflow__long_rand_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15321()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15320()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15621()).runTest("CWE190_Integer_Overflow__long_max_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15620()).runTest("CWE190_Integer_Overflow__long_max_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15645()).runTest("CWE190_Integer_Overflow__long_max_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15644()).runTest("CWE190_Integer_Overflow__long_max_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15467()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15466()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15463()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15462()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15641()).runTest("CWE190_Integer_Overflow__long_max_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15640()).runTest("CWE190_Integer_Overflow__long_max_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15917()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15916()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15381()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15380()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15823()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15822()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15781()).runTest("CWE190_Integer_Overflow__long_rand_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15780()).runTest("CWE190_Integer_Overflow__long_rand_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15807()).runTest("CWE190_Integer_Overflow__long_rand_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15806()).runTest("CWE190_Integer_Overflow__long_rand_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15795()).runTest("CWE190_Integer_Overflow__long_rand_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15794()).runTest("CWE190_Integer_Overflow__long_rand_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15581()).runTest("CWE190_Integer_Overflow__long_max_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15580()).runTest("CWE190_Integer_Overflow__long_max_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15969()).runTest("CWE190_Integer_Overflow__short_max_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15968()).runTest("CWE190_Integer_Overflow__short_max_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15425()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15424()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15295()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15294()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15787()).runTest("CWE190_Integer_Overflow__long_rand_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15786()).runTest("CWE190_Integer_Overflow__long_rand_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15447()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15446()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15473()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15472()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15715()).runTest("CWE190_Integer_Overflow__long_rand_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15714()).runTest("CWE190_Integer_Overflow__long_rand_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15285()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15284()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15453()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15452()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15481()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15480()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15797()).runTest("CWE190_Integer_Overflow__long_rand_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15796()).runTest("CWE190_Integer_Overflow__long_rand_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15507()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15506()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15751()).runTest("CWE190_Integer_Overflow__long_rand_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15750()).runTest("CWE190_Integer_Overflow__long_rand_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15437()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15436()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15551()).runTest("CWE190_Integer_Overflow__long_max_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15550()).runTest("CWE190_Integer_Overflow__long_max_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15703()).runTest("CWE190_Integer_Overflow__long_rand_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15702()).runTest("CWE190_Integer_Overflow__long_rand_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15363()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15362()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15935()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15934()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15905()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15904()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15723()).runTest("CWE190_Integer_Overflow__long_rand_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15722()).runTest("CWE190_Integer_Overflow__long_rand_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15783()).runTest("CWE190_Integer_Overflow__long_rand_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15782()).runTest("CWE190_Integer_Overflow__long_rand_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15493()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15492()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15677()).runTest("CWE190_Integer_Overflow__long_rand_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15676()).runTest("CWE190_Integer_Overflow__long_rand_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15601()).runTest("CWE190_Integer_Overflow__long_max_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15600()).runTest("CWE190_Integer_Overflow__long_max_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15603()).runTest("CWE190_Integer_Overflow__long_max_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15602()).runTest("CWE190_Integer_Overflow__long_max_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15737()).runTest("CWE190_Integer_Overflow__long_rand_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15736()).runTest("CWE190_Integer_Overflow__long_rand_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15859()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15858()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15289()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15288()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15973()).runTest("CWE190_Integer_Overflow__short_max_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15972()).runTest("CWE190_Integer_Overflow__short_max_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15809()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15808()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15433()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15432()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15351()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15350()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15913()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15912()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15505()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15504()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15293()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15292()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15353()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15352()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15793()).runTest("CWE190_Integer_Overflow__long_rand_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15792()).runTest("CWE190_Integer_Overflow__long_rand_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15421()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15420()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15745()).runTest("CWE190_Integer_Overflow__long_rand_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15744()).runTest("CWE190_Integer_Overflow__long_rand_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15633()).runTest("CWE190_Integer_Overflow__long_max_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15632()).runTest("CWE190_Integer_Overflow__long_max_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15387()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15386()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15383()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15382()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15607()).runTest("CWE190_Integer_Overflow__long_max_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15606()).runTest("CWE190_Integer_Overflow__long_max_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15613()).runTest("CWE190_Integer_Overflow__long_max_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15612()).runTest("CWE190_Integer_Overflow__long_max_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15967()).runTest("CWE190_Integer_Overflow__short_max_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15966()).runTest("CWE190_Integer_Overflow__short_max_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15499()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15498()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15841()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15840()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15379()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15378()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15821()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15820()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15773()).runTest("CWE190_Integer_Overflow__long_rand_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15772()).runTest("CWE190_Integer_Overflow__long_rand_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15373()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15372()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15301()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15300()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15537()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15536()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15767()).runTest("CWE190_Integer_Overflow__long_rand_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15766()).runTest("CWE190_Integer_Overflow__long_rand_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15479()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15478()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15939()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15938()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15779()).runTest("CWE190_Integer_Overflow__long_rand_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15778()).runTest("CWE190_Integer_Overflow__long_rand_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15829()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15828()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15489()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15488()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15397()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15396()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15287()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15286()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s04.J15741()).runTest("CWE190_Integer_Overflow__long_rand_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s04.J15740()).runTest("CWE190_Integer_Overflow__long_rand_multiply_11_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
