package testcases.CWE190_Integer_Overflow.s04;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s04.J1241()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1240()).runTest("CWE190_Integer_Overflow__int_URLConnection_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1249()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1248()).runTest("CWE190_Integer_Overflow__long_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1247()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1246()).runTest("CWE190_Integer_Overflow__long_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1263()).runTest("CWE190_Integer_Overflow__long_rand_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1262()).runTest("CWE190_Integer_Overflow__long_rand_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1253()).runTest("CWE190_Integer_Overflow__long_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1252()).runTest("CWE190_Integer_Overflow__long_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1269()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1268()).runTest("CWE190_Integer_Overflow__short_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1251()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1250()).runTest("CWE190_Integer_Overflow__long_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1261()).runTest("CWE190_Integer_Overflow__long_rand_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1260()).runTest("CWE190_Integer_Overflow__long_rand_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1271()).runTest("CWE190_Integer_Overflow__short_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1270()).runTest("CWE190_Integer_Overflow__short_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1255()).runTest("CWE190_Integer_Overflow__long_max_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1254()).runTest("CWE190_Integer_Overflow__long_max_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1243()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1242()).runTest("CWE190_Integer_Overflow__int_URLConnection_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1245()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1244()).runTest("CWE190_Integer_Overflow__int_URLConnection_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1267()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1266()).runTest("CWE190_Integer_Overflow__short_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1259()).runTest("CWE190_Integer_Overflow__long_rand_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1258()).runTest("CWE190_Integer_Overflow__long_rand_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1265()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1264()).runTest("CWE190_Integer_Overflow__short_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1257()).runTest("CWE190_Integer_Overflow__long_max_square_01");
        (new testcases.CWE190_Integer_Overflow.s04.J1256()).runTest("CWE190_Integer_Overflow__long_max_square_01");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
