package testcases.CWE190_Integer_Overflow.s01;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s01.J13713()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13712()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13575()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13574()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13469()).runTest("CWE190_Integer_Overflow__byte_rand_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13468()).runTest("CWE190_Integer_Overflow__byte_rand_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13703()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13702()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13605()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13604()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13621()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13620()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13375()).runTest("CWE190_Integer_Overflow__byte_max_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13374()).runTest("CWE190_Integer_Overflow__byte_max_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13357()).runTest("CWE190_Integer_Overflow__byte_max_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13356()).runTest("CWE190_Integer_Overflow__byte_max_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13505()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13504()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13355()).runTest("CWE190_Integer_Overflow__byte_max_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13354()).runTest("CWE190_Integer_Overflow__byte_max_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13383()).runTest("CWE190_Integer_Overflow__byte_max_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13382()).runTest("CWE190_Integer_Overflow__byte_max_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13347()).runTest("CWE190_Integer_Overflow__byte_max_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13346()).runTest("CWE190_Integer_Overflow__byte_max_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13329()).runTest("CWE190_Integer_Overflow__byte_max_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13328()).runTest("CWE190_Integer_Overflow__byte_max_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13271()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13270()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13527()).runTest("CWE190_Integer_Overflow__byte_rand_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13526()).runTest("CWE190_Integer_Overflow__byte_rand_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13477()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13476()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13485()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13484()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13205()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13204()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13531()).runTest("CWE190_Integer_Overflow__byte_rand_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13530()).runTest("CWE190_Integer_Overflow__byte_rand_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13237()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13236()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13503()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13502()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13543()).runTest("CWE190_Integer_Overflow__byte_rand_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13542()).runTest("CWE190_Integer_Overflow__byte_rand_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13869()).runTest("CWE190_Integer_Overflow__int_database_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13868()).runTest("CWE190_Integer_Overflow__int_database_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13359()).runTest("CWE190_Integer_Overflow__byte_max_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13358()).runTest("CWE190_Integer_Overflow__byte_max_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13663()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13662()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13427()).runTest("CWE190_Integer_Overflow__byte_max_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13426()).runTest("CWE190_Integer_Overflow__byte_max_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13827()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13826()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13607()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13606()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13615()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13614()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13857()).runTest("CWE190_Integer_Overflow__int_database_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13856()).runTest("CWE190_Integer_Overflow__int_database_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13377()).runTest("CWE190_Integer_Overflow__byte_max_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13376()).runTest("CWE190_Integer_Overflow__byte_max_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13339()).runTest("CWE190_Integer_Overflow__byte_max_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13338()).runTest("CWE190_Integer_Overflow__byte_max_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13561()).runTest("CWE190_Integer_Overflow__byte_rand_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13560()).runTest("CWE190_Integer_Overflow__byte_rand_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13321()).runTest("CWE190_Integer_Overflow__byte_max_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13320()).runTest("CWE190_Integer_Overflow__byte_max_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13539()).runTest("CWE190_Integer_Overflow__byte_rand_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13538()).runTest("CWE190_Integer_Overflow__byte_rand_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13323()).runTest("CWE190_Integer_Overflow__byte_max_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13322()).runTest("CWE190_Integer_Overflow__byte_max_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13585()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13584()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13697()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13696()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13181()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13180()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13757()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13756()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13491()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13490()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13361()).runTest("CWE190_Integer_Overflow__byte_max_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13360()).runTest("CWE190_Integer_Overflow__byte_max_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13659()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13658()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13241()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13240()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13437()).runTest("CWE190_Integer_Overflow__byte_rand_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13436()).runTest("CWE190_Integer_Overflow__byte_rand_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13425()).runTest("CWE190_Integer_Overflow__byte_max_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13424()).runTest("CWE190_Integer_Overflow__byte_max_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13341()).runTest("CWE190_Integer_Overflow__byte_max_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13340()).runTest("CWE190_Integer_Overflow__byte_max_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13255()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13254()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13285()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13284()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13583()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13582()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13733()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13732()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13293()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13292()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13451()).runTest("CWE190_Integer_Overflow__byte_rand_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13450()).runTest("CWE190_Integer_Overflow__byte_rand_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13495()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13494()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13661()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13660()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13845()).runTest("CWE190_Integer_Overflow__int_database_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13844()).runTest("CWE190_Integer_Overflow__int_database_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13817()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13816()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13263()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13262()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13795()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13794()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13767()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13766()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13669()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13668()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13313()).runTest("CWE190_Integer_Overflow__byte_max_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13312()).runTest("CWE190_Integer_Overflow__byte_max_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13211()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13210()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13563()).runTest("CWE190_Integer_Overflow__byte_rand_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13562()).runTest("CWE190_Integer_Overflow__byte_rand_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13599()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13598()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13789()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13788()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13459()).runTest("CWE190_Integer_Overflow__byte_rand_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13458()).runTest("CWE190_Integer_Overflow__byte_rand_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13513()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13512()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13715()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13714()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13867()).runTest("CWE190_Integer_Overflow__int_database_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13866()).runTest("CWE190_Integer_Overflow__int_database_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13443()).runTest("CWE190_Integer_Overflow__byte_rand_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13442()).runTest("CWE190_Integer_Overflow__byte_rand_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13829()).runTest("CWE190_Integer_Overflow__int_database_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13828()).runTest("CWE190_Integer_Overflow__int_database_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13573()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13572()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13501()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13500()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13537()).runTest("CWE190_Integer_Overflow__byte_rand_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13536()).runTest("CWE190_Integer_Overflow__byte_rand_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13755()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13754()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13643()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13642()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13871()).runTest("CWE190_Integer_Overflow__int_database_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13870()).runTest("CWE190_Integer_Overflow__int_database_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13591()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13590()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13521()).runTest("CWE190_Integer_Overflow__byte_rand_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13520()).runTest("CWE190_Integer_Overflow__byte_rand_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13215()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13214()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13671()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13670()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13809()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13808()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13711()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13710()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13657()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13656()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13749()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13748()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13641()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13640()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13349()).runTest("CWE190_Integer_Overflow__byte_max_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13348()).runTest("CWE190_Integer_Overflow__byte_max_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13741()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13740()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13367()).runTest("CWE190_Integer_Overflow__byte_max_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13366()).runTest("CWE190_Integer_Overflow__byte_max_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13191()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13190()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13645()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13644()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13455()).runTest("CWE190_Integer_Overflow__byte_rand_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13454()).runTest("CWE190_Integer_Overflow__byte_rand_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13813()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13812()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13401()).runTest("CWE190_Integer_Overflow__byte_max_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13400()).runTest("CWE190_Integer_Overflow__byte_max_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13559()).runTest("CWE190_Integer_Overflow__byte_rand_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13558()).runTest("CWE190_Integer_Overflow__byte_rand_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13567()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13566()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13701()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13700()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13317()).runTest("CWE190_Integer_Overflow__byte_max_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13316()).runTest("CWE190_Integer_Overflow__byte_max_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13199()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13198()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13863()).runTest("CWE190_Integer_Overflow__int_database_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13862()).runTest("CWE190_Integer_Overflow__int_database_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13373()).runTest("CWE190_Integer_Overflow__byte_max_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13372()).runTest("CWE190_Integer_Overflow__byte_max_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13335()).runTest("CWE190_Integer_Overflow__byte_max_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13334()).runTest("CWE190_Integer_Overflow__byte_max_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13825()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13824()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13839()).runTest("CWE190_Integer_Overflow__int_database_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13838()).runTest("CWE190_Integer_Overflow__int_database_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13759()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13758()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13551()).runTest("CWE190_Integer_Overflow__byte_rand_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13550()).runTest("CWE190_Integer_Overflow__byte_rand_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13523()).runTest("CWE190_Integer_Overflow__byte_rand_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13522()).runTest("CWE190_Integer_Overflow__byte_rand_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13471()).runTest("CWE190_Integer_Overflow__byte_rand_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13470()).runTest("CWE190_Integer_Overflow__byte_rand_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13371()).runTest("CWE190_Integer_Overflow__byte_max_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13370()).runTest("CWE190_Integer_Overflow__byte_max_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13173()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13172()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13169()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13168()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13547()).runTest("CWE190_Integer_Overflow__byte_rand_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13546()).runTest("CWE190_Integer_Overflow__byte_rand_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13677()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13676()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13201()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13200()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13515()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13514()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13247()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13246()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13419()).runTest("CWE190_Integer_Overflow__byte_max_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13418()).runTest("CWE190_Integer_Overflow__byte_max_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13493()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13492()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13365()).runTest("CWE190_Integer_Overflow__byte_max_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13364()).runTest("CWE190_Integer_Overflow__byte_max_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13245()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13244()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13807()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13806()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13637()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13636()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13593()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13592()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13197()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13196()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13777()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13776()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13507()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13506()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13281()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13280()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13233()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13232()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13841()).runTest("CWE190_Integer_Overflow__int_database_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13840()).runTest("CWE190_Integer_Overflow__int_database_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13431()).runTest("CWE190_Integer_Overflow__byte_max_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13430()).runTest("CWE190_Integer_Overflow__byte_max_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13725()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13724()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13295()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13294()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13555()).runTest("CWE190_Integer_Overflow__byte_rand_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13554()).runTest("CWE190_Integer_Overflow__byte_rand_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13613()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13612()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13315()).runTest("CWE190_Integer_Overflow__byte_max_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13314()).runTest("CWE190_Integer_Overflow__byte_max_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13647()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13646()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13533()).runTest("CWE190_Integer_Overflow__byte_rand_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13532()).runTest("CWE190_Integer_Overflow__byte_rand_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13695()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13694()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13175()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13174()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13815()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13814()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13635()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13634()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13849()).runTest("CWE190_Integer_Overflow__int_database_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13848()).runTest("CWE190_Integer_Overflow__int_database_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13453()).runTest("CWE190_Integer_Overflow__byte_rand_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13452()).runTest("CWE190_Integer_Overflow__byte_rand_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13457()).runTest("CWE190_Integer_Overflow__byte_rand_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13456()).runTest("CWE190_Integer_Overflow__byte_rand_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13609()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13608()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13627()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13626()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13309()).runTest("CWE190_Integer_Overflow__byte_max_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13308()).runTest("CWE190_Integer_Overflow__byte_max_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13207()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13206()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13765()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13764()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13473()).runTest("CWE190_Integer_Overflow__byte_rand_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13472()).runTest("CWE190_Integer_Overflow__byte_rand_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13623()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13622()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13691()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13690()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13823()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13822()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13833()).runTest("CWE190_Integer_Overflow__int_database_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13832()).runTest("CWE190_Integer_Overflow__int_database_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13415()).runTest("CWE190_Integer_Overflow__byte_max_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13414()).runTest("CWE190_Integer_Overflow__byte_max_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13287()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13286()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13821()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13820()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13545()).runTest("CWE190_Integer_Overflow__byte_rand_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13544()).runTest("CWE190_Integer_Overflow__byte_rand_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13395()).runTest("CWE190_Integer_Overflow__byte_max_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13394()).runTest("CWE190_Integer_Overflow__byte_max_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13399()).runTest("CWE190_Integer_Overflow__byte_max_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13398()).runTest("CWE190_Integer_Overflow__byte_max_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13433()).runTest("CWE190_Integer_Overflow__byte_rand_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13432()).runTest("CWE190_Integer_Overflow__byte_rand_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13557()).runTest("CWE190_Integer_Overflow__byte_rand_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13556()).runTest("CWE190_Integer_Overflow__byte_rand_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13171()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13170()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13791()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13790()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13797()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13796()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13407()).runTest("CWE190_Integer_Overflow__byte_max_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13406()).runTest("CWE190_Integer_Overflow__byte_max_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13279()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13278()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13799()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13798()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13217()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13216()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13751()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13750()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13265()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13264()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13739()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13738()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13213()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13212()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13565()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13564()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13251()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13250()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13311()).runTest("CWE190_Integer_Overflow__byte_max_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13310()).runTest("CWE190_Integer_Overflow__byte_max_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13831()).runTest("CWE190_Integer_Overflow__int_database_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13830()).runTest("CWE190_Integer_Overflow__int_database_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13183()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13182()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13769()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13768()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13859()).runTest("CWE190_Integer_Overflow__int_database_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13858()).runTest("CWE190_Integer_Overflow__int_database_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13187()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13186()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13179()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13178()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13675()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13674()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13343()).runTest("CWE190_Integer_Overflow__byte_max_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13342()).runTest("CWE190_Integer_Overflow__byte_max_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13325()).runTest("CWE190_Integer_Overflow__byte_max_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13324()).runTest("CWE190_Integer_Overflow__byte_max_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13385()).runTest("CWE190_Integer_Overflow__byte_max_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13384()).runTest("CWE190_Integer_Overflow__byte_max_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13391()).runTest("CWE190_Integer_Overflow__byte_max_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13390()).runTest("CWE190_Integer_Overflow__byte_max_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13861()).runTest("CWE190_Integer_Overflow__int_database_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13860()).runTest("CWE190_Integer_Overflow__int_database_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13687()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13686()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13283()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13282()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13681()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13680()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13587()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13586()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13603()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13602()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13843()).runTest("CWE190_Integer_Overflow__int_database_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13842()).runTest("CWE190_Integer_Overflow__int_database_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13787()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13786()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13243()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13242()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13277()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13276()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13653()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13652()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13633()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13632()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13273()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13272()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13307()).runTest("CWE190_Integer_Overflow__byte_max_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13306()).runTest("CWE190_Integer_Overflow__byte_max_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13853()).runTest("CWE190_Integer_Overflow__int_database_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13852()).runTest("CWE190_Integer_Overflow__int_database_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13693()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13692()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13229()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13228()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13345()).runTest("CWE190_Integer_Overflow__byte_max_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13344()).runTest("CWE190_Integer_Overflow__byte_max_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13665()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13664()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13625()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13624()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13209()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13208()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13447()).runTest("CWE190_Integer_Overflow__byte_rand_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13446()).runTest("CWE190_Integer_Overflow__byte_rand_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13259()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13258()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13487()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13486()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13579()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13578()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13363()).runTest("CWE190_Integer_Overflow__byte_max_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13362()).runTest("CWE190_Integer_Overflow__byte_max_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13489()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13488()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13649()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13648()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13835()).runTest("CWE190_Integer_Overflow__int_database_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13834()).runTest("CWE190_Integer_Overflow__int_database_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13631()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13630()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13435()).runTest("CWE190_Integer_Overflow__byte_rand_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13434()).runTest("CWE190_Integer_Overflow__byte_rand_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13803()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13802()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13541()).runTest("CWE190_Integer_Overflow__byte_rand_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13540()).runTest("CWE190_Integer_Overflow__byte_rand_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13319()).runTest("CWE190_Integer_Overflow__byte_max_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13318()).runTest("CWE190_Integer_Overflow__byte_max_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13709()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13708()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13865()).runTest("CWE190_Integer_Overflow__int_database_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13864()).runTest("CWE190_Integer_Overflow__int_database_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13413()).runTest("CWE190_Integer_Overflow__byte_max_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13412()).runTest("CWE190_Integer_Overflow__byte_max_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13289()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13288()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13379()).runTest("CWE190_Integer_Overflow__byte_max_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13378()).runTest("CWE190_Integer_Overflow__byte_max_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13611()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13610()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13785()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13784()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13719()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13718()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13225()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13224()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13743()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13742()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13381()).runTest("CWE190_Integer_Overflow__byte_max_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13380()).runTest("CWE190_Integer_Overflow__byte_max_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13303()).runTest("CWE190_Integer_Overflow__byte_max_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13302()).runTest("CWE190_Integer_Overflow__byte_max_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13449()).runTest("CWE190_Integer_Overflow__byte_rand_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13448()).runTest("CWE190_Integer_Overflow__byte_rand_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13351()).runTest("CWE190_Integer_Overflow__byte_max_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13350()).runTest("CWE190_Integer_Overflow__byte_max_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13837()).runTest("CWE190_Integer_Overflow__int_database_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13836()).runTest("CWE190_Integer_Overflow__int_database_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13651()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13650()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13185()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13184()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13519()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13518()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13195()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13194()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13773()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13772()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13763()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13762()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13737()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13736()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13177()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13176()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13387()).runTest("CWE190_Integer_Overflow__byte_max_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13386()).runTest("CWE190_Integer_Overflow__byte_max_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13707()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13706()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13511()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13510()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13577()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13576()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13775()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13774()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13589()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13588()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13683()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13682()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13299()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13298()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13705()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13704()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13291()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13290()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13731()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13730()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13569()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13568()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13855()).runTest("CWE190_Integer_Overflow__int_database_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13854()).runTest("CWE190_Integer_Overflow__int_database_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13517()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13516()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13465()).runTest("CWE190_Integer_Overflow__byte_rand_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13464()).runTest("CWE190_Integer_Overflow__byte_rand_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13553()).runTest("CWE190_Integer_Overflow__byte_rand_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13552()).runTest("CWE190_Integer_Overflow__byte_rand_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13753()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13752()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13727()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13726()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13483()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13482()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13689()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13688()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13239()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13238()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13261()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13260()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13333()).runTest("CWE190_Integer_Overflow__byte_max_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13332()).runTest("CWE190_Integer_Overflow__byte_max_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13781()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13780()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13801()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13800()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13403()).runTest("CWE190_Integer_Overflow__byte_max_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13402()).runTest("CWE190_Integer_Overflow__byte_max_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13227()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13226()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13461()).runTest("CWE190_Integer_Overflow__byte_rand_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13460()).runTest("CWE190_Integer_Overflow__byte_rand_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13467()).runTest("CWE190_Integer_Overflow__byte_rand_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13466()).runTest("CWE190_Integer_Overflow__byte_rand_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13301()).runTest("CWE190_Integer_Overflow__byte_max_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13300()).runTest("CWE190_Integer_Overflow__byte_max_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13673()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13672()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13811()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13810()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13193()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13192()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13601()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13600()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13441()).runTest("CWE190_Integer_Overflow__byte_rand_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13440()).runTest("CWE190_Integer_Overflow__byte_rand_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13535()).runTest("CWE190_Integer_Overflow__byte_rand_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13534()).runTest("CWE190_Integer_Overflow__byte_rand_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13571()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13570()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13729()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13728()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13331()).runTest("CWE190_Integer_Overflow__byte_max_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13330()).runTest("CWE190_Integer_Overflow__byte_max_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13639()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13638()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13223()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13222()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13417()).runTest("CWE190_Integer_Overflow__byte_max_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13416()).runTest("CWE190_Integer_Overflow__byte_max_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13597()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13596()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13771()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13770()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13429()).runTest("CWE190_Integer_Overflow__byte_max_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13428()).runTest("CWE190_Integer_Overflow__byte_max_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13617()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13616()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13479()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13478()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13735()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13734()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13529()).runTest("CWE190_Integer_Overflow__byte_rand_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13528()).runTest("CWE190_Integer_Overflow__byte_rand_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13847()).runTest("CWE190_Integer_Overflow__int_database_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13846()).runTest("CWE190_Integer_Overflow__int_database_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13423()).runTest("CWE190_Integer_Overflow__byte_max_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13422()).runTest("CWE190_Integer_Overflow__byte_max_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13337()).runTest("CWE190_Integer_Overflow__byte_max_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13336()).runTest("CWE190_Integer_Overflow__byte_max_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13581()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13580()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13411()).runTest("CWE190_Integer_Overflow__byte_max_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13410()).runTest("CWE190_Integer_Overflow__byte_max_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13475()).runTest("CWE190_Integer_Overflow__byte_rand_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13474()).runTest("CWE190_Integer_Overflow__byte_rand_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13761()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13760()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13235()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13234()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13397()).runTest("CWE190_Integer_Overflow__byte_max_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13396()).runTest("CWE190_Integer_Overflow__byte_max_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13499()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13498()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13619()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13618()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13497()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13496()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13445()).runTest("CWE190_Integer_Overflow__byte_rand_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13444()).runTest("CWE190_Integer_Overflow__byte_rand_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13685()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13684()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13463()).runTest("CWE190_Integer_Overflow__byte_rand_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13462()).runTest("CWE190_Integer_Overflow__byte_rand_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13679()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13678()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13783()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13782()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13509()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13508()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13525()).runTest("CWE190_Integer_Overflow__byte_rand_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13524()).runTest("CWE190_Integer_Overflow__byte_rand_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13805()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13804()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13219()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13218()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13481()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13480()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13721()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13720()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13253()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13252()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13393()).runTest("CWE190_Integer_Overflow__byte_max_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13392()).runTest("CWE190_Integer_Overflow__byte_max_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13389()).runTest("CWE190_Integer_Overflow__byte_max_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13388()).runTest("CWE190_Integer_Overflow__byte_max_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13257()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13256()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13723()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13722()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13275()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13274()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13655()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13654()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13203()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13202()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13699()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13698()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13779()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13778()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13221()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13220()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13305()).runTest("CWE190_Integer_Overflow__byte_max_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13304()).runTest("CWE190_Integer_Overflow__byte_max_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13327()).runTest("CWE190_Integer_Overflow__byte_max_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13326()).runTest("CWE190_Integer_Overflow__byte_max_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13439()).runTest("CWE190_Integer_Overflow__byte_rand_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13438()).runTest("CWE190_Integer_Overflow__byte_rand_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13297()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13296()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13549()).runTest("CWE190_Integer_Overflow__byte_rand_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13548()).runTest("CWE190_Integer_Overflow__byte_rand_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13231()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13230()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13793()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13792()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13851()).runTest("CWE190_Integer_Overflow__int_database_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13850()).runTest("CWE190_Integer_Overflow__int_database_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13353()).runTest("CWE190_Integer_Overflow__byte_max_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13352()).runTest("CWE190_Integer_Overflow__byte_max_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13819()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13818()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13745()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13744()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13595()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13594()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13405()).runTest("CWE190_Integer_Overflow__byte_max_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13404()).runTest("CWE190_Integer_Overflow__byte_max_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13747()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13746()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13667()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13666()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13421()).runTest("CWE190_Integer_Overflow__byte_max_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13420()).runTest("CWE190_Integer_Overflow__byte_max_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13189()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13188()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13629()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13628()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13249()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13248()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13269()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13268()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13717()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13716()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13267()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13266()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13409()).runTest("CWE190_Integer_Overflow__byte_max_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13408()).runTest("CWE190_Integer_Overflow__byte_max_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s01.J13369()).runTest("CWE190_Integer_Overflow__byte_max_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s01.J13368()).runTest("CWE190_Integer_Overflow__byte_max_multiply_13_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
