package testcases.CWE190_Integer_Overflow.s01;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s01.J1159()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1158()).runTest("CWE190_Integer_Overflow__byte_rand_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1169()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1168()).runTest("CWE190_Integer_Overflow__int_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1175()).runTest("CWE190_Integer_Overflow__int_database_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1174()).runTest("CWE190_Integer_Overflow__int_database_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1161()).runTest("CWE190_Integer_Overflow__byte_rand_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1160()).runTest("CWE190_Integer_Overflow__byte_rand_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1171()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1170()).runTest("CWE190_Integer_Overflow__int_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1145()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1144()).runTest("CWE190_Integer_Overflow__byte_console_readLine_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1165()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1164()).runTest("CWE190_Integer_Overflow__int_connect_tcp_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1157()).runTest("CWE190_Integer_Overflow__byte_rand_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1156()).runTest("CWE190_Integer_Overflow__byte_rand_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1147()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1146()).runTest("CWE190_Integer_Overflow__byte_console_readLine_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1163()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1162()).runTest("CWE190_Integer_Overflow__int_connect_tcp_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1167()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1166()).runTest("CWE190_Integer_Overflow__int_connect_tcp_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1153()).runTest("CWE190_Integer_Overflow__byte_max_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1152()).runTest("CWE190_Integer_Overflow__byte_max_multiply_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1173()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1172()).runTest("CWE190_Integer_Overflow__int_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1151()).runTest("CWE190_Integer_Overflow__byte_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1150()).runTest("CWE190_Integer_Overflow__byte_max_add_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1155()).runTest("CWE190_Integer_Overflow__byte_max_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1154()).runTest("CWE190_Integer_Overflow__byte_max_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1149()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_01");
        (new testcases.CWE190_Integer_Overflow.s01.J1148()).runTest("CWE190_Integer_Overflow__byte_console_readLine_square_01");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
