package testcases.CWE129_Improper_Validation_of_Array_Index.s05;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12989()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12988()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12893()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12892()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13029()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13028()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13035()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13034()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12917()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12916()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13025()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13024()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12963()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12962()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12873()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12872()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12923()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12922()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12999()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12998()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13115()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13114()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13089()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13088()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12991()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12990()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13017()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13016()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13093()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13092()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12903()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12902()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13113()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13112()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13063()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13062()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13127()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13126()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12863()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12862()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12987()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12986()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12943()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12942()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13057()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13056()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12877()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12876()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12831()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12830()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12931()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12930()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12887()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12886()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13049()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13048()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12855()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12854()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12927()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12926()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12867()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12866()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12901()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12900()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13151()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13150()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12897()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12896()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13077()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13076()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12967()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12966()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12977()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12976()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13045()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13044()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12945()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12944()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13123()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13122()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13165()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13164()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12937()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12936()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12905()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12904()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12857()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12856()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13135()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13134()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12849()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12848()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13085()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13084()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12907()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12906()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13161()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13160()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12925()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12924()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12981()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12980()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12993()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12992()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12935()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12934()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12975()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12974()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12995()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12994()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13119()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13118()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13095()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13094()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12985()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12984()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13023()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13022()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13003()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13002()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13155()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13154()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13033()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13032()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12969()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12968()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12883()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12882()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13159()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13158()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13153()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13152()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12933()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12932()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12919()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12918()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12941()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12940()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13107()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13106()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13131()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13130()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13021()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13020()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13019()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13018()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12839()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12838()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12865()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12864()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12889()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12888()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13047()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13046()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13013()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13012()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12819()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12818()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12871()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12870()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13125()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13124()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13097()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13096()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13079()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13078()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13073()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13072()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12825()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12824()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12971()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12970()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13101()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13100()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13005()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13004()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12861()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12860()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12909()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12908()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13091()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13090()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12951()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12950()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13081()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13080()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12955()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12954()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13117()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13116()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12847()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12846()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12983()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12982()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13037()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13036()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12841()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12840()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12879()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12878()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13105()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13104()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12973()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12972()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12957()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12956()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12829()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12828()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13099()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13098()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12939()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12938()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12949()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12948()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12915()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12914()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13043()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13042()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12979()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12978()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13087()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13086()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12947()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12946()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12833()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12832()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12997()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12996()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12959()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12958()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12911()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12910()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13129()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13128()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13083()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13082()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13015()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13014()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13011()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13010()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12859()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12858()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12869()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12868()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12851()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12850()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13001()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13000()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12895()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12894()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13163()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13162()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13055()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13054()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13103()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13102()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12965()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12964()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12837()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12836()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13139()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13138()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13121()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_42_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13120()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_42_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13053()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13052()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13149()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13148()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13143()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13142()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13075()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13074()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13031()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13030()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13157()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13156()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12921()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12920()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13067()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13066()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12913()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12912()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13137()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13136()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13141()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13140()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13111()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13110()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12961()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_07_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12960()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_07_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12953()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12952()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_max_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13065()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13064()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13039()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_02_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13038()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_02_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13145()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13144()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12823()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_04_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12822()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_04_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12835()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_10_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12834()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_10_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13147()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13146()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12817()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_01_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12816()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_01_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12843()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_14_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12842()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_14_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13167()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_45_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13166()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_45_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12929()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12928()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_write_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13069()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_17_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13068()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_17_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13041()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13040()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13051()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13050()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13059()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_12_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13058()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_12_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12885()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12884()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13109()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13108()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_size_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12821()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_03_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12820()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_03_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13027()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13026()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13133()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_05_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13132()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_write_no_check_05_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12845()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_15_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12844()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_15_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12891()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_16_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12890()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_16_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12853()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_31_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12852()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_31_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13071()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_21_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13070()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_21_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12827()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_06_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12826()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_no_check_06_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12881()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_11_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12880()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_11_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13061()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_13_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13060()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_no_check_13_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13009()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_09_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13008()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_09_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13007()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J13006()).runTest("CWE129_Improper_Validation_of_Array_Index__URLConnection_array_read_check_min_08_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12899()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_41_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12898()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_41_b");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12875()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_08_gd");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s05.J12874()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_size_08_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
