package testcases.CWE190_Integer_Overflow.s02;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s02.J14203()).runTest("CWE190_Integer_Overflow__int_File_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14202()).runTest("CWE190_Integer_Overflow__int_File_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14077()).runTest("CWE190_Integer_Overflow__int_Environment_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14076()).runTest("CWE190_Integer_Overflow__int_Environment_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13979()).runTest("CWE190_Integer_Overflow__int_Environment_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13978()).runTest("CWE190_Integer_Overflow__int_Environment_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14081()).runTest("CWE190_Integer_Overflow__int_Environment_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14080()).runTest("CWE190_Integer_Overflow__int_Environment_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14117()).runTest("CWE190_Integer_Overflow__int_File_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14116()).runTest("CWE190_Integer_Overflow__int_File_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14173()).runTest("CWE190_Integer_Overflow__int_File_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14172()).runTest("CWE190_Integer_Overflow__int_File_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14195()).runTest("CWE190_Integer_Overflow__int_File_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14194()).runTest("CWE190_Integer_Overflow__int_File_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13937()).runTest("CWE190_Integer_Overflow__int_database_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13936()).runTest("CWE190_Integer_Overflow__int_database_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14155()).runTest("CWE190_Integer_Overflow__int_File_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14154()).runTest("CWE190_Integer_Overflow__int_File_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13879()).runTest("CWE190_Integer_Overflow__int_database_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13878()).runTest("CWE190_Integer_Overflow__int_database_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14141()).runTest("CWE190_Integer_Overflow__int_File_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14140()).runTest("CWE190_Integer_Overflow__int_File_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14169()).runTest("CWE190_Integer_Overflow__int_File_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14168()).runTest("CWE190_Integer_Overflow__int_File_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14215()).runTest("CWE190_Integer_Overflow__int_File_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14214()).runTest("CWE190_Integer_Overflow__int_File_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14149()).runTest("CWE190_Integer_Overflow__int_File_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14148()).runTest("CWE190_Integer_Overflow__int_File_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13887()).runTest("CWE190_Integer_Overflow__int_database_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13886()).runTest("CWE190_Integer_Overflow__int_database_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14209()).runTest("CWE190_Integer_Overflow__int_File_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14208()).runTest("CWE190_Integer_Overflow__int_File_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13913()).runTest("CWE190_Integer_Overflow__int_database_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13912()).runTest("CWE190_Integer_Overflow__int_database_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14047()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14046()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13981()).runTest("CWE190_Integer_Overflow__int_Environment_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13980()).runTest("CWE190_Integer_Overflow__int_Environment_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13971()).runTest("CWE190_Integer_Overflow__int_Environment_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13970()).runTest("CWE190_Integer_Overflow__int_Environment_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13959()).runTest("CWE190_Integer_Overflow__int_database_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13958()).runTest("CWE190_Integer_Overflow__int_database_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14143()).runTest("CWE190_Integer_Overflow__int_File_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14142()).runTest("CWE190_Integer_Overflow__int_File_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13925()).runTest("CWE190_Integer_Overflow__int_database_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13924()).runTest("CWE190_Integer_Overflow__int_database_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13997()).runTest("CWE190_Integer_Overflow__int_Environment_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13996()).runTest("CWE190_Integer_Overflow__int_Environment_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14069()).runTest("CWE190_Integer_Overflow__int_Environment_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14068()).runTest("CWE190_Integer_Overflow__int_Environment_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14159()).runTest("CWE190_Integer_Overflow__int_File_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14158()).runTest("CWE190_Integer_Overflow__int_File_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14097()).runTest("CWE190_Integer_Overflow__int_File_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14096()).runTest("CWE190_Integer_Overflow__int_File_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14007()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14006()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14171()).runTest("CWE190_Integer_Overflow__int_File_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14170()).runTest("CWE190_Integer_Overflow__int_File_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14161()).runTest("CWE190_Integer_Overflow__int_File_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14160()).runTest("CWE190_Integer_Overflow__int_File_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13985()).runTest("CWE190_Integer_Overflow__int_Environment_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13984()).runTest("CWE190_Integer_Overflow__int_Environment_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14121()).runTest("CWE190_Integer_Overflow__int_File_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14120()).runTest("CWE190_Integer_Overflow__int_File_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14093()).runTest("CWE190_Integer_Overflow__int_File_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14092()).runTest("CWE190_Integer_Overflow__int_File_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14065()).runTest("CWE190_Integer_Overflow__int_Environment_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14064()).runTest("CWE190_Integer_Overflow__int_Environment_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14091()).runTest("CWE190_Integer_Overflow__int_Environment_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14090()).runTest("CWE190_Integer_Overflow__int_Environment_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13961()).runTest("CWE190_Integer_Overflow__int_Environment_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13960()).runTest("CWE190_Integer_Overflow__int_Environment_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14135()).runTest("CWE190_Integer_Overflow__int_File_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14134()).runTest("CWE190_Integer_Overflow__int_File_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13895()).runTest("CWE190_Integer_Overflow__int_database_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13894()).runTest("CWE190_Integer_Overflow__int_database_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14061()).runTest("CWE190_Integer_Overflow__int_Environment_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14060()).runTest("CWE190_Integer_Overflow__int_Environment_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13993()).runTest("CWE190_Integer_Overflow__int_Environment_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13992()).runTest("CWE190_Integer_Overflow__int_Environment_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13915()).runTest("CWE190_Integer_Overflow__int_database_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13914()).runTest("CWE190_Integer_Overflow__int_database_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14189()).runTest("CWE190_Integer_Overflow__int_File_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14188()).runTest("CWE190_Integer_Overflow__int_File_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14211()).runTest("CWE190_Integer_Overflow__int_File_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14210()).runTest("CWE190_Integer_Overflow__int_File_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13883()).runTest("CWE190_Integer_Overflow__int_database_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13882()).runTest("CWE190_Integer_Overflow__int_database_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14123()).runTest("CWE190_Integer_Overflow__int_File_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14122()).runTest("CWE190_Integer_Overflow__int_File_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14221()).runTest("CWE190_Integer_Overflow__int_File_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14220()).runTest("CWE190_Integer_Overflow__int_File_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14009()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14008()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14085()).runTest("CWE190_Integer_Overflow__int_Environment_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14084()).runTest("CWE190_Integer_Overflow__int_Environment_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13983()).runTest("CWE190_Integer_Overflow__int_Environment_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13982()).runTest("CWE190_Integer_Overflow__int_Environment_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13975()).runTest("CWE190_Integer_Overflow__int_Environment_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13974()).runTest("CWE190_Integer_Overflow__int_Environment_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13917()).runTest("CWE190_Integer_Overflow__int_database_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13916()).runTest("CWE190_Integer_Overflow__int_database_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14193()).runTest("CWE190_Integer_Overflow__int_File_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14192()).runTest("CWE190_Integer_Overflow__int_File_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14023()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14022()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13891()).runTest("CWE190_Integer_Overflow__int_database_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13890()).runTest("CWE190_Integer_Overflow__int_database_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13923()).runTest("CWE190_Integer_Overflow__int_database_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13922()).runTest("CWE190_Integer_Overflow__int_database_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13905()).runTest("CWE190_Integer_Overflow__int_database_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13904()).runTest("CWE190_Integer_Overflow__int_database_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14001()).runTest("CWE190_Integer_Overflow__int_Environment_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14000()).runTest("CWE190_Integer_Overflow__int_Environment_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13893()).runTest("CWE190_Integer_Overflow__int_database_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13892()).runTest("CWE190_Integer_Overflow__int_database_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13875()).runTest("CWE190_Integer_Overflow__int_database_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13874()).runTest("CWE190_Integer_Overflow__int_database_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14005()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14004()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13995()).runTest("CWE190_Integer_Overflow__int_Environment_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13994()).runTest("CWE190_Integer_Overflow__int_Environment_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13939()).runTest("CWE190_Integer_Overflow__int_database_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13938()).runTest("CWE190_Integer_Overflow__int_database_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13947()).runTest("CWE190_Integer_Overflow__int_database_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13946()).runTest("CWE190_Integer_Overflow__int_database_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14013()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14012()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14147()).runTest("CWE190_Integer_Overflow__int_File_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14146()).runTest("CWE190_Integer_Overflow__int_File_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14205()).runTest("CWE190_Integer_Overflow__int_File_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14204()).runTest("CWE190_Integer_Overflow__int_File_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13957()).runTest("CWE190_Integer_Overflow__int_database_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13956()).runTest("CWE190_Integer_Overflow__int_database_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14099()).runTest("CWE190_Integer_Overflow__int_File_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14098()).runTest("CWE190_Integer_Overflow__int_File_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14033()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14032()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14101()).runTest("CWE190_Integer_Overflow__int_File_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14100()).runTest("CWE190_Integer_Overflow__int_File_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14089()).runTest("CWE190_Integer_Overflow__int_Environment_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14088()).runTest("CWE190_Integer_Overflow__int_Environment_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14063()).runTest("CWE190_Integer_Overflow__int_Environment_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14062()).runTest("CWE190_Integer_Overflow__int_Environment_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14153()).runTest("CWE190_Integer_Overflow__int_File_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14152()).runTest("CWE190_Integer_Overflow__int_File_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14129()).runTest("CWE190_Integer_Overflow__int_File_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14128()).runTest("CWE190_Integer_Overflow__int_File_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14035()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14034()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13941()).runTest("CWE190_Integer_Overflow__int_database_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13940()).runTest("CWE190_Integer_Overflow__int_database_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14059()).runTest("CWE190_Integer_Overflow__int_Environment_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14058()).runTest("CWE190_Integer_Overflow__int_Environment_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14021()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14020()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14051()).runTest("CWE190_Integer_Overflow__int_Environment_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14050()).runTest("CWE190_Integer_Overflow__int_Environment_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14179()).runTest("CWE190_Integer_Overflow__int_File_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14178()).runTest("CWE190_Integer_Overflow__int_File_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14095()).runTest("CWE190_Integer_Overflow__int_File_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14094()).runTest("CWE190_Integer_Overflow__int_File_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14011()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14010()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14025()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14024()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14185()).runTest("CWE190_Integer_Overflow__int_File_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14184()).runTest("CWE190_Integer_Overflow__int_File_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14107()).runTest("CWE190_Integer_Overflow__int_File_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14106()).runTest("CWE190_Integer_Overflow__int_File_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13885()).runTest("CWE190_Integer_Overflow__int_database_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13884()).runTest("CWE190_Integer_Overflow__int_database_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14043()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14042()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14115()).runTest("CWE190_Integer_Overflow__int_File_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14114()).runTest("CWE190_Integer_Overflow__int_File_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13897()).runTest("CWE190_Integer_Overflow__int_database_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13896()).runTest("CWE190_Integer_Overflow__int_database_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13919()).runTest("CWE190_Integer_Overflow__int_database_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13918()).runTest("CWE190_Integer_Overflow__int_database_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13949()).runTest("CWE190_Integer_Overflow__int_database_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13948()).runTest("CWE190_Integer_Overflow__int_database_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13911()).runTest("CWE190_Integer_Overflow__int_database_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13910()).runTest("CWE190_Integer_Overflow__int_database_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13963()).runTest("CWE190_Integer_Overflow__int_Environment_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13962()).runTest("CWE190_Integer_Overflow__int_Environment_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14015()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14014()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14109()).runTest("CWE190_Integer_Overflow__int_File_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14108()).runTest("CWE190_Integer_Overflow__int_File_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13927()).runTest("CWE190_Integer_Overflow__int_database_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13926()).runTest("CWE190_Integer_Overflow__int_database_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14071()).runTest("CWE190_Integer_Overflow__int_Environment_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14070()).runTest("CWE190_Integer_Overflow__int_Environment_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14111()).runTest("CWE190_Integer_Overflow__int_File_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14110()).runTest("CWE190_Integer_Overflow__int_File_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14151()).runTest("CWE190_Integer_Overflow__int_File_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14150()).runTest("CWE190_Integer_Overflow__int_File_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13977()).runTest("CWE190_Integer_Overflow__int_Environment_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13976()).runTest("CWE190_Integer_Overflow__int_Environment_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13945()).runTest("CWE190_Integer_Overflow__int_database_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13944()).runTest("CWE190_Integer_Overflow__int_database_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13901()).runTest("CWE190_Integer_Overflow__int_database_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13900()).runTest("CWE190_Integer_Overflow__int_database_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13877()).runTest("CWE190_Integer_Overflow__int_database_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13876()).runTest("CWE190_Integer_Overflow__int_database_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13931()).runTest("CWE190_Integer_Overflow__int_database_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13930()).runTest("CWE190_Integer_Overflow__int_database_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14197()).runTest("CWE190_Integer_Overflow__int_File_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14196()).runTest("CWE190_Integer_Overflow__int_File_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13973()).runTest("CWE190_Integer_Overflow__int_Environment_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13972()).runTest("CWE190_Integer_Overflow__int_Environment_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14127()).runTest("CWE190_Integer_Overflow__int_File_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14126()).runTest("CWE190_Integer_Overflow__int_File_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14125()).runTest("CWE190_Integer_Overflow__int_File_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14124()).runTest("CWE190_Integer_Overflow__int_File_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14049()).runTest("CWE190_Integer_Overflow__int_Environment_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14048()).runTest("CWE190_Integer_Overflow__int_Environment_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13881()).runTest("CWE190_Integer_Overflow__int_database_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13880()).runTest("CWE190_Integer_Overflow__int_database_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14003()).runTest("CWE190_Integer_Overflow__int_Environment_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14002()).runTest("CWE190_Integer_Overflow__int_Environment_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14201()).runTest("CWE190_Integer_Overflow__int_File_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14200()).runTest("CWE190_Integer_Overflow__int_File_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14145()).runTest("CWE190_Integer_Overflow__int_File_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14144()).runTest("CWE190_Integer_Overflow__int_File_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13921()).runTest("CWE190_Integer_Overflow__int_database_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13920()).runTest("CWE190_Integer_Overflow__int_database_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14191()).runTest("CWE190_Integer_Overflow__int_File_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14190()).runTest("CWE190_Integer_Overflow__int_File_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13889()).runTest("CWE190_Integer_Overflow__int_database_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13888()).runTest("CWE190_Integer_Overflow__int_database_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14067()).runTest("CWE190_Integer_Overflow__int_Environment_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14066()).runTest("CWE190_Integer_Overflow__int_Environment_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14167()).runTest("CWE190_Integer_Overflow__int_File_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14166()).runTest("CWE190_Integer_Overflow__int_File_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14041()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14040()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14177()).runTest("CWE190_Integer_Overflow__int_File_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14176()).runTest("CWE190_Integer_Overflow__int_File_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14055()).runTest("CWE190_Integer_Overflow__int_Environment_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14054()).runTest("CWE190_Integer_Overflow__int_Environment_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13987()).runTest("CWE190_Integer_Overflow__int_Environment_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13986()).runTest("CWE190_Integer_Overflow__int_Environment_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14057()).runTest("CWE190_Integer_Overflow__int_Environment_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14056()).runTest("CWE190_Integer_Overflow__int_Environment_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14183()).runTest("CWE190_Integer_Overflow__int_File_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14182()).runTest("CWE190_Integer_Overflow__int_File_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14087()).runTest("CWE190_Integer_Overflow__int_Environment_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14086()).runTest("CWE190_Integer_Overflow__int_Environment_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14053()).runTest("CWE190_Integer_Overflow__int_Environment_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14052()).runTest("CWE190_Integer_Overflow__int_Environment_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13943()).runTest("CWE190_Integer_Overflow__int_database_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13942()).runTest("CWE190_Integer_Overflow__int_database_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14119()).runTest("CWE190_Integer_Overflow__int_File_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14118()).runTest("CWE190_Integer_Overflow__int_File_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13999()).runTest("CWE190_Integer_Overflow__int_Environment_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13998()).runTest("CWE190_Integer_Overflow__int_Environment_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13991()).runTest("CWE190_Integer_Overflow__int_Environment_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13990()).runTest("CWE190_Integer_Overflow__int_Environment_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14223()).runTest("CWE190_Integer_Overflow__int_File_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14222()).runTest("CWE190_Integer_Overflow__int_File_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14199()).runTest("CWE190_Integer_Overflow__int_File_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14198()).runTest("CWE190_Integer_Overflow__int_File_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14137()).runTest("CWE190_Integer_Overflow__int_File_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14136()).runTest("CWE190_Integer_Overflow__int_File_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14165()).runTest("CWE190_Integer_Overflow__int_File_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14164()).runTest("CWE190_Integer_Overflow__int_File_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13933()).runTest("CWE190_Integer_Overflow__int_database_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13932()).runTest("CWE190_Integer_Overflow__int_database_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14031()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14030()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14075()).runTest("CWE190_Integer_Overflow__int_Environment_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14074()).runTest("CWE190_Integer_Overflow__int_Environment_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14037()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14036()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14175()).runTest("CWE190_Integer_Overflow__int_File_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14174()).runTest("CWE190_Integer_Overflow__int_File_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14207()).runTest("CWE190_Integer_Overflow__int_File_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14206()).runTest("CWE190_Integer_Overflow__int_File_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14079()).runTest("CWE190_Integer_Overflow__int_Environment_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14078()).runTest("CWE190_Integer_Overflow__int_Environment_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13965()).runTest("CWE190_Integer_Overflow__int_Environment_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13964()).runTest("CWE190_Integer_Overflow__int_Environment_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13969()).runTest("CWE190_Integer_Overflow__int_Environment_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13968()).runTest("CWE190_Integer_Overflow__int_Environment_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14019()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14018()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14113()).runTest("CWE190_Integer_Overflow__int_File_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14112()).runTest("CWE190_Integer_Overflow__int_File_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14181()).runTest("CWE190_Integer_Overflow__int_File_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14180()).runTest("CWE190_Integer_Overflow__int_File_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13951()).runTest("CWE190_Integer_Overflow__int_database_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13950()).runTest("CWE190_Integer_Overflow__int_database_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14027()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14026()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14083()).runTest("CWE190_Integer_Overflow__int_Environment_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14082()).runTest("CWE190_Integer_Overflow__int_Environment_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14131()).runTest("CWE190_Integer_Overflow__int_File_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14130()).runTest("CWE190_Integer_Overflow__int_File_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13929()).runTest("CWE190_Integer_Overflow__int_database_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13928()).runTest("CWE190_Integer_Overflow__int_database_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14105()).runTest("CWE190_Integer_Overflow__int_File_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14104()).runTest("CWE190_Integer_Overflow__int_File_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13873()).runTest("CWE190_Integer_Overflow__int_database_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13872()).runTest("CWE190_Integer_Overflow__int_database_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13909()).runTest("CWE190_Integer_Overflow__int_database_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13908()).runTest("CWE190_Integer_Overflow__int_database_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13899()).runTest("CWE190_Integer_Overflow__int_database_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13898()).runTest("CWE190_Integer_Overflow__int_database_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14029()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14028()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14133()).runTest("CWE190_Integer_Overflow__int_File_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14132()).runTest("CWE190_Integer_Overflow__int_File_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13903()).runTest("CWE190_Integer_Overflow__int_database_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13902()).runTest("CWE190_Integer_Overflow__int_database_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13953()).runTest("CWE190_Integer_Overflow__int_database_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13952()).runTest("CWE190_Integer_Overflow__int_database_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14103()).runTest("CWE190_Integer_Overflow__int_File_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14102()).runTest("CWE190_Integer_Overflow__int_File_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13967()).runTest("CWE190_Integer_Overflow__int_Environment_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13966()).runTest("CWE190_Integer_Overflow__int_Environment_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14045()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14044()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14073()).runTest("CWE190_Integer_Overflow__int_Environment_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14072()).runTest("CWE190_Integer_Overflow__int_Environment_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13935()).runTest("CWE190_Integer_Overflow__int_database_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13934()).runTest("CWE190_Integer_Overflow__int_database_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14039()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14038()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14213()).runTest("CWE190_Integer_Overflow__int_File_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14212()).runTest("CWE190_Integer_Overflow__int_File_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14187()).runTest("CWE190_Integer_Overflow__int_File_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14186()).runTest("CWE190_Integer_Overflow__int_File_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13989()).runTest("CWE190_Integer_Overflow__int_Environment_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13988()).runTest("CWE190_Integer_Overflow__int_Environment_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13955()).runTest("CWE190_Integer_Overflow__int_database_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13954()).runTest("CWE190_Integer_Overflow__int_database_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14139()).runTest("CWE190_Integer_Overflow__int_File_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14138()).runTest("CWE190_Integer_Overflow__int_File_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14219()).runTest("CWE190_Integer_Overflow__int_File_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14218()).runTest("CWE190_Integer_Overflow__int_File_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14217()).runTest("CWE190_Integer_Overflow__int_File_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14216()).runTest("CWE190_Integer_Overflow__int_File_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s02.J13907()).runTest("CWE190_Integer_Overflow__int_database_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J13906()).runTest("CWE190_Integer_Overflow__int_database_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14157()).runTest("CWE190_Integer_Overflow__int_File_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14156()).runTest("CWE190_Integer_Overflow__int_File_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14017()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14016()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s02.J14163()).runTest("CWE190_Integer_Overflow__int_File_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s02.J14162()).runTest("CWE190_Integer_Overflow__int_File_multiply_14_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
