package testcases.CWE190_Integer_Overflow.s02;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_12_good()).runTest("CWE190_Integer_Overflow__int_File_square_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_12_bad()).runTest("CWE190_Integer_Overflow__int_File_square_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_15_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_15_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_10_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_10_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_17_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_17_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_13_good()).runTest("CWE190_Integer_Overflow__int_File_add_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_13_bad()).runTest("CWE190_Integer_Overflow__int_File_add_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_31_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_31_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_08_good()).runTest("CWE190_Integer_Overflow__int_File_square_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_08_bad()).runTest("CWE190_Integer_Overflow__int_File_square_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_11_good()).runTest("CWE190_Integer_Overflow__int_database_square_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_11_bad()).runTest("CWE190_Integer_Overflow__int_database_square_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_10_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_10_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_04_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_04_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_03_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_03_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_17_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_17_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_21_good()).runTest("CWE190_Integer_Overflow__int_File_square_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_21_bad()).runTest("CWE190_Integer_Overflow__int_File_square_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_07_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_07_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_08_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_08_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_15_good()).runTest("CWE190_Integer_Overflow__int_File_square_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_15_bad()).runTest("CWE190_Integer_Overflow__int_File_square_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_42_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_42_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_45_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_45_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_11_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_11_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_06_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_06_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_45_good()).runTest("CWE190_Integer_Overflow__int_database_square_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_45_bad()).runTest("CWE190_Integer_Overflow__int_database_square_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_04_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_04_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_05_good()).runTest("CWE190_Integer_Overflow__int_database_square_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_05_bad()).runTest("CWE190_Integer_Overflow__int_database_square_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_31_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_31_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_11_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_11_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_12_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_12_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_03_good()).runTest("CWE190_Integer_Overflow__int_File_add_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_03_bad()).runTest("CWE190_Integer_Overflow__int_File_add_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_02_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_02_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_21_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_21_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_13_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_13_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_13_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_13_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_15_good()).runTest("CWE190_Integer_Overflow__int_File_add_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_15_bad()).runTest("CWE190_Integer_Overflow__int_File_add_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_01_good()).runTest("CWE190_Integer_Overflow__int_File_add_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_01_bad()).runTest("CWE190_Integer_Overflow__int_File_add_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_09_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_09_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_45_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_45_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_01_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_01_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_45_good()).runTest("CWE190_Integer_Overflow__int_File_add_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_45_bad()).runTest("CWE190_Integer_Overflow__int_File_add_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_12_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_12_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_07_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_07_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_17_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_17_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_45_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_45_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_05_good()).runTest("CWE190_Integer_Overflow__int_File_square_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_05_bad()).runTest("CWE190_Integer_Overflow__int_File_square_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_16_good()).runTest("CWE190_Integer_Overflow__int_File_square_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_16_bad()).runTest("CWE190_Integer_Overflow__int_File_square_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_06_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_06_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_16_good()).runTest("CWE190_Integer_Overflow__int_File_add_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_16_bad()).runTest("CWE190_Integer_Overflow__int_File_add_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_42_good()).runTest("CWE190_Integer_Overflow__int_File_square_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_42_bad()).runTest("CWE190_Integer_Overflow__int_File_square_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_03_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_03_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_31_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_31_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_12_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_12_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_08_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_08_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_01_good()).runTest("CWE190_Integer_Overflow__int_database_square_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_01_bad()).runTest("CWE190_Integer_Overflow__int_database_square_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_07_good()).runTest("CWE190_Integer_Overflow__int_File_square_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_07_bad()).runTest("CWE190_Integer_Overflow__int_File_square_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_10_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_10_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_10_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_10_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_04_good()).runTest("CWE190_Integer_Overflow__int_database_square_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_04_bad()).runTest("CWE190_Integer_Overflow__int_database_square_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_17_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_17_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_42_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_42_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_11_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_11_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_02_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_02_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_01_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_01_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_21_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_21_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_12_good()).runTest("CWE190_Integer_Overflow__int_database_square_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_12_bad()).runTest("CWE190_Integer_Overflow__int_database_square_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_16_good()).runTest("CWE190_Integer_Overflow__int_database_square_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_16_bad()).runTest("CWE190_Integer_Overflow__int_database_square_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_05_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_05_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_06_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_06_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_13_good()).runTest("CWE190_Integer_Overflow__int_File_square_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_13_bad()).runTest("CWE190_Integer_Overflow__int_File_square_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_42_good()).runTest("CWE190_Integer_Overflow__int_database_square_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_42_bad()).runTest("CWE190_Integer_Overflow__int_database_square_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_04_good()).runTest("CWE190_Integer_Overflow__int_File_add_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_04_bad()).runTest("CWE190_Integer_Overflow__int_File_add_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_15_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_15_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_05_good()).runTest("CWE190_Integer_Overflow__int_File_add_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_05_bad()).runTest("CWE190_Integer_Overflow__int_File_add_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_42_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_42_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_08_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_08_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_09_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_09_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_31_good()).runTest("CWE190_Integer_Overflow__int_File_add_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_31_bad()).runTest("CWE190_Integer_Overflow__int_File_add_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_16_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_16_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_13_good()).runTest("CWE190_Integer_Overflow__int_database_square_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_13_bad()).runTest("CWE190_Integer_Overflow__int_database_square_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_06_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_06_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_09_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_09_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_02_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_02_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_45_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_45_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_02_good()).runTest("CWE190_Integer_Overflow__int_File_add_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_02_bad()).runTest("CWE190_Integer_Overflow__int_File_add_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_04_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_04_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_11_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_11_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_03_good()).runTest("CWE190_Integer_Overflow__int_File_square_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_03_bad()).runTest("CWE190_Integer_Overflow__int_File_square_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_08_good()).runTest("CWE190_Integer_Overflow__int_File_add_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_08_bad()).runTest("CWE190_Integer_Overflow__int_File_add_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_07_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_07_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_41_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_41_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_12_good()).runTest("CWE190_Integer_Overflow__int_File_add_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_12_bad()).runTest("CWE190_Integer_Overflow__int_File_add_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_13_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_13_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_02_good()).runTest("CWE190_Integer_Overflow__int_database_square_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_02_bad()).runTest("CWE190_Integer_Overflow__int_database_square_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_17_good()).runTest("CWE190_Integer_Overflow__int_database_square_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_17_bad()).runTest("CWE190_Integer_Overflow__int_database_square_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_41_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_41_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_02_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_02_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_06_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_06_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_09_good()).runTest("CWE190_Integer_Overflow__int_File_add_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_09_bad()).runTest("CWE190_Integer_Overflow__int_File_add_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_06_good()).runTest("CWE190_Integer_Overflow__int_database_square_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_06_bad()).runTest("CWE190_Integer_Overflow__int_database_square_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_12_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_12_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_10_good()).runTest("CWE190_Integer_Overflow__int_File_add_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_10_bad()).runTest("CWE190_Integer_Overflow__int_File_add_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_08_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_08_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_09_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_09_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_15_good()).runTest("CWE190_Integer_Overflow__int_database_square_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_15_bad()).runTest("CWE190_Integer_Overflow__int_database_square_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_15_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_15_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_03_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_03_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_08_good()).runTest("CWE190_Integer_Overflow__int_database_square_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_08_bad()).runTest("CWE190_Integer_Overflow__int_database_square_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_09_good()).runTest("CWE190_Integer_Overflow__int_File_square_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_09_bad()).runTest("CWE190_Integer_Overflow__int_File_square_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_07_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_07_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_21_good()).runTest("CWE190_Integer_Overflow__int_File_add_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_21_bad()).runTest("CWE190_Integer_Overflow__int_File_add_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_17_good()).runTest("CWE190_Integer_Overflow__int_File_add_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_17_bad()).runTest("CWE190_Integer_Overflow__int_File_add_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_01_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_01_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_05_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_05_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_45_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_45_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_11_good()).runTest("CWE190_Integer_Overflow__int_File_square_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_11_bad()).runTest("CWE190_Integer_Overflow__int_File_square_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_05_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_05_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_03_good()).runTest("CWE190_Integer_Overflow__int_database_square_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_03_bad()).runTest("CWE190_Integer_Overflow__int_database_square_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_06_good()).runTest("CWE190_Integer_Overflow__int_File_square_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_06_bad()).runTest("CWE190_Integer_Overflow__int_File_square_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_09_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_09_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_10_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_10_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_16_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_16_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_31_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_31_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_42_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_42_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_04_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_04_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_14_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_14_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_05_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_05_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_02_good()).runTest("CWE190_Integer_Overflow__int_File_square_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_02_bad()).runTest("CWE190_Integer_Overflow__int_File_square_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_41_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_41_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_03_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_03_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_14_good()).runTest("CWE190_Integer_Overflow__int_database_square_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_14_bad()).runTest("CWE190_Integer_Overflow__int_database_square_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_14_good()).runTest("CWE190_Integer_Overflow__int_File_add_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_14_bad()).runTest("CWE190_Integer_Overflow__int_File_add_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_41_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_41_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_16_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_16_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_45_good()).runTest("CWE190_Integer_Overflow__int_File_square_45_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_45_bad()).runTest("CWE190_Integer_Overflow__int_File_square_45_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_10_good()).runTest("CWE190_Integer_Overflow__int_File_square_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_10_bad()).runTest("CWE190_Integer_Overflow__int_File_square_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_01_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_01_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_15_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_15_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_09_good()).runTest("CWE190_Integer_Overflow__int_database_square_09_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_09_bad()).runTest("CWE190_Integer_Overflow__int_database_square_09_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_14_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_14_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_14_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_14_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_17_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_17_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_41_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_41_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_14_good()).runTest("CWE190_Integer_Overflow__int_File_square_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_14_bad()).runTest("CWE190_Integer_Overflow__int_File_square_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_16_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_16_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_03_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_03_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_03_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_03_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_05_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_05_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_05_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_05_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_08_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_08_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_08_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_08_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_11_good()).runTest("CWE190_Integer_Overflow__int_File_add_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_11_bad()).runTest("CWE190_Integer_Overflow__int_File_add_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_01_good()).runTest("CWE190_Integer_Overflow__int_File_square_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_01_bad()).runTest("CWE190_Integer_Overflow__int_File_square_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_21_good()).runTest("CWE190_Integer_Overflow__int_database_square_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_21_bad()).runTest("CWE190_Integer_Overflow__int_database_square_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_12_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_12_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_12_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_12_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_21_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_21_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_41_good()).runTest("CWE190_Integer_Overflow__int_File_add_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_41_bad()).runTest("CWE190_Integer_Overflow__int_File_add_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_07_good()).runTest("CWE190_Integer_Overflow__int_database_square_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_07_bad()).runTest("CWE190_Integer_Overflow__int_database_square_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_07_good()).runTest("CWE190_Integer_Overflow__int_File_add_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_07_bad()).runTest("CWE190_Integer_Overflow__int_File_add_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_01_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_01_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_01_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_01_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_31_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_31_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_14_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_14_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_14_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_13_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_13_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_42_good()).runTest("CWE190_Integer_Overflow__int_File_add_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_42_bad()).runTest("CWE190_Integer_Overflow__int_File_add_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_16_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_16_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_16_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_16_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_31_good()).runTest("CWE190_Integer_Overflow__int_database_square_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_31_bad()).runTest("CWE190_Integer_Overflow__int_database_square_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_06_good()).runTest("CWE190_Integer_Overflow__int_File_add_06_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_add_06_bad()).runTest("CWE190_Integer_Overflow__int_File_add_06_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_04_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_04_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_42_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_42_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_42_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_42_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_13_good()).runTest("CWE190_Integer_Overflow__int_Environment_square_13_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_square_13_bad()).runTest("CWE190_Integer_Overflow__int_Environment_square_13_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_10_good()).runTest("CWE190_Integer_Overflow__int_database_square_10_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_10_bad()).runTest("CWE190_Integer_Overflow__int_database_square_10_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_21_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_21_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_17_good()).runTest("CWE190_Integer_Overflow__int_File_square_17_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_17_bad()).runTest("CWE190_Integer_Overflow__int_File_square_17_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_04_good()).runTest("CWE190_Integer_Overflow__int_File_square_04_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_04_bad()).runTest("CWE190_Integer_Overflow__int_File_square_04_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_15_good()).runTest("CWE190_Integer_Overflow__int_Environment_add_15_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_add_15_bad()).runTest("CWE190_Integer_Overflow__int_Environment_add_15_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_41_good()).runTest("CWE190_Integer_Overflow__int_database_square_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_square_41_bad()).runTest("CWE190_Integer_Overflow__int_database_square_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_02_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_02_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_02_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_02_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_41_good()).runTest("CWE190_Integer_Overflow__int_File_square_41_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_41_bad()).runTest("CWE190_Integer_Overflow__int_File_square_41_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_31_good()).runTest("CWE190_Integer_Overflow__int_File_square_31_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_square_31_bad()).runTest("CWE190_Integer_Overflow__int_File_square_31_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_21_good()).runTest("CWE190_Integer_Overflow__int_database_multiply_21_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_database_multiply_21_bad()).runTest("CWE190_Integer_Overflow__int_database_multiply_21_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_11_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_11_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_11_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_11_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_07_good()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_07_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_Environment_multiply_07_bad()).runTest("CWE190_Integer_Overflow__int_Environment_multiply_07_bad");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_14_good()).runTest("CWE190_Integer_Overflow__int_File_multiply_14_good");
        (new testcases.CWE190_Integer_Overflow.s02.CWE190_Integer_Overflow__int_File_multiply_14_bad()).runTest("CWE190_Integer_Overflow__int_File_multiply_14_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
