package testcases.CWE89_SQL_Injection.s01;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s01.J23163()).runTest("CWE89_SQL_Injection__database_prepareStatement_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23162()).runTest("CWE89_SQL_Injection__database_prepareStatement_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23025()).runTest("CWE89_SQL_Injection__database_executeQuery_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23024()).runTest("CWE89_SQL_Injection__database_executeQuery_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J23043()).runTest("CWE89_SQL_Injection__database_executeQuery_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23042()).runTest("CWE89_SQL_Injection__database_executeQuery_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22765()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22764()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J23209()).runTest("CWE89_SQL_Injection__Environment_executeBatch_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23208()).runTest("CWE89_SQL_Injection__Environment_executeBatch_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22603()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22602()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J23215()).runTest("CWE89_SQL_Injection__Environment_executeBatch_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23214()).runTest("CWE89_SQL_Injection__Environment_executeBatch_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22725()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22724()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23195()).runTest("CWE89_SQL_Injection__Environment_executeBatch_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23194()).runTest("CWE89_SQL_Injection__Environment_executeBatch_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23135()).runTest("CWE89_SQL_Injection__database_execute_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23134()).runTest("CWE89_SQL_Injection__database_execute_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22991()).runTest("CWE89_SQL_Injection__database_executeBatch_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22990()).runTest("CWE89_SQL_Injection__database_executeBatch_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22773()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22772()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22783()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22782()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22965()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22964()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23205()).runTest("CWE89_SQL_Injection__Environment_executeBatch_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23204()).runTest("CWE89_SQL_Injection__Environment_executeBatch_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J23235()).runTest("CWE89_SQL_Injection__Environment_executeBatch_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23234()).runTest("CWE89_SQL_Injection__Environment_executeBatch_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22985()).runTest("CWE89_SQL_Injection__database_executeBatch_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22984()).runTest("CWE89_SQL_Injection__database_executeBatch_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J23001()).runTest("CWE89_SQL_Injection__database_executeBatch_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23000()).runTest("CWE89_SQL_Injection__database_executeBatch_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22813()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22812()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23005()).runTest("CWE89_SQL_Injection__database_executeBatch_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23004()).runTest("CWE89_SQL_Injection__database_executeBatch_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22851()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22850()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J23177()).runTest("CWE89_SQL_Injection__database_prepareStatement_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23176()).runTest("CWE89_SQL_Injection__database_prepareStatement_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22757()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22756()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22737()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22736()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J23151()).runTest("CWE89_SQL_Injection__database_prepareStatement_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23150()).runTest("CWE89_SQL_Injection__database_prepareStatement_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22593()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22592()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23017()).runTest("CWE89_SQL_Injection__database_executeBatch_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23016()).runTest("CWE89_SQL_Injection__database_executeBatch_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J23231()).runTest("CWE89_SQL_Injection__Environment_executeBatch_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23230()).runTest("CWE89_SQL_Injection__Environment_executeBatch_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22709()).runTest("CWE89_SQL_Injection__connect_tcp_execute_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22708()).runTest("CWE89_SQL_Injection__connect_tcp_execute_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J23035()).runTest("CWE89_SQL_Injection__database_executeQuery_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23034()).runTest("CWE89_SQL_Injection__database_executeQuery_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22659()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22658()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23143()).runTest("CWE89_SQL_Injection__database_execute_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23142()).runTest("CWE89_SQL_Injection__database_execute_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23081()).runTest("CWE89_SQL_Injection__database_executeUpdate_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23080()).runTest("CWE89_SQL_Injection__database_executeUpdate_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23127()).runTest("CWE89_SQL_Injection__database_execute_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23126()).runTest("CWE89_SQL_Injection__database_execute_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22557()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22556()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22733()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22732()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22543()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22542()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J23183()).runTest("CWE89_SQL_Injection__database_prepareStatement_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23182()).runTest("CWE89_SQL_Injection__database_prepareStatement_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22539()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22538()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22875()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22874()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22541()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22540()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22899()).runTest("CWE89_SQL_Injection__console_readLine_execute_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22898()).runTest("CWE89_SQL_Injection__console_readLine_execute_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22759()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22758()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22915()).runTest("CWE89_SQL_Injection__console_readLine_execute_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22914()).runTest("CWE89_SQL_Injection__console_readLine_execute_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23061()).runTest("CWE89_SQL_Injection__database_executeQuery_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23060()).runTest("CWE89_SQL_Injection__database_executeQuery_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22959()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22958()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22827()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22826()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23067()).runTest("CWE89_SQL_Injection__database_executeUpdate_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23066()).runTest("CWE89_SQL_Injection__database_executeUpdate_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22981()).runTest("CWE89_SQL_Injection__database_executeBatch_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22980()).runTest("CWE89_SQL_Injection__database_executeBatch_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22555()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22554()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22923()).runTest("CWE89_SQL_Injection__console_readLine_execute_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22922()).runTest("CWE89_SQL_Injection__console_readLine_execute_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22817()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22816()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22549()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22548()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22685()).runTest("CWE89_SQL_Injection__connect_tcp_execute_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22684()).runTest("CWE89_SQL_Injection__connect_tcp_execute_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22781()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22780()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J23147()).runTest("CWE89_SQL_Injection__database_execute_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23146()).runTest("CWE89_SQL_Injection__database_execute_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22887()).runTest("CWE89_SQL_Injection__console_readLine_execute_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22886()).runTest("CWE89_SQL_Injection__console_readLine_execute_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22721()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22720()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22629()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22628()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22893()).runTest("CWE89_SQL_Injection__console_readLine_execute_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22892()).runTest("CWE89_SQL_Injection__console_readLine_execute_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22787()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22786()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23227()).runTest("CWE89_SQL_Injection__Environment_executeBatch_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23226()).runTest("CWE89_SQL_Injection__Environment_executeBatch_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22729()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22728()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23003()).runTest("CWE89_SQL_Injection__database_executeBatch_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23002()).runTest("CWE89_SQL_Injection__database_executeBatch_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22983()).runTest("CWE89_SQL_Injection__database_executeBatch_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22982()).runTest("CWE89_SQL_Injection__database_executeBatch_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J23219()).runTest("CWE89_SQL_Injection__Environment_executeBatch_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23218()).runTest("CWE89_SQL_Injection__Environment_executeBatch_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22907()).runTest("CWE89_SQL_Injection__console_readLine_execute_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22906()).runTest("CWE89_SQL_Injection__console_readLine_execute_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22727()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22726()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J23069()).runTest("CWE89_SQL_Injection__database_executeUpdate_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23068()).runTest("CWE89_SQL_Injection__database_executeUpdate_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22619()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22618()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22871()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22870()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23223()).runTest("CWE89_SQL_Injection__Environment_executeBatch_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23222()).runTest("CWE89_SQL_Injection__Environment_executeBatch_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23015()).runTest("CWE89_SQL_Injection__database_executeBatch_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23014()).runTest("CWE89_SQL_Injection__database_executeBatch_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23091()).runTest("CWE89_SQL_Injection__database_executeUpdate_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23090()).runTest("CWE89_SQL_Injection__database_executeUpdate_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23229()).runTest("CWE89_SQL_Injection__Environment_executeBatch_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23228()).runTest("CWE89_SQL_Injection__Environment_executeBatch_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22587()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22586()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22921()).runTest("CWE89_SQL_Injection__console_readLine_execute_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22920()).runTest("CWE89_SQL_Injection__console_readLine_execute_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23057()).runTest("CWE89_SQL_Injection__database_executeQuery_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23056()).runTest("CWE89_SQL_Injection__database_executeQuery_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23051()).runTest("CWE89_SQL_Injection__database_executeQuery_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23050()).runTest("CWE89_SQL_Injection__database_executeQuery_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23037()).runTest("CWE89_SQL_Injection__database_executeQuery_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23036()).runTest("CWE89_SQL_Injection__database_executeQuery_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22793()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22792()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22545()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22544()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22681()).runTest("CWE89_SQL_Injection__connect_tcp_execute_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22680()).runTest("CWE89_SQL_Injection__connect_tcp_execute_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22753()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22752()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22825()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22824()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22627()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22626()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23221()).runTest("CWE89_SQL_Injection__Environment_executeBatch_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23220()).runTest("CWE89_SQL_Injection__Environment_executeBatch_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22997()).runTest("CWE89_SQL_Injection__database_executeBatch_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22996()).runTest("CWE89_SQL_Injection__database_executeBatch_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22687()).runTest("CWE89_SQL_Injection__connect_tcp_execute_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22686()).runTest("CWE89_SQL_Injection__connect_tcp_execute_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J23045()).runTest("CWE89_SQL_Injection__database_executeQuery_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23044()).runTest("CWE89_SQL_Injection__database_executeQuery_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J23213()).runTest("CWE89_SQL_Injection__Environment_executeBatch_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23212()).runTest("CWE89_SQL_Injection__Environment_executeBatch_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23063()).runTest("CWE89_SQL_Injection__database_executeUpdate_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23062()).runTest("CWE89_SQL_Injection__database_executeUpdate_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23075()).runTest("CWE89_SQL_Injection__database_executeUpdate_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23074()).runTest("CWE89_SQL_Injection__database_executeUpdate_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23013()).runTest("CWE89_SQL_Injection__database_executeBatch_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23012()).runTest("CWE89_SQL_Injection__database_executeBatch_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22651()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22650()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22779()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22778()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22643()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22642()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22877()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22876()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23111()).runTest("CWE89_SQL_Injection__database_execute_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23110()).runTest("CWE89_SQL_Injection__database_execute_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22639()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22638()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22661()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22660()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23175()).runTest("CWE89_SQL_Injection__database_prepareStatement_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23174()).runTest("CWE89_SQL_Injection__database_prepareStatement_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22849()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22848()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J23211()).runTest("CWE89_SQL_Injection__Environment_executeBatch_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23210()).runTest("CWE89_SQL_Injection__Environment_executeBatch_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22621()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22620()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J23113()).runTest("CWE89_SQL_Injection__database_execute_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23112()).runTest("CWE89_SQL_Injection__database_execute_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22553()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22552()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22885()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22884()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22705()).runTest("CWE89_SQL_Injection__connect_tcp_execute_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22704()).runTest("CWE89_SQL_Injection__connect_tcp_execute_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22901()).runTest("CWE89_SQL_Injection__console_readLine_execute_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22900()).runTest("CWE89_SQL_Injection__console_readLine_execute_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23007()).runTest("CWE89_SQL_Injection__database_executeBatch_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23006()).runTest("CWE89_SQL_Injection__database_executeBatch_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22637()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22636()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23033()).runTest("CWE89_SQL_Injection__database_executeQuery_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23032()).runTest("CWE89_SQL_Injection__database_executeQuery_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22647()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22646()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22735()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22734()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22841()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22840()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22693()).runTest("CWE89_SQL_Injection__connect_tcp_execute_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22692()).runTest("CWE89_SQL_Injection__connect_tcp_execute_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22999()).runTest("CWE89_SQL_Injection__database_executeBatch_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22998()).runTest("CWE89_SQL_Injection__database_executeBatch_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22771()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22770()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22671()).runTest("CWE89_SQL_Injection__connect_tcp_execute_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22670()).runTest("CWE89_SQL_Injection__connect_tcp_execute_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22743()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22742()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23119()).runTest("CWE89_SQL_Injection__database_execute_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23118()).runTest("CWE89_SQL_Injection__database_execute_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23139()).runTest("CWE89_SQL_Injection__database_execute_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23138()).runTest("CWE89_SQL_Injection__database_execute_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23103()).runTest("CWE89_SQL_Injection__database_executeUpdate_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23102()).runTest("CWE89_SQL_Injection__database_executeUpdate_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22731()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22730()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22597()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22596()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23115()).runTest("CWE89_SQL_Injection__database_execute_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23114()).runTest("CWE89_SQL_Injection__database_execute_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22927()).runTest("CWE89_SQL_Injection__console_readLine_execute_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22926()).runTest("CWE89_SQL_Injection__console_readLine_execute_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22741()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22740()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22703()).runTest("CWE89_SQL_Injection__connect_tcp_execute_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22702()).runTest("CWE89_SQL_Injection__connect_tcp_execute_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23225()).runTest("CWE89_SQL_Injection__Environment_executeBatch_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23224()).runTest("CWE89_SQL_Injection__Environment_executeBatch_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23199()).runTest("CWE89_SQL_Injection__Environment_executeBatch_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23198()).runTest("CWE89_SQL_Injection__Environment_executeBatch_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23191()).runTest("CWE89_SQL_Injection__database_prepareStatement_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23190()).runTest("CWE89_SQL_Injection__database_prepareStatement_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23201()).runTest("CWE89_SQL_Injection__Environment_executeBatch_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23200()).runTest("CWE89_SQL_Injection__Environment_executeBatch_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22879()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22878()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23095()).runTest("CWE89_SQL_Injection__database_executeUpdate_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23094()).runTest("CWE89_SQL_Injection__database_executeUpdate_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23141()).runTest("CWE89_SQL_Injection__database_execute_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23140()).runTest("CWE89_SQL_Injection__database_execute_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22867()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22866()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22855()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22854()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22785()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22784()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22601()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22600()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22789()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22788()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22791()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22790()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22815()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22814()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22939()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22938()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22767()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22766()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22561()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22560()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J23217()).runTest("CWE89_SQL_Injection__Environment_executeBatch_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23216()).runTest("CWE89_SQL_Injection__Environment_executeBatch_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22641()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22640()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23065()).runTest("CWE89_SQL_Injection__database_executeUpdate_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23064()).runTest("CWE89_SQL_Injection__database_executeUpdate_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22889()).runTest("CWE89_SQL_Injection__console_readLine_execute_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22888()).runTest("CWE89_SQL_Injection__console_readLine_execute_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22747()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22746()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22819()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22818()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22943()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22942()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22551()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22550()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22861()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22860()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22913()).runTest("CWE89_SQL_Injection__console_readLine_execute_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22912()).runTest("CWE89_SQL_Injection__console_readLine_execute_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22937()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22936()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J23079()).runTest("CWE89_SQL_Injection__database_executeUpdate_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23078()).runTest("CWE89_SQL_Injection__database_executeUpdate_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22655()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22654()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22931()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22930()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22925()).runTest("CWE89_SQL_Injection__console_readLine_execute_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22924()).runTest("CWE89_SQL_Injection__console_readLine_execute_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22761()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22760()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22941()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22940()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J23167()).runTest("CWE89_SQL_Injection__database_prepareStatement_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23166()).runTest("CWE89_SQL_Injection__database_prepareStatement_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J23109()).runTest("CWE89_SQL_Injection__database_execute_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23108()).runTest("CWE89_SQL_Injection__database_execute_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22809()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22808()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22873()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22872()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22905()).runTest("CWE89_SQL_Injection__console_readLine_execute_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22904()).runTest("CWE89_SQL_Injection__console_readLine_execute_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23189()).runTest("CWE89_SQL_Injection__database_prepareStatement_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23188()).runTest("CWE89_SQL_Injection__database_prepareStatement_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23185()).runTest("CWE89_SQL_Injection__database_prepareStatement_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23184()).runTest("CWE89_SQL_Injection__database_prepareStatement_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23073()).runTest("CWE89_SQL_Injection__database_executeUpdate_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23072()).runTest("CWE89_SQL_Injection__database_executeUpdate_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22585()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22584()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22957()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22956()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22591()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22590()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23071()).runTest("CWE89_SQL_Injection__database_executeUpdate_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23070()).runTest("CWE89_SQL_Injection__database_executeUpdate_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22807()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22806()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22845()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22844()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22657()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22656()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22883()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22882()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23233()).runTest("CWE89_SQL_Injection__Environment_executeBatch_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23232()).runTest("CWE89_SQL_Injection__Environment_executeBatch_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22769()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22768()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22909()).runTest("CWE89_SQL_Injection__console_readLine_execute_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22908()).runTest("CWE89_SQL_Injection__console_readLine_execute_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22615()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22614()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22977()).runTest("CWE89_SQL_Injection__database_executeBatch_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22976()).runTest("CWE89_SQL_Injection__database_executeBatch_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J23055()).runTest("CWE89_SQL_Injection__database_executeQuery_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23054()).runTest("CWE89_SQL_Injection__database_executeQuery_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22755()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22754()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22745()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22744()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22891()).runTest("CWE89_SQL_Injection__console_readLine_execute_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22890()).runTest("CWE89_SQL_Injection__console_readLine_execute_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23093()).runTest("CWE89_SQL_Injection__database_executeUpdate_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23092()).runTest("CWE89_SQL_Injection__database_executeUpdate_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22611()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22610()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23203()).runTest("CWE89_SQL_Injection__Environment_executeBatch_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23202()).runTest("CWE89_SQL_Injection__Environment_executeBatch_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22751()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22750()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22911()).runTest("CWE89_SQL_Injection__console_readLine_execute_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22910()).runTest("CWE89_SQL_Injection__console_readLine_execute_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J23207()).runTest("CWE89_SQL_Injection__Environment_executeBatch_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23206()).runTest("CWE89_SQL_Injection__Environment_executeBatch_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22839()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22838()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22689()).runTest("CWE89_SQL_Injection__connect_tcp_execute_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22688()).runTest("CWE89_SQL_Injection__connect_tcp_execute_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22749()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22748()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23129()).runTest("CWE89_SQL_Injection__database_execute_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23128()).runTest("CWE89_SQL_Injection__database_execute_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22805()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22804()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22829()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22828()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22935()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22934()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22863()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22862()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22645()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22644()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J23161()).runTest("CWE89_SQL_Injection__database_prepareStatement_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23160()).runTest("CWE89_SQL_Injection__database_prepareStatement_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22595()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22594()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22869()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22868()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22975()).runTest("CWE89_SQL_Injection__database_executeBatch_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22974()).runTest("CWE89_SQL_Injection__database_executeBatch_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23165()).runTest("CWE89_SQL_Injection__database_prepareStatement_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23164()).runTest("CWE89_SQL_Injection__database_prepareStatement_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22547()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22546()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23131()).runTest("CWE89_SQL_Injection__database_execute_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23130()).runTest("CWE89_SQL_Injection__database_execute_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22897()).runTest("CWE89_SQL_Injection__console_readLine_execute_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22896()).runTest("CWE89_SQL_Injection__console_readLine_execute_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22635()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22634()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23009()).runTest("CWE89_SQL_Injection__database_executeBatch_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23008()).runTest("CWE89_SQL_Injection__database_executeBatch_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23187()).runTest("CWE89_SQL_Injection__database_prepareStatement_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23186()).runTest("CWE89_SQL_Injection__database_prepareStatement_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23085()).runTest("CWE89_SQL_Injection__database_executeUpdate_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23084()).runTest("CWE89_SQL_Injection__database_executeUpdate_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22823()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22822()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J23173()).runTest("CWE89_SQL_Injection__database_prepareStatement_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23172()).runTest("CWE89_SQL_Injection__database_prepareStatement_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22865()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22864()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22961()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22960()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23083()).runTest("CWE89_SQL_Injection__database_executeUpdate_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23082()).runTest("CWE89_SQL_Injection__database_executeUpdate_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J23011()).runTest("CWE89_SQL_Injection__database_executeBatch_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23010()).runTest("CWE89_SQL_Injection__database_executeBatch_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22933()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22932()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22699()).runTest("CWE89_SQL_Injection__connect_tcp_execute_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22698()).runTest("CWE89_SQL_Injection__connect_tcp_execute_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22955()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22954()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22919()).runTest("CWE89_SQL_Injection__console_readLine_execute_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22918()).runTest("CWE89_SQL_Injection__console_readLine_execute_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J23197()).runTest("CWE89_SQL_Injection__Environment_executeBatch_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23196()).runTest("CWE89_SQL_Injection__Environment_executeBatch_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22971()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22970()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22663()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22662()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23123()).runTest("CWE89_SQL_Injection__database_execute_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23122()).runTest("CWE89_SQL_Injection__database_execute_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22677()).runTest("CWE89_SQL_Injection__connect_tcp_execute_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22676()).runTest("CWE89_SQL_Injection__connect_tcp_execute_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22669()).runTest("CWE89_SQL_Injection__connect_tcp_execute_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22668()).runTest("CWE89_SQL_Injection__connect_tcp_execute_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22691()).runTest("CWE89_SQL_Injection__connect_tcp_execute_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22690()).runTest("CWE89_SQL_Injection__connect_tcp_execute_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22573()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22572()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23021()).runTest("CWE89_SQL_Injection__database_executeQuery_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23020()).runTest("CWE89_SQL_Injection__database_executeQuery_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22797()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22796()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22739()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22738()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23145()).runTest("CWE89_SQL_Injection__database_execute_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23144()).runTest("CWE89_SQL_Injection__database_execute_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22623()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22622()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23159()).runTest("CWE89_SQL_Injection__database_prepareStatement_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23158()).runTest("CWE89_SQL_Injection__database_prepareStatement_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22653()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22652()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22811()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22810()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23237()).runTest("CWE89_SQL_Injection__Environment_executeBatch_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23236()).runTest("CWE89_SQL_Injection__Environment_executeBatch_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22881()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22880()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23087()).runTest("CWE89_SQL_Injection__database_executeUpdate_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23086()).runTest("CWE89_SQL_Injection__database_executeUpdate_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22679()).runTest("CWE89_SQL_Injection__connect_tcp_execute_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22678()).runTest("CWE89_SQL_Injection__connect_tcp_execute_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J23149()).runTest("CWE89_SQL_Injection__database_execute_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23148()).runTest("CWE89_SQL_Injection__database_execute_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22609()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22608()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23193()).runTest("CWE89_SQL_Injection__database_prepareStatement_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23192()).runTest("CWE89_SQL_Injection__database_prepareStatement_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22631()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22630()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22929()).runTest("CWE89_SQL_Injection__console_readLine_execute_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22928()).runTest("CWE89_SQL_Injection__console_readLine_execute_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22583()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22582()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22633()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22632()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22853()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22852()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J23047()).runTest("CWE89_SQL_Injection__database_executeQuery_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23046()).runTest("CWE89_SQL_Injection__database_executeQuery_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22895()).runTest("CWE89_SQL_Injection__console_readLine_execute_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22894()).runTest("CWE89_SQL_Injection__console_readLine_execute_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22717()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22716()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J22995()).runTest("CWE89_SQL_Injection__database_executeBatch_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22994()).runTest("CWE89_SQL_Injection__database_executeBatch_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J23027()).runTest("CWE89_SQL_Injection__database_executeQuery_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23026()).runTest("CWE89_SQL_Injection__database_executeQuery_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J23059()).runTest("CWE89_SQL_Injection__database_executeQuery_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23058()).runTest("CWE89_SQL_Injection__database_executeQuery_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22801()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22800()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22833()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22832()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22967()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22966()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22723()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22722()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22951()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22950()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22963()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22962()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22947()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22946()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22799()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22798()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23137()).runTest("CWE89_SQL_Injection__database_execute_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23136()).runTest("CWE89_SQL_Injection__database_execute_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23155()).runTest("CWE89_SQL_Injection__database_prepareStatement_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23154()).runTest("CWE89_SQL_Injection__database_prepareStatement_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22775()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22774()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22903()).runTest("CWE89_SQL_Injection__console_readLine_execute_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22902()).runTest("CWE89_SQL_Injection__console_readLine_execute_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J23077()).runTest("CWE89_SQL_Injection__database_executeUpdate_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23076()).runTest("CWE89_SQL_Injection__database_executeUpdate_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22859()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22858()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22695()).runTest("CWE89_SQL_Injection__connect_tcp_execute_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22694()).runTest("CWE89_SQL_Injection__connect_tcp_execute_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22607()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22606()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J23019()).runTest("CWE89_SQL_Injection__database_executeQuery_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23018()).runTest("CWE89_SQL_Injection__database_executeQuery_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23089()).runTest("CWE89_SQL_Injection__database_executeUpdate_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23088()).runTest("CWE89_SQL_Injection__database_executeUpdate_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22571()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22570()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23181()).runTest("CWE89_SQL_Injection__database_prepareStatement_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23180()).runTest("CWE89_SQL_Injection__database_prepareStatement_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22777()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22776()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J23153()).runTest("CWE89_SQL_Injection__database_prepareStatement_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23152()).runTest("CWE89_SQL_Injection__database_prepareStatement_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22577()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22576()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22617()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22616()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22837()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22836()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J23179()).runTest("CWE89_SQL_Injection__database_prepareStatement_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23178()).runTest("CWE89_SQL_Injection__database_prepareStatement_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22567()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22566()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22917()).runTest("CWE89_SQL_Injection__console_readLine_execute_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22916()).runTest("CWE89_SQL_Injection__console_readLine_execute_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23133()).runTest("CWE89_SQL_Injection__database_execute_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23132()).runTest("CWE89_SQL_Injection__database_execute_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22559()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_13_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22558()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_13_b");
        (new testcases.CWE89_SQL_Injection.s01.J22945()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22944()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22763()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22762()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22667()).runTest("CWE89_SQL_Injection__connect_tcp_execute_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22666()).runTest("CWE89_SQL_Injection__connect_tcp_execute_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22835()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22834()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J22625()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22624()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22589()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22588()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22715()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22714()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23121()).runTest("CWE89_SQL_Injection__database_execute_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23120()).runTest("CWE89_SQL_Injection__database_execute_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J23041()).runTest("CWE89_SQL_Injection__database_executeQuery_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23040()).runTest("CWE89_SQL_Injection__database_executeQuery_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22949()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22948()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22953()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22952()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22719()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22718()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22993()).runTest("CWE89_SQL_Injection__database_executeBatch_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22992()).runTest("CWE89_SQL_Injection__database_executeBatch_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J22575()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22574()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23099()).runTest("CWE89_SQL_Injection__database_executeUpdate_31_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23098()).runTest("CWE89_SQL_Injection__database_executeUpdate_31_b");
        (new testcases.CWE89_SQL_Injection.s01.J23105()).runTest("CWE89_SQL_Injection__database_executeUpdate_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23104()).runTest("CWE89_SQL_Injection__database_executeUpdate_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22683()).runTest("CWE89_SQL_Injection__connect_tcp_execute_09_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22682()).runTest("CWE89_SQL_Injection__connect_tcp_execute_09_b");
        (new testcases.CWE89_SQL_Injection.s01.J22857()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22856()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22821()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_12_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22820()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_12_b");
        (new testcases.CWE89_SQL_Injection.s01.J22701()).runTest("CWE89_SQL_Injection__connect_tcp_execute_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22700()).runTest("CWE89_SQL_Injection__connect_tcp_execute_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22697()).runTest("CWE89_SQL_Injection__connect_tcp_execute_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22696()).runTest("CWE89_SQL_Injection__connect_tcp_execute_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23097()).runTest("CWE89_SQL_Injection__database_executeUpdate_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23096()).runTest("CWE89_SQL_Injection__database_executeUpdate_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22665()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22664()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J22707()).runTest("CWE89_SQL_Injection__connect_tcp_execute_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22706()).runTest("CWE89_SQL_Injection__connect_tcp_execute_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J23053()).runTest("CWE89_SQL_Injection__database_executeQuery_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23052()).runTest("CWE89_SQL_Injection__database_executeQuery_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J23039()).runTest("CWE89_SQL_Injection__database_executeQuery_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23038()).runTest("CWE89_SQL_Injection__database_executeQuery_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22649()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22648()).runTest("CWE89_SQL_Injection__connect_tcp_executeUpdate_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J22831()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_17_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22830()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_17_b");
        (new testcases.CWE89_SQL_Injection.s01.J22675()).runTest("CWE89_SQL_Injection__connect_tcp_execute_05_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22674()).runTest("CWE89_SQL_Injection__connect_tcp_execute_05_b");
        (new testcases.CWE89_SQL_Injection.s01.J22673()).runTest("CWE89_SQL_Injection__connect_tcp_execute_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22672()).runTest("CWE89_SQL_Injection__connect_tcp_execute_04_b");
        (new testcases.CWE89_SQL_Injection.s01.J23049()).runTest("CWE89_SQL_Injection__database_executeQuery_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23048()).runTest("CWE89_SQL_Injection__database_executeQuery_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J22579()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22578()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22969()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22968()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22569()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22568()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22847()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22846()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23029()).runTest("CWE89_SQL_Injection__database_executeQuery_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23028()).runTest("CWE89_SQL_Injection__database_executeQuery_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22843()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22842()).runTest("CWE89_SQL_Injection__console_readLine_executeUpdate_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22711()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22710()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22599()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22598()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J23023()).runTest("CWE89_SQL_Injection__database_executeQuery_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23022()).runTest("CWE89_SQL_Injection__database_executeQuery_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23169()).runTest("CWE89_SQL_Injection__database_prepareStatement_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23168()).runTest("CWE89_SQL_Injection__database_prepareStatement_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23125()).runTest("CWE89_SQL_Injection__database_execute_10_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23124()).runTest("CWE89_SQL_Injection__database_execute_10_b");
        (new testcases.CWE89_SQL_Injection.s01.J23107()).runTest("CWE89_SQL_Injection__database_execute_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23106()).runTest("CWE89_SQL_Injection__database_execute_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J22537()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22536()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22795()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_42_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22794()).runTest("CWE89_SQL_Injection__console_readLine_executeBatch_42_b");
        (new testcases.CWE89_SQL_Injection.s01.J22803()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22802()).runTest("CWE89_SQL_Injection__console_readLine_executeQuery_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J23101()).runTest("CWE89_SQL_Injection__database_executeUpdate_41_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23100()).runTest("CWE89_SQL_Injection__database_executeUpdate_41_b");
        (new testcases.CWE89_SQL_Injection.s01.J22987()).runTest("CWE89_SQL_Injection__database_executeBatch_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22986()).runTest("CWE89_SQL_Injection__database_executeBatch_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22973()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_45_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22972()).runTest("CWE89_SQL_Injection__console_readLine_prepareStatement_45_b");
        (new testcases.CWE89_SQL_Injection.s01.J23171()).runTest("CWE89_SQL_Injection__database_prepareStatement_11_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23170()).runTest("CWE89_SQL_Injection__database_prepareStatement_11_b");
        (new testcases.CWE89_SQL_Injection.s01.J22535()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_01_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22534()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_01_b");
        (new testcases.CWE89_SQL_Injection.s01.J23117()).runTest("CWE89_SQL_Injection__database_execute_06_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23116()).runTest("CWE89_SQL_Injection__database_execute_06_b");
        (new testcases.CWE89_SQL_Injection.s01.J22605()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_14_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22604()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_14_b");
        (new testcases.CWE89_SQL_Injection.s01.J23031()).runTest("CWE89_SQL_Injection__database_executeQuery_07_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23030()).runTest("CWE89_SQL_Injection__database_executeQuery_07_b");
        (new testcases.CWE89_SQL_Injection.s01.J22989()).runTest("CWE89_SQL_Injection__database_executeBatch_08_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22988()).runTest("CWE89_SQL_Injection__database_executeBatch_08_b");
        (new testcases.CWE89_SQL_Injection.s01.J22979()).runTest("CWE89_SQL_Injection__database_executeBatch_03_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22978()).runTest("CWE89_SQL_Injection__database_executeBatch_03_b");
        (new testcases.CWE89_SQL_Injection.s01.J22613()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_21_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22612()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_21_b");
        (new testcases.CWE89_SQL_Injection.s01.J22713()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22712()).runTest("CWE89_SQL_Injection__connect_tcp_prepareStatement_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22563()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_15_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22562()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_15_b");
        (new testcases.CWE89_SQL_Injection.s01.J22581()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_02_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22580()).runTest("CWE89_SQL_Injection__connect_tcp_executeQuery_02_b");
        (new testcases.CWE89_SQL_Injection.s01.J22565()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_16_gd");
        (new testcases.CWE89_SQL_Injection.s01.J22564()).runTest("CWE89_SQL_Injection__connect_tcp_executeBatch_16_b");
        (new testcases.CWE89_SQL_Injection.s01.J23157()).runTest("CWE89_SQL_Injection__database_prepareStatement_04_gd");
        (new testcases.CWE89_SQL_Injection.s01.J23156()).runTest("CWE89_SQL_Injection__database_prepareStatement_04_b");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
