package testcases.CWE89_SQL_Injection.s04;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s04.J1685()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_01");
        (new testcases.CWE89_SQL_Injection.s04.J1684()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_01");
        (new testcases.CWE89_SQL_Injection.s04.J1677()).runTest("CWE89_SQL_Injection__Property_executeUpdate_01");
        (new testcases.CWE89_SQL_Injection.s04.J1676()).runTest("CWE89_SQL_Injection__Property_executeUpdate_01");
        (new testcases.CWE89_SQL_Injection.s04.J1671()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1670()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1675()).runTest("CWE89_SQL_Injection__Property_executeQuery_01");
        (new testcases.CWE89_SQL_Injection.s04.J1674()).runTest("CWE89_SQL_Injection__Property_executeQuery_01");
        (new testcases.CWE89_SQL_Injection.s04.J1681()).runTest("CWE89_SQL_Injection__Property_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1680()).runTest("CWE89_SQL_Injection__Property_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1691()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1690()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_01");
        (new testcases.CWE89_SQL_Injection.s04.J1689()).runTest("CWE89_SQL_Injection__URLConnection_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1688()).runTest("CWE89_SQL_Injection__URLConnection_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1687()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_01");
        (new testcases.CWE89_SQL_Injection.s04.J1686()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_01");
        (new testcases.CWE89_SQL_Injection.s04.J1669()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1668()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1679()).runTest("CWE89_SQL_Injection__Property_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1678()).runTest("CWE89_SQL_Injection__Property_execute_01");
        (new testcases.CWE89_SQL_Injection.s04.J1683()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_01");
        (new testcases.CWE89_SQL_Injection.s04.J1682()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_01");
        (new testcases.CWE89_SQL_Injection.s04.J1673()).runTest("CWE89_SQL_Injection__Property_executeBatch_01");
        (new testcases.CWE89_SQL_Injection.s04.J1672()).runTest("CWE89_SQL_Injection__Property_executeBatch_01");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
