package testcases.CWE89_SQL_Injection.s04;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
        (new testcases.CWE89_SQL_Injection.s04.J24707()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24706()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25053()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J25052()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24883()).runTest("CWE89_SQL_Injection__Property_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24882()).runTest("CWE89_SQL_Injection__Property_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24947()).runTest("CWE89_SQL_Injection__Property_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24946()).runTest("CWE89_SQL_Injection__Property_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24659()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24658()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24661()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24660()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25139()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J25138()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24851()).runTest("CWE89_SQL_Injection__Property_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24850()).runTest("CWE89_SQL_Injection__Property_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24999()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24998()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24963()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24962()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24823()).runTest("CWE89_SQL_Injection__Property_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24822()).runTest("CWE89_SQL_Injection__Property_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25125()).runTest("CWE89_SQL_Injection__URLConnection_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J25124()).runTest("CWE89_SQL_Injection__URLConnection_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24929()).runTest("CWE89_SQL_Injection__Property_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24928()).runTest("CWE89_SQL_Injection__Property_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24875()).runTest("CWE89_SQL_Injection__Property_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24874()).runTest("CWE89_SQL_Injection__Property_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25013()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J25012()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25039()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J25038()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25027()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J25026()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24665()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24664()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24777()).runTest("CWE89_SQL_Injection__Property_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24776()).runTest("CWE89_SQL_Injection__Property_executeBatch_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24763()).runTest("CWE89_SQL_Injection__Property_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24762()).runTest("CWE89_SQL_Injection__Property_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24933()).runTest("CWE89_SQL_Injection__Property_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24932()).runTest("CWE89_SQL_Injection__Property_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25007()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J25006()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24695()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24694()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24805()).runTest("CWE89_SQL_Injection__Property_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24804()).runTest("CWE89_SQL_Injection__Property_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25147()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J25146()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24987()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24986()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24923()).runTest("CWE89_SQL_Injection__Property_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24922()).runTest("CWE89_SQL_Injection__Property_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24879()).runTest("CWE89_SQL_Injection__Property_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24878()).runTest("CWE89_SQL_Injection__Property_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24953()).runTest("CWE89_SQL_Injection__Property_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24952()).runTest("CWE89_SQL_Injection__Property_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25031()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J25030()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24917()).runTest("CWE89_SQL_Injection__Property_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24916()).runTest("CWE89_SQL_Injection__Property_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25095()).runTest("CWE89_SQL_Injection__URLConnection_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J25094()).runTest("CWE89_SQL_Injection__URLConnection_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24691()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24690()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24855()).runTest("CWE89_SQL_Injection__Property_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24854()).runTest("CWE89_SQL_Injection__Property_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24849()).runTest("CWE89_SQL_Injection__Property_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24848()).runTest("CWE89_SQL_Injection__Property_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24715()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24714()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24679()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24678()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25073()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J25072()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25069()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J25068()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24831()).runTest("CWE89_SQL_Injection__Property_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24830()).runTest("CWE89_SQL_Injection__Property_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24891()).runTest("CWE89_SQL_Injection__Property_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24890()).runTest("CWE89_SQL_Injection__Property_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24821()).runTest("CWE89_SQL_Injection__Property_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24820()).runTest("CWE89_SQL_Injection__Property_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24811()).runTest("CWE89_SQL_Injection__Property_executeQuery_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24810()).runTest("CWE89_SQL_Injection__Property_executeQuery_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24951()).runTest("CWE89_SQL_Injection__Property_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24950()).runTest("CWE89_SQL_Injection__Property_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24657()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24656()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25093()).runTest("CWE89_SQL_Injection__URLConnection_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J25092()).runTest("CWE89_SQL_Injection__URLConnection_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25109()).runTest("CWE89_SQL_Injection__URLConnection_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J25108()).runTest("CWE89_SQL_Injection__URLConnection_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24791()).runTest("CWE89_SQL_Injection__Property_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24790()).runTest("CWE89_SQL_Injection__Property_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24779()).runTest("CWE89_SQL_Injection__Property_executeQuery_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24778()).runTest("CWE89_SQL_Injection__Property_executeQuery_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25037()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J25036()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24919()).runTest("CWE89_SQL_Injection__Property_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24918()).runTest("CWE89_SQL_Injection__Property_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24957()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24956()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24751()).runTest("CWE89_SQL_Injection__Property_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24750()).runTest("CWE89_SQL_Injection__Property_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24893()).runTest("CWE89_SQL_Injection__Property_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24892()).runTest("CWE89_SQL_Injection__Property_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24693()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24692()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24885()).runTest("CWE89_SQL_Injection__Property_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24884()).runTest("CWE89_SQL_Injection__Property_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25061()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J25060()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24881()).runTest("CWE89_SQL_Injection__Property_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24880()).runTest("CWE89_SQL_Injection__Property_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24911()).runTest("CWE89_SQL_Injection__Property_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24910()).runTest("CWE89_SQL_Injection__Property_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24801()).runTest("CWE89_SQL_Injection__Property_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24800()).runTest("CWE89_SQL_Injection__Property_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24677()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24676()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24843()).runTest("CWE89_SQL_Injection__Property_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24842()).runTest("CWE89_SQL_Injection__Property_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24663()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24662()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24899()).runTest("CWE89_SQL_Injection__Property_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24898()).runTest("CWE89_SQL_Injection__Property_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24729()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24728()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25101()).runTest("CWE89_SQL_Injection__URLConnection_execute_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J25100()).runTest("CWE89_SQL_Injection__URLConnection_execute_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24897()).runTest("CWE89_SQL_Injection__Property_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24896()).runTest("CWE89_SQL_Injection__Property_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24673()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24672()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25075()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J25074()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25173()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J25172()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25049()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J25048()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24787()).runTest("CWE89_SQL_Injection__Property_executeQuery_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24786()).runTest("CWE89_SQL_Injection__Property_executeQuery_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24759()).runTest("CWE89_SQL_Injection__Property_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24758()).runTest("CWE89_SQL_Injection__Property_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24991()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24990()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25153()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J25152()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25155()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J25154()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24835()).runTest("CWE89_SQL_Injection__Property_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24834()).runTest("CWE89_SQL_Injection__Property_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25001()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J25000()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24731()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24730()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24697()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24696()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25091()).runTest("CWE89_SQL_Injection__URLConnection_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J25090()).runTest("CWE89_SQL_Injection__URLConnection_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24903()).runTest("CWE89_SQL_Injection__Property_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24902()).runTest("CWE89_SQL_Injection__Property_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24719()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24718()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25161()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J25160()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24817()).runTest("CWE89_SQL_Injection__Property_executeQuery_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24816()).runTest("CWE89_SQL_Injection__Property_executeQuery_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25079()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J25078()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25127()).runTest("CWE89_SQL_Injection__URLConnection_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J25126()).runTest("CWE89_SQL_Injection__URLConnection_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24757()).runTest("CWE89_SQL_Injection__Property_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24756()).runTest("CWE89_SQL_Injection__Property_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25169()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J25168()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24839()).runTest("CWE89_SQL_Injection__Property_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24838()).runTest("CWE89_SQL_Injection__Property_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25005()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J25004()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25131()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J25130()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25009()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J25008()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24863()).runTest("CWE89_SQL_Injection__Property_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24862()).runTest("CWE89_SQL_Injection__Property_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24819()).runTest("CWE89_SQL_Injection__Property_executeQuery_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24818()).runTest("CWE89_SQL_Injection__Property_executeQuery_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24687()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24686()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25167()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J25166()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25151()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J25150()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24793()).runTest("CWE89_SQL_Injection__Property_executeQuery_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24792()).runTest("CWE89_SQL_Injection__Property_executeQuery_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24703()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24702()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25021()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J25020()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25087()).runTest("CWE89_SQL_Injection__URLConnection_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J25086()).runTest("CWE89_SQL_Injection__URLConnection_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25029()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J25028()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24653()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24652()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24667()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24666()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25111()).runTest("CWE89_SQL_Injection__URLConnection_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J25110()).runTest("CWE89_SQL_Injection__URLConnection_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25043()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J25042()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24973()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24972()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24717()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24716()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25117()).runTest("CWE89_SQL_Injection__URLConnection_execute_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J25116()).runTest("CWE89_SQL_Injection__URLConnection_execute_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25097()).runTest("CWE89_SQL_Injection__URLConnection_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J25096()).runTest("CWE89_SQL_Injection__URLConnection_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24827()).runTest("CWE89_SQL_Injection__Property_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24826()).runTest("CWE89_SQL_Injection__Property_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25137()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J25136()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24781()).runTest("CWE89_SQL_Injection__Property_executeQuery_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24780()).runTest("CWE89_SQL_Injection__Property_executeQuery_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24937()).runTest("CWE89_SQL_Injection__Property_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24936()).runTest("CWE89_SQL_Injection__Property_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24723()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24722()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24905()).runTest("CWE89_SQL_Injection__Property_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24904()).runTest("CWE89_SQL_Injection__Property_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24983()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24982()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24889()).runTest("CWE89_SQL_Injection__Property_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24888()).runTest("CWE89_SQL_Injection__Property_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25055()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J25054()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24943()).runTest("CWE89_SQL_Injection__Property_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24942()).runTest("CWE89_SQL_Injection__Property_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24699()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24698()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25157()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J25156()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24841()).runTest("CWE89_SQL_Injection__Property_executeUpdate_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24840()).runTest("CWE89_SQL_Injection__Property_executeUpdate_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24803()).runTest("CWE89_SQL_Injection__Property_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24802()).runTest("CWE89_SQL_Injection__Property_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24743()).runTest("CWE89_SQL_Injection__Property_executeBatch_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24742()).runTest("CWE89_SQL_Injection__Property_executeBatch_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24935()).runTest("CWE89_SQL_Injection__Property_prepareStatement_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24934()).runTest("CWE89_SQL_Injection__Property_prepareStatement_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24857()).runTest("CWE89_SQL_Injection__Property_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24856()).runTest("CWE89_SQL_Injection__Property_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25063()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J25062()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24711()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24710()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24683()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24682()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24807()).runTest("CWE89_SQL_Injection__Property_executeQuery_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24806()).runTest("CWE89_SQL_Injection__Property_executeQuery_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24675()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24674()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24959()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24958()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24769()).runTest("CWE89_SQL_Injection__Property_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24768()).runTest("CWE89_SQL_Injection__Property_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24925()).runTest("CWE89_SQL_Injection__Property_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24924()).runTest("CWE89_SQL_Injection__Property_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25135()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J25134()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25067()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J25066()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24727()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24726()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24859()).runTest("CWE89_SQL_Injection__Property_executeUpdate_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24858()).runTest("CWE89_SQL_Injection__Property_executeUpdate_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25119()).runTest("CWE89_SQL_Injection__URLConnection_execute_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J25118()).runTest("CWE89_SQL_Injection__URLConnection_execute_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25149()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J25148()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24853()).runTest("CWE89_SQL_Injection__Property_executeUpdate_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24852()).runTest("CWE89_SQL_Injection__Property_executeUpdate_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25047()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J25046()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24709()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24708()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24895()).runTest("CWE89_SQL_Injection__Property_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24894()).runTest("CWE89_SQL_Injection__Property_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24915()).runTest("CWE89_SQL_Injection__Property_prepareStatement_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24914()).runTest("CWE89_SQL_Injection__Property_prepareStatement_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25133()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J25132()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24765()).runTest("CWE89_SQL_Injection__Property_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24764()).runTest("CWE89_SQL_Injection__Property_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25105()).runTest("CWE89_SQL_Injection__URLConnection_execute_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J25104()).runTest("CWE89_SQL_Injection__URLConnection_execute_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25045()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J25044()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24689()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24688()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24783()).runTest("CWE89_SQL_Injection__Property_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24782()).runTest("CWE89_SQL_Injection__Property_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25099()).runTest("CWE89_SQL_Injection__URLConnection_execute_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J25098()).runTest("CWE89_SQL_Injection__URLConnection_execute_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25107()).runTest("CWE89_SQL_Injection__URLConnection_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J25106()).runTest("CWE89_SQL_Injection__URLConnection_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24741()).runTest("CWE89_SQL_Injection__Property_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24740()).runTest("CWE89_SQL_Injection__Property_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24761()).runTest("CWE89_SQL_Injection__Property_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24760()).runTest("CWE89_SQL_Injection__Property_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25035()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J25034()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24833()).runTest("CWE89_SQL_Injection__Property_executeUpdate_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24832()).runTest("CWE89_SQL_Injection__Property_executeUpdate_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24865()).runTest("CWE89_SQL_Injection__Property_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24864()).runTest("CWE89_SQL_Injection__Property_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24651()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24650()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25059()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J25058()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24989()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24988()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25023()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J25022()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24967()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24966()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24921()).runTest("CWE89_SQL_Injection__Property_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24920()).runTest("CWE89_SQL_Injection__Property_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24749()).runTest("CWE89_SQL_Injection__Property_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24748()).runTest("CWE89_SQL_Injection__Property_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24671()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24670()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24927()).runTest("CWE89_SQL_Injection__Property_prepareStatement_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24926()).runTest("CWE89_SQL_Injection__Property_prepareStatement_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25003()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J25002()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24773()).runTest("CWE89_SQL_Injection__Property_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24772()).runTest("CWE89_SQL_Injection__Property_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25051()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J25050()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24785()).runTest("CWE89_SQL_Injection__Property_executeQuery_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24784()).runTest("CWE89_SQL_Injection__Property_executeQuery_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24939()).runTest("CWE89_SQL_Injection__Property_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J24938()).runTest("CWE89_SQL_Injection__Property_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25103()).runTest("CWE89_SQL_Injection__URLConnection_execute_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J25102()).runTest("CWE89_SQL_Injection__URLConnection_execute_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24685()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24684()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24655()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_05_good");
        (new testcases.CWE89_SQL_Injection.s04.J24654()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_05_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24931()).runTest("CWE89_SQL_Injection__Property_prepareStatement_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24930()).runTest("CWE89_SQL_Injection__Property_prepareStatement_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24979()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24978()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24647()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24646()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25057()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J25056()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24861()).runTest("CWE89_SQL_Injection__Property_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24860()).runTest("CWE89_SQL_Injection__Property_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24913()).runTest("CWE89_SQL_Injection__Property_prepareStatement_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24912()).runTest("CWE89_SQL_Injection__Property_prepareStatement_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24837()).runTest("CWE89_SQL_Injection__Property_executeUpdate_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24836()).runTest("CWE89_SQL_Injection__Property_executeUpdate_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24721()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24720()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25113()).runTest("CWE89_SQL_Injection__URLConnection_execute_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J25112()).runTest("CWE89_SQL_Injection__URLConnection_execute_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24815()).runTest("CWE89_SQL_Injection__Property_executeQuery_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24814()).runTest("CWE89_SQL_Injection__Property_executeQuery_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24799()).runTest("CWE89_SQL_Injection__Property_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24798()).runTest("CWE89_SQL_Injection__Property_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24977()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24976()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25129()).runTest("CWE89_SQL_Injection__URLConnection_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J25128()).runTest("CWE89_SQL_Injection__URLConnection_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24981()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J24980()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24775()).runTest("CWE89_SQL_Injection__Property_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24774()).runTest("CWE89_SQL_Injection__Property_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25019()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J25018()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24873()).runTest("CWE89_SQL_Injection__Property_execute_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24872()).runTest("CWE89_SQL_Injection__Property_execute_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24795()).runTest("CWE89_SQL_Injection__Property_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24794()).runTest("CWE89_SQL_Injection__Property_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24669()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24668()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24867()).runTest("CWE89_SQL_Injection__Property_execute_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24866()).runTest("CWE89_SQL_Injection__Property_execute_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24809()).runTest("CWE89_SQL_Injection__Property_executeQuery_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24808()).runTest("CWE89_SQL_Injection__Property_executeQuery_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25041()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J25040()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24993()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24992()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25011()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J25010()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25089()).runTest("CWE89_SQL_Injection__URLConnection_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J25088()).runTest("CWE89_SQL_Injection__URLConnection_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24901()).runTest("CWE89_SQL_Injection__Property_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24900()).runTest("CWE89_SQL_Injection__Property_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24955()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24954()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25121()).runTest("CWE89_SQL_Injection__URLConnection_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J25120()).runTest("CWE89_SQL_Injection__URLConnection_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24945()).runTest("CWE89_SQL_Injection__Property_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24944()).runTest("CWE89_SQL_Injection__Property_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25015()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J25014()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24753()).runTest("CWE89_SQL_Injection__Property_executeBatch_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24752()).runTest("CWE89_SQL_Injection__Property_executeBatch_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25081()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J25080()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24649()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24648()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24845()).runTest("CWE89_SQL_Injection__Property_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24844()).runTest("CWE89_SQL_Injection__Property_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25141()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J25140()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24771()).runTest("CWE89_SQL_Injection__Property_executeBatch_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J24770()).runTest("CWE89_SQL_Injection__Property_executeBatch_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24789()).runTest("CWE89_SQL_Injection__Property_executeQuery_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24788()).runTest("CWE89_SQL_Injection__Property_executeQuery_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24681()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24680()).runTest("CWE89_SQL_Injection__PropertiesFile_execute_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24975()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24974()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24909()).runTest("CWE89_SQL_Injection__Property_execute_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24908()).runTest("CWE89_SQL_Injection__Property_execute_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24949()).runTest("CWE89_SQL_Injection__Property_prepareStatement_41_good");
        (new testcases.CWE89_SQL_Injection.s04.J24948()).runTest("CWE89_SQL_Injection__Property_prepareStatement_41_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25071()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J25070()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24887()).runTest("CWE89_SQL_Injection__Property_execute_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24886()).runTest("CWE89_SQL_Injection__Property_execute_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24713()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J24712()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24733()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24732()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24797()).runTest("CWE89_SQL_Injection__Property_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J24796()).runTest("CWE89_SQL_Injection__Property_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24825()).runTest("CWE89_SQL_Injection__Property_executeUpdate_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24824()).runTest("CWE89_SQL_Injection__Property_executeUpdate_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24871()).runTest("CWE89_SQL_Injection__Property_execute_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24870()).runTest("CWE89_SQL_Injection__Property_execute_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24971()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_09_good");
        (new testcases.CWE89_SQL_Injection.s04.J24970()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_09_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24745()).runTest("CWE89_SQL_Injection__Property_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24744()).runTest("CWE89_SQL_Injection__Property_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24969()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24968()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25077()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J25076()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24877()).runTest("CWE89_SQL_Injection__Property_execute_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24876()).runTest("CWE89_SQL_Injection__Property_execute_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25123()).runTest("CWE89_SQL_Injection__URLConnection_execute_31_good");
        (new testcases.CWE89_SQL_Injection.s04.J25122()).runTest("CWE89_SQL_Injection__URLConnection_execute_31_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24705()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J24704()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24829()).runTest("CWE89_SQL_Injection__Property_executeUpdate_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24828()).runTest("CWE89_SQL_Injection__Property_executeUpdate_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25145()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_08_good");
        (new testcases.CWE89_SQL_Injection.s04.J25144()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_08_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25165()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J25164()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24961()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_04_good");
        (new testcases.CWE89_SQL_Injection.s04.J24960()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_04_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24755()).runTest("CWE89_SQL_Injection__Property_executeBatch_11_good");
        (new testcases.CWE89_SQL_Injection.s04.J24754()).runTest("CWE89_SQL_Injection__Property_executeBatch_11_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25025()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_14_good");
        (new testcases.CWE89_SQL_Injection.s04.J25024()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_14_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24737()).runTest("CWE89_SQL_Injection__Property_executeBatch_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24736()).runTest("CWE89_SQL_Injection__Property_executeBatch_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24747()).runTest("CWE89_SQL_Injection__Property_executeBatch_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J24746()).runTest("CWE89_SQL_Injection__Property_executeBatch_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25083()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J25082()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24813()).runTest("CWE89_SQL_Injection__Property_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24812()).runTest("CWE89_SQL_Injection__Property_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25171()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J25170()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25115()).runTest("CWE89_SQL_Injection__URLConnection_execute_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J25114()).runTest("CWE89_SQL_Injection__URLConnection_execute_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25159()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_15_good");
        (new testcases.CWE89_SQL_Injection.s04.J25158()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_15_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24739()).runTest("CWE89_SQL_Injection__Property_executeBatch_03_good");
        (new testcases.CWE89_SQL_Injection.s04.J24738()).runTest("CWE89_SQL_Injection__Property_executeBatch_03_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25065()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_12_good");
        (new testcases.CWE89_SQL_Injection.s04.J25064()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_12_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24725()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J24724()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25017()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_10_good");
        (new testcases.CWE89_SQL_Injection.s04.J25016()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_10_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24735()).runTest("CWE89_SQL_Injection__Property_executeBatch_01_good");
        (new testcases.CWE89_SQL_Injection.s04.J24734()).runTest("CWE89_SQL_Injection__Property_executeBatch_01_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24701()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24700()).runTest("CWE89_SQL_Injection__PropertiesFile_prepareStatement_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24941()).runTest("CWE89_SQL_Injection__Property_prepareStatement_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24940()).runTest("CWE89_SQL_Injection__Property_prepareStatement_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25033()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_21_good");
        (new testcases.CWE89_SQL_Injection.s04.J25032()).runTest("CWE89_SQL_Injection__URLConnection_executeQuery_21_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24847()).runTest("CWE89_SQL_Injection__Property_executeUpdate_13_good");
        (new testcases.CWE89_SQL_Injection.s04.J24846()).runTest("CWE89_SQL_Injection__Property_executeUpdate_13_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25085()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J25084()).runTest("CWE89_SQL_Injection__URLConnection_executeUpdate_45_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25163()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J25162()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J25143()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_07_good");
        (new testcases.CWE89_SQL_Injection.s04.J25142()).runTest("CWE89_SQL_Injection__URLConnection_prepareStatement_07_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24869()).runTest("CWE89_SQL_Injection__Property_execute_02_good");
        (new testcases.CWE89_SQL_Injection.s04.J24868()).runTest("CWE89_SQL_Injection__Property_execute_02_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24965()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_06_good");
        (new testcases.CWE89_SQL_Injection.s04.J24964()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_06_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24985()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_16_good");
        (new testcases.CWE89_SQL_Injection.s04.J24984()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_16_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24907()).runTest("CWE89_SQL_Injection__Property_execute_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24906()).runTest("CWE89_SQL_Injection__Property_execute_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24995()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_42_good");
        (new testcases.CWE89_SQL_Injection.s04.J24994()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_42_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24767()).runTest("CWE89_SQL_Injection__Property_executeBatch_17_good");
        (new testcases.CWE89_SQL_Injection.s04.J24766()).runTest("CWE89_SQL_Injection__Property_executeBatch_17_bad");
        (new testcases.CWE89_SQL_Injection.s04.J24997()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_45_good");
        (new testcases.CWE89_SQL_Injection.s04.J24996()).runTest("CWE89_SQL_Injection__URLConnection_executeBatch_45_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
