package testcases.CWE190_Integer_Overflow.s03;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE190_Integer_Overflow.s03.J14893()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14892()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15173()).runTest("CWE190_Integer_Overflow__int_random_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15172()).runTest("CWE190_Integer_Overflow__int_random_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14927()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14926()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14959()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14958()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15075()).runTest("CWE190_Integer_Overflow__int_Property_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15074()).runTest("CWE190_Integer_Overflow__int_Property_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14865()).runTest("CWE190_Integer_Overflow__int_max_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14864()).runTest("CWE190_Integer_Overflow__int_max_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15127()).runTest("CWE190_Integer_Overflow__int_Property_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15126()).runTest("CWE190_Integer_Overflow__int_Property_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15211()).runTest("CWE190_Integer_Overflow__int_random_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15210()).runTest("CWE190_Integer_Overflow__int_random_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14957()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14956()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14625()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14624()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14809()).runTest("CWE190_Integer_Overflow__int_max_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14808()).runTest("CWE190_Integer_Overflow__int_max_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14971()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14970()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15241()).runTest("CWE190_Integer_Overflow__int_random_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15240()).runTest("CWE190_Integer_Overflow__int_random_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15043()).runTest("CWE190_Integer_Overflow__int_Property_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15042()).runTest("CWE190_Integer_Overflow__int_Property_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14629()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14628()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14827()).runTest("CWE190_Integer_Overflow__int_max_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14826()).runTest("CWE190_Integer_Overflow__int_max_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14757()).runTest("CWE190_Integer_Overflow__int_max_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14756()).runTest("CWE190_Integer_Overflow__int_max_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15271()).runTest("CWE190_Integer_Overflow__int_random_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15270()).runTest("CWE190_Integer_Overflow__int_random_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14667()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14666()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14653()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14652()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14715()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14714()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14997()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14996()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15185()).runTest("CWE190_Integer_Overflow__int_random_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15184()).runTest("CWE190_Integer_Overflow__int_random_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14703()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14702()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14881()).runTest("CWE190_Integer_Overflow__int_max_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14880()).runTest("CWE190_Integer_Overflow__int_max_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15103()).runTest("CWE190_Integer_Overflow__int_Property_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15102()).runTest("CWE190_Integer_Overflow__int_Property_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15269()).runTest("CWE190_Integer_Overflow__int_random_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15268()).runTest("CWE190_Integer_Overflow__int_random_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15053()).runTest("CWE190_Integer_Overflow__int_Property_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15052()).runTest("CWE190_Integer_Overflow__int_Property_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14909()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14908()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14843()).runTest("CWE190_Integer_Overflow__int_max_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14842()).runTest("CWE190_Integer_Overflow__int_max_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15007()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15006()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14883()).runTest("CWE190_Integer_Overflow__int_max_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14882()).runTest("CWE190_Integer_Overflow__int_max_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14681()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14680()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14759()).runTest("CWE190_Integer_Overflow__int_max_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14758()).runTest("CWE190_Integer_Overflow__int_max_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14921()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14920()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14897()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14896()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15117()).runTest("CWE190_Integer_Overflow__int_Property_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15116()).runTest("CWE190_Integer_Overflow__int_Property_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14637()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14636()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15091()).runTest("CWE190_Integer_Overflow__int_Property_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15090()).runTest("CWE190_Integer_Overflow__int_Property_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15049()).runTest("CWE190_Integer_Overflow__int_Property_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15048()).runTest("CWE190_Integer_Overflow__int_Property_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14793()).runTest("CWE190_Integer_Overflow__int_max_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14792()).runTest("CWE190_Integer_Overflow__int_max_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15065()).runTest("CWE190_Integer_Overflow__int_Property_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15064()).runTest("CWE190_Integer_Overflow__int_Property_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15177()).runTest("CWE190_Integer_Overflow__int_random_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15176()).runTest("CWE190_Integer_Overflow__int_random_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15167()).runTest("CWE190_Integer_Overflow__int_random_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15166()).runTest("CWE190_Integer_Overflow__int_random_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14913()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14912()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14693()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14692()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14745()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14744()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14675()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14674()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15259()).runTest("CWE190_Integer_Overflow__int_random_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15258()).runTest("CWE190_Integer_Overflow__int_random_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14979()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14978()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14837()).runTest("CWE190_Integer_Overflow__int_max_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14836()).runTest("CWE190_Integer_Overflow__int_max_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15235()).runTest("CWE190_Integer_Overflow__int_random_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15234()).runTest("CWE190_Integer_Overflow__int_random_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14627()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14626()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15099()).runTest("CWE190_Integer_Overflow__int_Property_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15098()).runTest("CWE190_Integer_Overflow__int_Property_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15143()).runTest("CWE190_Integer_Overflow__int_Property_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15142()).runTest("CWE190_Integer_Overflow__int_Property_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15133()).runTest("CWE190_Integer_Overflow__int_Property_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15132()).runTest("CWE190_Integer_Overflow__int_Property_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14987()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14986()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14871()).runTest("CWE190_Integer_Overflow__int_max_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14870()).runTest("CWE190_Integer_Overflow__int_max_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15205()).runTest("CWE190_Integer_Overflow__int_random_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15204()).runTest("CWE190_Integer_Overflow__int_random_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15199()).runTest("CWE190_Integer_Overflow__int_random_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15198()).runTest("CWE190_Integer_Overflow__int_random_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15201()).runTest("CWE190_Integer_Overflow__int_random_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15200()).runTest("CWE190_Integer_Overflow__int_random_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15115()).runTest("CWE190_Integer_Overflow__int_Property_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15114()).runTest("CWE190_Integer_Overflow__int_Property_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14965()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14964()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15059()).runTest("CWE190_Integer_Overflow__int_Property_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15058()).runTest("CWE190_Integer_Overflow__int_Property_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15209()).runTest("CWE190_Integer_Overflow__int_random_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15208()).runTest("CWE190_Integer_Overflow__int_random_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14915()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14914()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14839()).runTest("CWE190_Integer_Overflow__int_max_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14838()).runTest("CWE190_Integer_Overflow__int_max_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15261()).runTest("CWE190_Integer_Overflow__int_random_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15260()).runTest("CWE190_Integer_Overflow__int_random_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14761()).runTest("CWE190_Integer_Overflow__int_max_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14760()).runTest("CWE190_Integer_Overflow__int_max_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14623()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14622()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15047()).runTest("CWE190_Integer_Overflow__int_Property_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15046()).runTest("CWE190_Integer_Overflow__int_Property_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14949()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14948()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14739()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14738()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15229()).runTest("CWE190_Integer_Overflow__int_random_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15228()).runTest("CWE190_Integer_Overflow__int_random_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15001()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15000()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15003()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15002()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14673()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14672()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14765()).runTest("CWE190_Integer_Overflow__int_max_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14764()).runTest("CWE190_Integer_Overflow__int_max_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14671()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14670()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14817()).runTest("CWE190_Integer_Overflow__int_max_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14816()).runTest("CWE190_Integer_Overflow__int_max_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14869()).runTest("CWE190_Integer_Overflow__int_max_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14868()).runTest("CWE190_Integer_Overflow__int_max_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14663()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14662()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15187()).runTest("CWE190_Integer_Overflow__int_random_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15186()).runTest("CWE190_Integer_Overflow__int_random_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15253()).runTest("CWE190_Integer_Overflow__int_random_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15252()).runTest("CWE190_Integer_Overflow__int_random_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15063()).runTest("CWE190_Integer_Overflow__int_Property_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15062()).runTest("CWE190_Integer_Overflow__int_Property_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14819()).runTest("CWE190_Integer_Overflow__int_max_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14818()).runTest("CWE190_Integer_Overflow__int_max_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14853()).runTest("CWE190_Integer_Overflow__int_max_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14852()).runTest("CWE190_Integer_Overflow__int_max_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14713()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14712()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15079()).runTest("CWE190_Integer_Overflow__int_Property_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15078()).runTest("CWE190_Integer_Overflow__int_Property_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14639()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14638()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15249()).runTest("CWE190_Integer_Overflow__int_random_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15248()).runTest("CWE190_Integer_Overflow__int_random_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15123()).runTest("CWE190_Integer_Overflow__int_Property_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15122()).runTest("CWE190_Integer_Overflow__int_Property_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15255()).runTest("CWE190_Integer_Overflow__int_random_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15254()).runTest("CWE190_Integer_Overflow__int_random_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15109()).runTest("CWE190_Integer_Overflow__int_Property_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15108()).runTest("CWE190_Integer_Overflow__int_Property_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15165()).runTest("CWE190_Integer_Overflow__int_random_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15164()).runTest("CWE190_Integer_Overflow__int_random_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15097()).runTest("CWE190_Integer_Overflow__int_Property_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15096()).runTest("CWE190_Integer_Overflow__int_Property_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14689()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14688()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14835()).runTest("CWE190_Integer_Overflow__int_max_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14834()).runTest("CWE190_Integer_Overflow__int_max_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14813()).runTest("CWE190_Integer_Overflow__int_max_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14812()).runTest("CWE190_Integer_Overflow__int_max_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14789()).runTest("CWE190_Integer_Overflow__int_max_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14788()).runTest("CWE190_Integer_Overflow__int_max_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14779()).runTest("CWE190_Integer_Overflow__int_max_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14778()).runTest("CWE190_Integer_Overflow__int_max_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14999()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14998()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14643()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14642()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14763()).runTest("CWE190_Integer_Overflow__int_max_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14762()).runTest("CWE190_Integer_Overflow__int_max_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15083()).runTest("CWE190_Integer_Overflow__int_Property_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15082()).runTest("CWE190_Integer_Overflow__int_Property_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15195()).runTest("CWE190_Integer_Overflow__int_random_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15194()).runTest("CWE190_Integer_Overflow__int_random_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14875()).runTest("CWE190_Integer_Overflow__int_max_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14874()).runTest("CWE190_Integer_Overflow__int_max_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14687()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14686()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15231()).runTest("CWE190_Integer_Overflow__int_random_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15230()).runTest("CWE190_Integer_Overflow__int_random_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14879()).runTest("CWE190_Integer_Overflow__int_max_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14878()).runTest("CWE190_Integer_Overflow__int_max_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14815()).runTest("CWE190_Integer_Overflow__int_max_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14814()).runTest("CWE190_Integer_Overflow__int_max_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15223()).runTest("CWE190_Integer_Overflow__int_random_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15222()).runTest("CWE190_Integer_Overflow__int_random_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15121()).runTest("CWE190_Integer_Overflow__int_Property_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15120()).runTest("CWE190_Integer_Overflow__int_Property_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15013()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15012()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14887()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14886()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14841()).runTest("CWE190_Integer_Overflow__int_max_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14840()).runTest("CWE190_Integer_Overflow__int_max_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15275()).runTest("CWE190_Integer_Overflow__int_random_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15274()).runTest("CWE190_Integer_Overflow__int_random_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15069()).runTest("CWE190_Integer_Overflow__int_Property_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15068()).runTest("CWE190_Integer_Overflow__int_Property_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15139()).runTest("CWE190_Integer_Overflow__int_Property_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15138()).runTest("CWE190_Integer_Overflow__int_Property_square_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15189()).runTest("CWE190_Integer_Overflow__int_random_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15188()).runTest("CWE190_Integer_Overflow__int_random_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14873()).runTest("CWE190_Integer_Overflow__int_max_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14872()).runTest("CWE190_Integer_Overflow__int_max_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15227()).runTest("CWE190_Integer_Overflow__int_random_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15226()).runTest("CWE190_Integer_Overflow__int_random_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14665()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14664()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15247()).runTest("CWE190_Integer_Overflow__int_random_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15246()).runTest("CWE190_Integer_Overflow__int_random_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14773()).runTest("CWE190_Integer_Overflow__int_max_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14772()).runTest("CWE190_Integer_Overflow__int_max_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14787()).runTest("CWE190_Integer_Overflow__int_max_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14786()).runTest("CWE190_Integer_Overflow__int_max_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14857()).runTest("CWE190_Integer_Overflow__int_max_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14856()).runTest("CWE190_Integer_Overflow__int_max_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14811()).runTest("CWE190_Integer_Overflow__int_max_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14810()).runTest("CWE190_Integer_Overflow__int_max_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14983()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14982()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14807()).runTest("CWE190_Integer_Overflow__int_max_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14806()).runTest("CWE190_Integer_Overflow__int_max_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15257()).runTest("CWE190_Integer_Overflow__int_random_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15256()).runTest("CWE190_Integer_Overflow__int_random_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15045()).runTest("CWE190_Integer_Overflow__int_Property_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15044()).runTest("CWE190_Integer_Overflow__int_Property_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14719()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14718()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15161()).runTest("CWE190_Integer_Overflow__int_random_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15160()).runTest("CWE190_Integer_Overflow__int_random_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15037()).runTest("CWE190_Integer_Overflow__int_Property_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15036()).runTest("CWE190_Integer_Overflow__int_Property_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15035()).runTest("CWE190_Integer_Overflow__int_Property_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15034()).runTest("CWE190_Integer_Overflow__int_Property_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14699()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14698()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14867()).runTest("CWE190_Integer_Overflow__int_max_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14866()).runTest("CWE190_Integer_Overflow__int_max_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14805()).runTest("CWE190_Integer_Overflow__int_max_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14804()).runTest("CWE190_Integer_Overflow__int_max_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14955()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14954()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15031()).runTest("CWE190_Integer_Overflow__int_Property_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15030()).runTest("CWE190_Integer_Overflow__int_Property_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14825()).runTest("CWE190_Integer_Overflow__int_max_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14824()).runTest("CWE190_Integer_Overflow__int_max_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14631()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14630()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15107()).runTest("CWE190_Integer_Overflow__int_Property_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15106()).runTest("CWE190_Integer_Overflow__int_Property_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14947()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14946()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15033()).runTest("CWE190_Integer_Overflow__int_Property_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15032()).runTest("CWE190_Integer_Overflow__int_Property_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15087()).runTest("CWE190_Integer_Overflow__int_Property_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15086()).runTest("CWE190_Integer_Overflow__int_Property_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14911()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14910()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14691()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14690()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14977()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14976()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14861()).runTest("CWE190_Integer_Overflow__int_max_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14860()).runTest("CWE190_Integer_Overflow__int_max_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14919()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14918()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15021()).runTest("CWE190_Integer_Overflow__int_Property_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15020()).runTest("CWE190_Integer_Overflow__int_Property_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15183()).runTest("CWE190_Integer_Overflow__int_random_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15182()).runTest("CWE190_Integer_Overflow__int_random_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14993()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14992()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14823()).runTest("CWE190_Integer_Overflow__int_max_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14822()).runTest("CWE190_Integer_Overflow__int_max_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15131()).runTest("CWE190_Integer_Overflow__int_Property_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15130()).runTest("CWE190_Integer_Overflow__int_Property_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14785()).runTest("CWE190_Integer_Overflow__int_max_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14784()).runTest("CWE190_Integer_Overflow__int_max_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15023()).runTest("CWE190_Integer_Overflow__int_Property_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15022()).runTest("CWE190_Integer_Overflow__int_Property_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15113()).runTest("CWE190_Integer_Overflow__int_Property_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15112()).runTest("CWE190_Integer_Overflow__int_Property_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15157()).runTest("CWE190_Integer_Overflow__int_random_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15156()).runTest("CWE190_Integer_Overflow__int_random_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14709()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14708()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14985()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14984()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15017()).runTest("CWE190_Integer_Overflow__int_Property_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15016()).runTest("CWE190_Integer_Overflow__int_Property_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14901()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14900()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14991()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14990()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14945()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14944()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14733()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14732()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14723()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14722()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14701()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14700()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14645()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14644()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15135()).runTest("CWE190_Integer_Overflow__int_Property_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15134()).runTest("CWE190_Integer_Overflow__int_Property_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14799()).runTest("CWE190_Integer_Overflow__int_max_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14798()).runTest("CWE190_Integer_Overflow__int_max_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15093()).runTest("CWE190_Integer_Overflow__int_Property_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15092()).runTest("CWE190_Integer_Overflow__int_Property_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14647()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14646()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15101()).runTest("CWE190_Integer_Overflow__int_Property_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15100()).runTest("CWE190_Integer_Overflow__int_Property_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14753()).runTest("CWE190_Integer_Overflow__int_max_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14752()).runTest("CWE190_Integer_Overflow__int_max_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14731()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14730()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14895()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14894()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15233()).runTest("CWE190_Integer_Overflow__int_random_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15232()).runTest("CWE190_Integer_Overflow__int_random_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14969()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14968()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14961()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14960()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14941()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14940()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15175()).runTest("CWE190_Integer_Overflow__int_random_add_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15174()).runTest("CWE190_Integer_Overflow__int_random_add_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15039()).runTest("CWE190_Integer_Overflow__int_Property_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15038()).runTest("CWE190_Integer_Overflow__int_Property_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15215()).runTest("CWE190_Integer_Overflow__int_random_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15214()).runTest("CWE190_Integer_Overflow__int_random_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14655()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14654()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14695()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14694()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15073()).runTest("CWE190_Integer_Overflow__int_Property_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15072()).runTest("CWE190_Integer_Overflow__int_Property_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15067()).runTest("CWE190_Integer_Overflow__int_Property_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15066()).runTest("CWE190_Integer_Overflow__int_Property_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14769()).runTest("CWE190_Integer_Overflow__int_max_add_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14768()).runTest("CWE190_Integer_Overflow__int_max_add_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14783()).runTest("CWE190_Integer_Overflow__int_max_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14782()).runTest("CWE190_Integer_Overflow__int_max_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14747()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14746()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14621()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14620()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14677()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14676()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15011()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15010()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15105()).runTest("CWE190_Integer_Overflow__int_Property_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15104()).runTest("CWE190_Integer_Overflow__int_Property_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14939()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14938()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15029()).runTest("CWE190_Integer_Overflow__int_Property_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15028()).runTest("CWE190_Integer_Overflow__int_Property_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15137()).runTest("CWE190_Integer_Overflow__int_Property_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15136()).runTest("CWE190_Integer_Overflow__int_Property_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14679()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14678()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14751()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14750()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14775()).runTest("CWE190_Integer_Overflow__int_max_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14774()).runTest("CWE190_Integer_Overflow__int_max_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15263()).runTest("CWE190_Integer_Overflow__int_random_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15262()).runTest("CWE190_Integer_Overflow__int_random_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14803()).runTest("CWE190_Integer_Overflow__int_max_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14802()).runTest("CWE190_Integer_Overflow__int_max_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14967()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14966()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15149()).runTest("CWE190_Integer_Overflow__int_random_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15148()).runTest("CWE190_Integer_Overflow__int_random_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14683()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14682()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15279()).runTest("CWE190_Integer_Overflow__int_random_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15278()).runTest("CWE190_Integer_Overflow__int_random_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14659()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14658()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14829()).runTest("CWE190_Integer_Overflow__int_max_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14828()).runTest("CWE190_Integer_Overflow__int_max_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14973()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14972()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15027()).runTest("CWE190_Integer_Overflow__int_Property_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15026()).runTest("CWE190_Integer_Overflow__int_Property_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14975()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14974()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14905()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14904()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14661()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14660()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14937()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14936()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14685()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14684()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14755()).runTest("CWE190_Integer_Overflow__int_max_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14754()).runTest("CWE190_Integer_Overflow__int_max_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15095()).runTest("CWE190_Integer_Overflow__int_Property_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15094()).runTest("CWE190_Integer_Overflow__int_Property_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14859()).runTest("CWE190_Integer_Overflow__int_max_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14858()).runTest("CWE190_Integer_Overflow__int_max_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14899()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14898()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15219()).runTest("CWE190_Integer_Overflow__int_random_multiply_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15218()).runTest("CWE190_Integer_Overflow__int_random_multiply_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15237()).runTest("CWE190_Integer_Overflow__int_random_square_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15236()).runTest("CWE190_Integer_Overflow__int_random_square_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14727()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14726()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15077()).runTest("CWE190_Integer_Overflow__int_Property_multiply_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15076()).runTest("CWE190_Integer_Overflow__int_Property_multiply_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15071()).runTest("CWE190_Integer_Overflow__int_Property_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15070()).runTest("CWE190_Integer_Overflow__int_Property_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15267()).runTest("CWE190_Integer_Overflow__int_random_square_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15266()).runTest("CWE190_Integer_Overflow__int_random_square_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14771()).runTest("CWE190_Integer_Overflow__int_max_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14770()).runTest("CWE190_Integer_Overflow__int_max_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14777()).runTest("CWE190_Integer_Overflow__int_max_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14776()).runTest("CWE190_Integer_Overflow__int_max_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14963()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14962()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14891()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14890()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15225()).runTest("CWE190_Integer_Overflow__int_random_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15224()).runTest("CWE190_Integer_Overflow__int_random_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15273()).runTest("CWE190_Integer_Overflow__int_random_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15272()).runTest("CWE190_Integer_Overflow__int_random_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14649()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14648()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15081()).runTest("CWE190_Integer_Overflow__int_Property_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15080()).runTest("CWE190_Integer_Overflow__int_Property_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14907()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14906()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15245()).runTest("CWE190_Integer_Overflow__int_random_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15244()).runTest("CWE190_Integer_Overflow__int_random_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15197()).runTest("CWE190_Integer_Overflow__int_random_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15196()).runTest("CWE190_Integer_Overflow__int_random_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15015()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15014()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15057()).runTest("CWE190_Integer_Overflow__int_Property_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15056()).runTest("CWE190_Integer_Overflow__int_Property_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15163()).runTest("CWE190_Integer_Overflow__int_random_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15162()).runTest("CWE190_Integer_Overflow__int_random_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14669()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14668()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14781()).runTest("CWE190_Integer_Overflow__int_max_add_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14780()).runTest("CWE190_Integer_Overflow__int_max_add_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15145()).runTest("CWE190_Integer_Overflow__int_Property_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15144()).runTest("CWE190_Integer_Overflow__int_Property_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15129()).runTest("CWE190_Integer_Overflow__int_Property_square_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15128()).runTest("CWE190_Integer_Overflow__int_Property_square_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14931()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14930()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15243()).runTest("CWE190_Integer_Overflow__int_random_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15242()).runTest("CWE190_Integer_Overflow__int_random_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14953()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14952()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14933()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14932()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15089()).runTest("CWE190_Integer_Overflow__int_Property_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15088()).runTest("CWE190_Integer_Overflow__int_Property_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15191()).runTest("CWE190_Integer_Overflow__int_random_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15190()).runTest("CWE190_Integer_Overflow__int_random_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14697()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14696()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14847()).runTest("CWE190_Integer_Overflow__int_max_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14846()).runTest("CWE190_Integer_Overflow__int_max_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15153()).runTest("CWE190_Integer_Overflow__int_random_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15152()).runTest("CWE190_Integer_Overflow__int_random_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14717()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14716()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15085()).runTest("CWE190_Integer_Overflow__int_Property_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15084()).runTest("CWE190_Integer_Overflow__int_Property_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15179()).runTest("CWE190_Integer_Overflow__int_random_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15178()).runTest("CWE190_Integer_Overflow__int_random_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14635()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14634()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15239()).runTest("CWE190_Integer_Overflow__int_random_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15238()).runTest("CWE190_Integer_Overflow__int_random_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14989()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14988()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14935()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14934()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14849()).runTest("CWE190_Integer_Overflow__int_max_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14848()).runTest("CWE190_Integer_Overflow__int_max_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14929()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14928()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15265()).runTest("CWE190_Integer_Overflow__int_random_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15264()).runTest("CWE190_Integer_Overflow__int_random_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15005()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15004()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14741()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14740()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15217()).runTest("CWE190_Integer_Overflow__int_random_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15216()).runTest("CWE190_Integer_Overflow__int_random_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14863()).runTest("CWE190_Integer_Overflow__int_max_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14862()).runTest("CWE190_Integer_Overflow__int_max_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14737()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14736()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14633()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14632()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15155()).runTest("CWE190_Integer_Overflow__int_random_add_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15154()).runTest("CWE190_Integer_Overflow__int_random_add_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15055()).runTest("CWE190_Integer_Overflow__int_Property_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15054()).runTest("CWE190_Integer_Overflow__int_Property_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15141()).runTest("CWE190_Integer_Overflow__int_Property_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15140()).runTest("CWE190_Integer_Overflow__int_Property_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15159()).runTest("CWE190_Integer_Overflow__int_random_add_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15158()).runTest("CWE190_Integer_Overflow__int_random_add_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15169()).runTest("CWE190_Integer_Overflow__int_random_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15168()).runTest("CWE190_Integer_Overflow__int_random_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15221()).runTest("CWE190_Integer_Overflow__int_random_multiply_15_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15220()).runTest("CWE190_Integer_Overflow__int_random_multiply_15_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14705()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14704()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15251()).runTest("CWE190_Integer_Overflow__int_random_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15250()).runTest("CWE190_Integer_Overflow__int_random_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15193()).runTest("CWE190_Integer_Overflow__int_random_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15192()).runTest("CWE190_Integer_Overflow__int_random_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15151()).runTest("CWE190_Integer_Overflow__int_random_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15150()).runTest("CWE190_Integer_Overflow__int_random_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14651()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_16_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14650()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_16_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14735()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_14_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14734()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_14_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14641()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14640()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14981()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14980()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15213()).runTest("CWE190_Integer_Overflow__int_random_multiply_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15212()).runTest("CWE190_Integer_Overflow__int_random_multiply_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14795()).runTest("CWE190_Integer_Overflow__int_max_add_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14794()).runTest("CWE190_Integer_Overflow__int_max_add_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14707()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14706()).runTest("CWE190_Integer_Overflow__int_listen_tcp_multiply_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14995()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14994()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15203()).runTest("CWE190_Integer_Overflow__int_random_multiply_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15202()).runTest("CWE190_Integer_Overflow__int_random_multiply_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14797()).runTest("CWE190_Integer_Overflow__int_max_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14796()).runTest("CWE190_Integer_Overflow__int_max_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15171()).runTest("CWE190_Integer_Overflow__int_random_add_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15170()).runTest("CWE190_Integer_Overflow__int_random_add_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14721()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_07_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14720()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_07_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14725()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_09_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14724()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_09_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15051()).runTest("CWE190_Integer_Overflow__int_Property_add_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15050()).runTest("CWE190_Integer_Overflow__int_Property_add_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15119()).runTest("CWE190_Integer_Overflow__int_Property_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15118()).runTest("CWE190_Integer_Overflow__int_Property_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14767()).runTest("CWE190_Integer_Overflow__int_max_add_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14766()).runTest("CWE190_Integer_Overflow__int_max_add_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14923()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14922()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15125()).runTest("CWE190_Integer_Overflow__int_Property_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15124()).runTest("CWE190_Integer_Overflow__int_Property_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14951()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_12_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14950()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_12_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15147()).runTest("CWE190_Integer_Overflow__int_Property_square_45_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15146()).runTest("CWE190_Integer_Overflow__int_Property_square_45_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14877()).runTest("CWE190_Integer_Overflow__int_max_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14876()).runTest("CWE190_Integer_Overflow__int_max_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15009()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15008()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_square_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15025()).runTest("CWE190_Integer_Overflow__int_Property_add_05_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15024()).runTest("CWE190_Integer_Overflow__int_Property_add_05_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15061()).runTest("CWE190_Integer_Overflow__int_Property_multiply_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15060()).runTest("CWE190_Integer_Overflow__int_Property_multiply_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14821()).runTest("CWE190_Integer_Overflow__int_max_multiply_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14820()).runTest("CWE190_Integer_Overflow__int_max_multiply_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14903()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_10_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14902()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_10_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15111()).runTest("CWE190_Integer_Overflow__int_Property_square_04_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15110()).runTest("CWE190_Integer_Overflow__int_Property_square_04_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14943()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14942()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15277()).runTest("CWE190_Integer_Overflow__int_random_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15276()).runTest("CWE190_Integer_Overflow__int_random_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14729()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_11_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14728()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_11_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14845()).runTest("CWE190_Integer_Overflow__int_max_square_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14844()).runTest("CWE190_Integer_Overflow__int_max_square_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14925()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14924()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14749()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_42_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14748()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_42_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15041()).runTest("CWE190_Integer_Overflow__int_Property_add_13_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15040()).runTest("CWE190_Integer_Overflow__int_Property_add_13_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14855()).runTest("CWE190_Integer_Overflow__int_max_square_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14854()).runTest("CWE190_Integer_Overflow__int_max_square_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14791()).runTest("CWE190_Integer_Overflow__int_max_add_41_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14790()).runTest("CWE190_Integer_Overflow__int_max_add_41_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14889()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14888()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14657()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14656()).runTest("CWE190_Integer_Overflow__int_listen_tcp_add_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14917()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14916()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14711()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14710()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14833()).runTest("CWE190_Integer_Overflow__int_max_multiply_31_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14832()).runTest("CWE190_Integer_Overflow__int_max_multiply_31_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15019()).runTest("CWE190_Integer_Overflow__int_Property_add_02_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15018()).runTest("CWE190_Integer_Overflow__int_Property_add_02_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14885()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_01_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14884()).runTest("CWE190_Integer_Overflow__int_PropertiesFile_add_01_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15207()).runTest("CWE190_Integer_Overflow__int_random_multiply_08_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15206()).runTest("CWE190_Integer_Overflow__int_random_multiply_08_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14801()).runTest("CWE190_Integer_Overflow__int_max_multiply_03_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14800()).runTest("CWE190_Integer_Overflow__int_max_multiply_03_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14831()).runTest("CWE190_Integer_Overflow__int_max_multiply_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14830()).runTest("CWE190_Integer_Overflow__int_max_multiply_21_b");
        (new testcases.CWE190_Integer_Overflow.s03.J15181()).runTest("CWE190_Integer_Overflow__int_random_add_17_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J15180()).runTest("CWE190_Integer_Overflow__int_random_add_17_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14851()).runTest("CWE190_Integer_Overflow__int_max_square_06_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14850()).runTest("CWE190_Integer_Overflow__int_max_square_06_b");
        (new testcases.CWE190_Integer_Overflow.s03.J14743()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_21_gd");
        (new testcases.CWE190_Integer_Overflow.s03.J14742()).runTest("CWE190_Integer_Overflow__int_listen_tcp_square_21_b");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
