package testcases.CWE36_Absolute_Path_Traversal;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */
        (new testcases.CWE36_Absolute_Path_Traversal.J19001()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_13_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19000()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_13_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19401()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_15_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19400()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_15_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19375()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_02_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19374()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_02_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J18995()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_10_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J18994()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_10_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19501()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_42_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19500()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_42_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19383()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_06_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19382()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_06_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19043()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_12_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19042()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_12_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19157()).runTest("CWE36_Absolute_Path_Traversal__File_03_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19156()).runTest("CWE36_Absolute_Path_Traversal__File_03_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19345()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_09_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19344()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_09_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19025()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_03_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19024()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_03_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19347()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_10_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19346()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_10_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19123()).runTest("CWE36_Absolute_Path_Traversal__Environment_08_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19122()).runTest("CWE36_Absolute_Path_Traversal__Environment_08_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19355()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_14_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19354()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_14_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19409()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_31_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19408()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_31_b");
        (new testcases.CWE36_Absolute_Path_Traversal.J19109()).runTest("CWE36_Absolute_Path_Traversal__Environment_01_gd");
        (new testcases.CWE36_Absolute_Path_Traversal.J19108()).runTest("CWE36_Absolute_Path_Traversal__Environment_01_b");
        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
