package testcases.CWE36_Absolute_Path_Traversal;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */
        (new testcases.CWE36_Absolute_Path_Traversal.J19391()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19390()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19035()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19034()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19087()).runTest("CWE36_Absolute_Path_Traversal__database_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19086()).runTest("CWE36_Absolute_Path_Traversal__database_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19081()).runTest("CWE36_Absolute_Path_Traversal__database_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19080()).runTest("CWE36_Absolute_Path_Traversal__database_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19051()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19050()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19149()).runTest("CWE36_Absolute_Path_Traversal__Environment_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19148()).runTest("CWE36_Absolute_Path_Traversal__Environment_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19153()).runTest("CWE36_Absolute_Path_Traversal__File_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19152()).runTest("CWE36_Absolute_Path_Traversal__File_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19093()).runTest("CWE36_Absolute_Path_Traversal__database_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19092()).runTest("CWE36_Absolute_Path_Traversal__database_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19065()).runTest("CWE36_Absolute_Path_Traversal__database_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19064()).runTest("CWE36_Absolute_Path_Traversal__database_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19331()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19330()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19411()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19410()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19423()).runTest("CWE36_Absolute_Path_Traversal__Property_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19422()).runTest("CWE36_Absolute_Path_Traversal__Property_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19021()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19020()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19357()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19356()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19433()).runTest("CWE36_Absolute_Path_Traversal__Property_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19432()).runTest("CWE36_Absolute_Path_Traversal__Property_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19147()).runTest("CWE36_Absolute_Path_Traversal__Environment_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19146()).runTest("CWE36_Absolute_Path_Traversal__Environment_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19099()).runTest("CWE36_Absolute_Path_Traversal__database_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19098()).runTest("CWE36_Absolute_Path_Traversal__database_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19373()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19372()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19329()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19328()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19059()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19058()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19343()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19342()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19479()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19478()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19351()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19350()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18977()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18976()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19493()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19492()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19173()).runTest("CWE36_Absolute_Path_Traversal__File_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19172()).runTest("CWE36_Absolute_Path_Traversal__File_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19103()).runTest("CWE36_Absolute_Path_Traversal__database_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19102()).runTest("CWE36_Absolute_Path_Traversal__database_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19111()).runTest("CWE36_Absolute_Path_Traversal__Environment_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19110()).runTest("CWE36_Absolute_Path_Traversal__Environment_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19359()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19358()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19467()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19466()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19005()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19004()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19481()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19480()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19011()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19010()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19001()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19000()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19073()).runTest("CWE36_Absolute_Path_Traversal__database_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19072()).runTest("CWE36_Absolute_Path_Traversal__database_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19165()).runTest("CWE36_Absolute_Path_Traversal__File_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19164()).runTest("CWE36_Absolute_Path_Traversal__File_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19007()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19006()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19401()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19400()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19449()).runTest("CWE36_Absolute_Path_Traversal__Property_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19448()).runTest("CWE36_Absolute_Path_Traversal__Property_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19187()).runTest("CWE36_Absolute_Path_Traversal__File_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19186()).runTest("CWE36_Absolute_Path_Traversal__File_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19003()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19002()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19053()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19052()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19485()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19484()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19031()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19030()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19429()).runTest("CWE36_Absolute_Path_Traversal__Property_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19428()).runTest("CWE36_Absolute_Path_Traversal__Property_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19413()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19412()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19375()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19374()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19041()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19040()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19139()).runTest("CWE36_Absolute_Path_Traversal__Environment_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19138()).runTest("CWE36_Absolute_Path_Traversal__Environment_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19185()).runTest("CWE36_Absolute_Path_Traversal__File_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19184()).runTest("CWE36_Absolute_Path_Traversal__File_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19105()).runTest("CWE36_Absolute_Path_Traversal__database_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19104()).runTest("CWE36_Absolute_Path_Traversal__database_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19017()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19016()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19419()).runTest("CWE36_Absolute_Path_Traversal__Property_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19418()).runTest("CWE36_Absolute_Path_Traversal__Property_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19439()).runTest("CWE36_Absolute_Path_Traversal__Property_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19438()).runTest("CWE36_Absolute_Path_Traversal__Property_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19333()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19332()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19483()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19482()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19175()).runTest("CWE36_Absolute_Path_Traversal__File_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19174()).runTest("CWE36_Absolute_Path_Traversal__File_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19137()).runTest("CWE36_Absolute_Path_Traversal__Environment_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19136()).runTest("CWE36_Absolute_Path_Traversal__Environment_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19495()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19494()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19475()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19474()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19169()).runTest("CWE36_Absolute_Path_Traversal__File_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19168()).runTest("CWE36_Absolute_Path_Traversal__File_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18993()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18992()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18995()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18994()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19079()).runTest("CWE36_Absolute_Path_Traversal__database_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19078()).runTest("CWE36_Absolute_Path_Traversal__database_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19403()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19402()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19009()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19008()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19015()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19014()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19107()).runTest("CWE36_Absolute_Path_Traversal__database_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19106()).runTest("CWE36_Absolute_Path_Traversal__database_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19417()).runTest("CWE36_Absolute_Path_Traversal__Property_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19416()).runTest("CWE36_Absolute_Path_Traversal__Property_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19337()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19336()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19183()).runTest("CWE36_Absolute_Path_Traversal__File_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19182()).runTest("CWE36_Absolute_Path_Traversal__File_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19381()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19380()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19421()).runTest("CWE36_Absolute_Path_Traversal__Property_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19420()).runTest("CWE36_Absolute_Path_Traversal__Property_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19095()).runTest("CWE36_Absolute_Path_Traversal__database_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19094()).runTest("CWE36_Absolute_Path_Traversal__database_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19143()).runTest("CWE36_Absolute_Path_Traversal__Environment_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19142()).runTest("CWE36_Absolute_Path_Traversal__Environment_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19501()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19500()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19457()).runTest("CWE36_Absolute_Path_Traversal__Property_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19456()).runTest("CWE36_Absolute_Path_Traversal__Property_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19141()).runTest("CWE36_Absolute_Path_Traversal__Environment_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19140()).runTest("CWE36_Absolute_Path_Traversal__Environment_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19159()).runTest("CWE36_Absolute_Path_Traversal__File_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19158()).runTest("CWE36_Absolute_Path_Traversal__File_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19451()).runTest("CWE36_Absolute_Path_Traversal__Property_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19450()).runTest("CWE36_Absolute_Path_Traversal__Property_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19397()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19396()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19083()).runTest("CWE36_Absolute_Path_Traversal__database_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19082()).runTest("CWE36_Absolute_Path_Traversal__database_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19027()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19026()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19383()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19382()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19471()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19470()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19335()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19334()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19121()).runTest("CWE36_Absolute_Path_Traversal__Environment_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19120()).runTest("CWE36_Absolute_Path_Traversal__Environment_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19043()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19042()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19075()).runTest("CWE36_Absolute_Path_Traversal__database_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19074()).runTest("CWE36_Absolute_Path_Traversal__database_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19365()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19364()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19377()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19376()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19459()).runTest("CWE36_Absolute_Path_Traversal__Property_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19458()).runTest("CWE36_Absolute_Path_Traversal__Property_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19049()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19048()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19157()).runTest("CWE36_Absolute_Path_Traversal__File_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19156()).runTest("CWE36_Absolute_Path_Traversal__File_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18997()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18996()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19155()).runTest("CWE36_Absolute_Path_Traversal__File_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19154()).runTest("CWE36_Absolute_Path_Traversal__File_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19171()).runTest("CWE36_Absolute_Path_Traversal__File_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19170()).runTest("CWE36_Absolute_Path_Traversal__File_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19125()).runTest("CWE36_Absolute_Path_Traversal__Environment_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19124()).runTest("CWE36_Absolute_Path_Traversal__Environment_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19443()).runTest("CWE36_Absolute_Path_Traversal__Property_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19442()).runTest("CWE36_Absolute_Path_Traversal__Property_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19181()).runTest("CWE36_Absolute_Path_Traversal__File_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19180()).runTest("CWE36_Absolute_Path_Traversal__File_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19345()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19344()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19047()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19046()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19097()).runTest("CWE36_Absolute_Path_Traversal__database_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19096()).runTest("CWE36_Absolute_Path_Traversal__database_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18981()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18980()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19427()).runTest("CWE36_Absolute_Path_Traversal__Property_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19426()).runTest("CWE36_Absolute_Path_Traversal__Property_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19019()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19018()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19445()).runTest("CWE36_Absolute_Path_Traversal__Property_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19444()).runTest("CWE36_Absolute_Path_Traversal__Property_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19029()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19028()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19071()).runTest("CWE36_Absolute_Path_Traversal__database_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19070()).runTest("CWE36_Absolute_Path_Traversal__database_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19349()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19348()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19477()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19476()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19131()).runTest("CWE36_Absolute_Path_Traversal__Environment_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19130()).runTest("CWE36_Absolute_Path_Traversal__Environment_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19393()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19392()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19101()).runTest("CWE36_Absolute_Path_Traversal__database_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19100()).runTest("CWE36_Absolute_Path_Traversal__database_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19191()).runTest("CWE36_Absolute_Path_Traversal__File_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19190()).runTest("CWE36_Absolute_Path_Traversal__File_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19189()).runTest("CWE36_Absolute_Path_Traversal__File_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19188()).runTest("CWE36_Absolute_Path_Traversal__File_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18999()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18998()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19461()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19460()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19399()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19398()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19133()).runTest("CWE36_Absolute_Path_Traversal__Environment_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19132()).runTest("CWE36_Absolute_Path_Traversal__Environment_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19379()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19378()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19371()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19370()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19025()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19024()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19077()).runTest("CWE36_Absolute_Path_Traversal__database_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19076()).runTest("CWE36_Absolute_Path_Traversal__database_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19367()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19366()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19055()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19054()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19161()).runTest("CWE36_Absolute_Path_Traversal__File_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19160()).runTest("CWE36_Absolute_Path_Traversal__File_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19119()).runTest("CWE36_Absolute_Path_Traversal__Environment_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19118()).runTest("CWE36_Absolute_Path_Traversal__Environment_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19465()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19464()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19473()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19472()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19347()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19346()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19177()).runTest("CWE36_Absolute_Path_Traversal__File_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19176()).runTest("CWE36_Absolute_Path_Traversal__File_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19145()).runTest("CWE36_Absolute_Path_Traversal__Environment_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19144()).runTest("CWE36_Absolute_Path_Traversal__Environment_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19057()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19056()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19497()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19496()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19469()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19468()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19405()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19404()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_17_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19415()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19414()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19441()).runTest("CWE36_Absolute_Path_Traversal__Property_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19440()).runTest("CWE36_Absolute_Path_Traversal__Property_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19135()).runTest("CWE36_Absolute_Path_Traversal__Environment_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19134()).runTest("CWE36_Absolute_Path_Traversal__Environment_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19369()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19368()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19127()).runTest("CWE36_Absolute_Path_Traversal__Environment_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19126()).runTest("CWE36_Absolute_Path_Traversal__Environment_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19447()).runTest("CWE36_Absolute_Path_Traversal__Property_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19446()).runTest("CWE36_Absolute_Path_Traversal__Property_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18983()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18982()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19045()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19044()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19395()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_12_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19394()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_12_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18991()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18990()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19067()).runTest("CWE36_Absolute_Path_Traversal__database_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19066()).runTest("CWE36_Absolute_Path_Traversal__database_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19151()).runTest("CWE36_Absolute_Path_Traversal__Environment_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19150()).runTest("CWE36_Absolute_Path_Traversal__Environment_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19503()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19502()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19063()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19062()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19489()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_15_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19488()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_15_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18989()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18988()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19499()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19498()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19435()).runTest("CWE36_Absolute_Path_Traversal__Property_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19434()).runTest("CWE36_Absolute_Path_Traversal__Property_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19389()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19388()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19163()).runTest("CWE36_Absolute_Path_Traversal__File_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19162()).runTest("CWE36_Absolute_Path_Traversal__File_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19353()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19352()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19117()).runTest("CWE36_Absolute_Path_Traversal__Environment_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19116()).runTest("CWE36_Absolute_Path_Traversal__Environment_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19033()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19032()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18987()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18986()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19385()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19384()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19023()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19022()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19089()).runTest("CWE36_Absolute_Path_Traversal__database_13_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19088()).runTest("CWE36_Absolute_Path_Traversal__database_13_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19463()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19462()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19487()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19486()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19037()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_09_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19036()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_09_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19341()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_07_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19340()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_07_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19339()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_06_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19338()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_06_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19179()).runTest("CWE36_Absolute_Path_Traversal__File_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19178()).runTest("CWE36_Absolute_Path_Traversal__File_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19129()).runTest("CWE36_Absolute_Path_Traversal__Environment_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19128()).runTest("CWE36_Absolute_Path_Traversal__Environment_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19193()).runTest("CWE36_Absolute_Path_Traversal__File_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19192()).runTest("CWE36_Absolute_Path_Traversal__File_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19431()).runTest("CWE36_Absolute_Path_Traversal__Property_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19430()).runTest("CWE36_Absolute_Path_Traversal__Property_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19113()).runTest("CWE36_Absolute_Path_Traversal__Environment_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19112()).runTest("CWE36_Absolute_Path_Traversal__Environment_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19039()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_10_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19038()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_10_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19425()).runTest("CWE36_Absolute_Path_Traversal__Property_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19424()).runTest("CWE36_Absolute_Path_Traversal__Property_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19123()).runTest("CWE36_Absolute_Path_Traversal__Environment_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19122()).runTest("CWE36_Absolute_Path_Traversal__Environment_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19491()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_16_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19490()).runTest("CWE36_Absolute_Path_Traversal__URLConnection_16_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19091()).runTest("CWE36_Absolute_Path_Traversal__database_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19090()).runTest("CWE36_Absolute_Path_Traversal__database_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19355()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_14_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19354()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_14_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19013()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19012()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18985()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_05_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18984()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_05_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J18979()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_02_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J18978()).runTest("CWE36_Absolute_Path_Traversal__connect_tcp_02_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19453()).runTest("CWE36_Absolute_Path_Traversal__Property_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19452()).runTest("CWE36_Absolute_Path_Traversal__Property_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19409()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_31_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19408()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_31_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19387()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19386()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19061()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_42_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19060()).runTest("CWE36_Absolute_Path_Traversal__console_readLine_42_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19195()).runTest("CWE36_Absolute_Path_Traversal__File_45_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19194()).runTest("CWE36_Absolute_Path_Traversal__File_45_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19167()).runTest("CWE36_Absolute_Path_Traversal__File_08_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19166()).runTest("CWE36_Absolute_Path_Traversal__File_08_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19069()).runTest("CWE36_Absolute_Path_Traversal__database_03_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19068()).runTest("CWE36_Absolute_Path_Traversal__database_03_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19363()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19362()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19085()).runTest("CWE36_Absolute_Path_Traversal__database_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19084()).runTest("CWE36_Absolute_Path_Traversal__database_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19455()).runTest("CWE36_Absolute_Path_Traversal__Property_41_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19454()).runTest("CWE36_Absolute_Path_Traversal__Property_41_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19437()).runTest("CWE36_Absolute_Path_Traversal__Property_11_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19436()).runTest("CWE36_Absolute_Path_Traversal__Property_11_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19109()).runTest("CWE36_Absolute_Path_Traversal__Environment_01_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19108()).runTest("CWE36_Absolute_Path_Traversal__Environment_01_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19115()).runTest("CWE36_Absolute_Path_Traversal__Environment_04_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19114()).runTest("CWE36_Absolute_Path_Traversal__Environment_04_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19407()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_21_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19406()).runTest("CWE36_Absolute_Path_Traversal__PropertiesFile_21_bad");
        (new testcases.CWE36_Absolute_Path_Traversal.J19361()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_17_good");
        (new testcases.CWE36_Absolute_Path_Traversal.J19360()).runTest("CWE36_Absolute_Path_Traversal__listen_tcp_17_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
