package testcases.CWE129_Improper_Validation_of_Array_Index.s04;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1127()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1126()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1117()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1116()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1125()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1124()).runTest("CWE129_Improper_Validation_of_Array_Index__random_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1111()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_size_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1110()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_size_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1105()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1104()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1113()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1112()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1115()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1114()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1121()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_size_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1120()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_size_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1119()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1118()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1099()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1098()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_read_check_max_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1101()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1100()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1107()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1106()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_check_min_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1123()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1122()).runTest("CWE129_Improper_Validation_of_Array_Index__Property_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1109()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1108()).runTest("CWE129_Improper_Validation_of_Array_Index__PropertiesFile_array_read_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1103()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1102()).runTest("CWE129_Improper_Validation_of_Array_Index__negative_fixed_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1097()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_write_no_check_01");
        (new testcases.CWE129_Improper_Validation_of_Array_Index.s04.J1096()).runTest("CWE129_Improper_Validation_of_Array_Index__listen_tcp_array_write_no_check_01");
        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
