package testcases.CWE259_Hard_Coded_Password;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_31_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_31_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_31_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_17_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_17_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_17_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_02_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_02_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_02_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_04_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_04_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_04_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_01_good()).runTest("CWE259_Hard_Coded_Password__driverManager_01_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_01_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_07_good()).runTest("CWE259_Hard_Coded_Password__driverManager_07_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_07_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_21_good()).runTest("CWE259_Hard_Coded_Password__driverManager_21_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_21_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_01_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_01_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_01_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_41_good()).runTest("CWE259_Hard_Coded_Password__driverManager_41_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_41_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_17_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_17_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_17_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_05_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_05_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_05_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_15_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_15_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_15_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_13_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_13_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_13_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_45_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_45_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_45_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_10_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_10_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_10_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_03_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_03_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_03_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_01_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_01_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_01_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_02_good()).runTest("CWE259_Hard_Coded_Password__driverManager_02_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_02_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_15_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_15_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_15_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_08_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_08_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_08_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_42_good()).runTest("CWE259_Hard_Coded_Password__driverManager_42_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_42_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_42_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_11_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_11_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_11_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_12_good()).runTest("CWE259_Hard_Coded_Password__driverManager_12_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_12_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_10_good()).runTest("CWE259_Hard_Coded_Password__driverManager_10_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_10_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_05_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_05_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_05_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_21_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_21_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_21_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_08_good()).runTest("CWE259_Hard_Coded_Password__driverManager_08_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_08_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_04_good()).runTest("CWE259_Hard_Coded_Password__driverManager_04_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_04_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_31_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_31_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_31_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_05_good()).runTest("CWE259_Hard_Coded_Password__driverManager_05_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_05_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_17_good()).runTest("CWE259_Hard_Coded_Password__driverManager_17_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_17_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_07_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_07_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_07_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_16_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_16_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_16_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_02_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_02_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_02_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_41_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_41_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_41_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_03_good()).runTest("CWE259_Hard_Coded_Password__driverManager_03_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_03_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_15_good()).runTest("CWE259_Hard_Coded_Password__driverManager_15_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_15_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_06_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_06_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_06_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_12_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_12_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_12_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_21_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_21_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_21_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_04_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_04_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_04_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_14_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_14_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_14_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_07_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_07_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_07_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_42_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_42_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_42_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_42_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_14_good()).runTest("CWE259_Hard_Coded_Password__driverManager_14_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_14_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_09_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_09_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_09_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_14_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_14_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_14_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_12_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_12_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_12_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_11_good()).runTest("CWE259_Hard_Coded_Password__driverManager_11_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_11_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_09_good()).runTest("CWE259_Hard_Coded_Password__driverManager_09_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_09_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_16_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_16_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_16_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_10_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_10_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_10_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_41_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_41_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_41_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_08_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_08_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_08_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_13_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_13_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_13_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_45_good()).runTest("CWE259_Hard_Coded_Password__driverManager_45_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_45_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_13_good()).runTest("CWE259_Hard_Coded_Password__driverManager_13_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_13_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_31_good()).runTest("CWE259_Hard_Coded_Password__driverManager_31_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_31_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_06_good()).runTest("CWE259_Hard_Coded_Password__driverManager_06_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_06_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_09_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_09_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_09_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_16_good()).runTest("CWE259_Hard_Coded_Password__driverManager_16_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__driverManager_16_bad()).runTest("CWE259_Hard_Coded_Password__driverManager_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_03_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_03_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_03_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_06_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_06_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_06_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_11_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_11_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_11_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_45_good()).runTest("CWE259_Hard_Coded_Password__passwordAuth_45_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__passwordAuth_45_bad()).runTest("CWE259_Hard_Coded_Password__passwordAuth_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_42_good()).runTest("CWE259_Hard_Coded_Password__kerberosKey_42_good");
        (new testcases.CWE259_Hard_Coded_Password.CWE259_Hard_Coded_Password__kerberosKey_42_bad()).runTest("CWE259_Hard_Coded_Password__kerberosKey_42_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
