package testcases.CWE259_Hard_Coded_Password;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */
        (new testcases.CWE259_Hard_Coded_Password.J18925()).runTest("CWE259_Hard_Coded_Password__passwordAuth_31_good");
        (new testcases.CWE259_Hard_Coded_Password.J18924()).runTest("CWE259_Hard_Coded_Password__passwordAuth_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18877()).runTest("CWE259_Hard_Coded_Password__kerberosKey_17_good");
        (new testcases.CWE259_Hard_Coded_Password.J18876()).runTest("CWE259_Hard_Coded_Password__kerberosKey_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18847()).runTest("CWE259_Hard_Coded_Password__kerberosKey_02_good");
        (new testcases.CWE259_Hard_Coded_Password.J18846()).runTest("CWE259_Hard_Coded_Password__kerberosKey_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18851()).runTest("CWE259_Hard_Coded_Password__kerberosKey_04_good");
        (new testcases.CWE259_Hard_Coded_Password.J18850()).runTest("CWE259_Hard_Coded_Password__kerberosKey_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18801()).runTest("CWE259_Hard_Coded_Password__driverManager_01_good");
        (new testcases.CWE259_Hard_Coded_Password.J18800()).runTest("CWE259_Hard_Coded_Password__driverManager_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18813()).runTest("CWE259_Hard_Coded_Password__driverManager_07_good");
        (new testcases.CWE259_Hard_Coded_Password.J18812()).runTest("CWE259_Hard_Coded_Password__driverManager_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18835()).runTest("CWE259_Hard_Coded_Password__driverManager_21_good");
        (new testcases.CWE259_Hard_Coded_Password.J18834()).runTest("CWE259_Hard_Coded_Password__driverManager_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18889()).runTest("CWE259_Hard_Coded_Password__passwordAuth_01_good");
        (new testcases.CWE259_Hard_Coded_Password.J18888()).runTest("CWE259_Hard_Coded_Password__passwordAuth_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18839()).runTest("CWE259_Hard_Coded_Password__driverManager_41_good");
        (new testcases.CWE259_Hard_Coded_Password.J18838()).runTest("CWE259_Hard_Coded_Password__driverManager_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18921()).runTest("CWE259_Hard_Coded_Password__passwordAuth_17_good");
        (new testcases.CWE259_Hard_Coded_Password.J18920()).runTest("CWE259_Hard_Coded_Password__passwordAuth_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18853()).runTest("CWE259_Hard_Coded_Password__kerberosKey_05_good");
        (new testcases.CWE259_Hard_Coded_Password.J18852()).runTest("CWE259_Hard_Coded_Password__kerberosKey_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18873()).runTest("CWE259_Hard_Coded_Password__kerberosKey_15_good");
        (new testcases.CWE259_Hard_Coded_Password.J18872()).runTest("CWE259_Hard_Coded_Password__kerberosKey_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18869()).runTest("CWE259_Hard_Coded_Password__kerberosKey_13_good");
        (new testcases.CWE259_Hard_Coded_Password.J18868()).runTest("CWE259_Hard_Coded_Password__kerberosKey_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18887()).runTest("CWE259_Hard_Coded_Password__kerberosKey_45_good");
        (new testcases.CWE259_Hard_Coded_Password.J18886()).runTest("CWE259_Hard_Coded_Password__kerberosKey_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18907()).runTest("CWE259_Hard_Coded_Password__passwordAuth_10_good");
        (new testcases.CWE259_Hard_Coded_Password.J18906()).runTest("CWE259_Hard_Coded_Password__passwordAuth_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18893()).runTest("CWE259_Hard_Coded_Password__passwordAuth_03_good");
        (new testcases.CWE259_Hard_Coded_Password.J18892()).runTest("CWE259_Hard_Coded_Password__passwordAuth_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18845()).runTest("CWE259_Hard_Coded_Password__kerberosKey_01_good");
        (new testcases.CWE259_Hard_Coded_Password.J18844()).runTest("CWE259_Hard_Coded_Password__kerberosKey_01_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18803()).runTest("CWE259_Hard_Coded_Password__driverManager_02_good");
        (new testcases.CWE259_Hard_Coded_Password.J18802()).runTest("CWE259_Hard_Coded_Password__driverManager_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18917()).runTest("CWE259_Hard_Coded_Password__passwordAuth_15_good");
        (new testcases.CWE259_Hard_Coded_Password.J18916()).runTest("CWE259_Hard_Coded_Password__passwordAuth_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18903()).runTest("CWE259_Hard_Coded_Password__passwordAuth_08_good");
        (new testcases.CWE259_Hard_Coded_Password.J18902()).runTest("CWE259_Hard_Coded_Password__passwordAuth_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18841()).runTest("CWE259_Hard_Coded_Password__driverManager_42_good");
        (new testcases.CWE259_Hard_Coded_Password.J18840()).runTest("CWE259_Hard_Coded_Password__driverManager_42_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18909()).runTest("CWE259_Hard_Coded_Password__passwordAuth_11_good");
        (new testcases.CWE259_Hard_Coded_Password.J18908()).runTest("CWE259_Hard_Coded_Password__passwordAuth_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18823()).runTest("CWE259_Hard_Coded_Password__driverManager_12_good");
        (new testcases.CWE259_Hard_Coded_Password.J18822()).runTest("CWE259_Hard_Coded_Password__driverManager_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18819()).runTest("CWE259_Hard_Coded_Password__driverManager_10_good");
        (new testcases.CWE259_Hard_Coded_Password.J18818()).runTest("CWE259_Hard_Coded_Password__driverManager_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18897()).runTest("CWE259_Hard_Coded_Password__passwordAuth_05_good");
        (new testcases.CWE259_Hard_Coded_Password.J18896()).runTest("CWE259_Hard_Coded_Password__passwordAuth_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18923()).runTest("CWE259_Hard_Coded_Password__passwordAuth_21_good");
        (new testcases.CWE259_Hard_Coded_Password.J18922()).runTest("CWE259_Hard_Coded_Password__passwordAuth_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18815()).runTest("CWE259_Hard_Coded_Password__driverManager_08_good");
        (new testcases.CWE259_Hard_Coded_Password.J18814()).runTest("CWE259_Hard_Coded_Password__driverManager_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18807()).runTest("CWE259_Hard_Coded_Password__driverManager_04_good");
        (new testcases.CWE259_Hard_Coded_Password.J18806()).runTest("CWE259_Hard_Coded_Password__driverManager_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18881()).runTest("CWE259_Hard_Coded_Password__kerberosKey_31_good");
        (new testcases.CWE259_Hard_Coded_Password.J18880()).runTest("CWE259_Hard_Coded_Password__kerberosKey_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18809()).runTest("CWE259_Hard_Coded_Password__driverManager_05_good");
        (new testcases.CWE259_Hard_Coded_Password.J18808()).runTest("CWE259_Hard_Coded_Password__driverManager_05_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18833()).runTest("CWE259_Hard_Coded_Password__driverManager_17_good");
        (new testcases.CWE259_Hard_Coded_Password.J18832()).runTest("CWE259_Hard_Coded_Password__driverManager_17_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18901()).runTest("CWE259_Hard_Coded_Password__passwordAuth_07_good");
        (new testcases.CWE259_Hard_Coded_Password.J18900()).runTest("CWE259_Hard_Coded_Password__passwordAuth_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18875()).runTest("CWE259_Hard_Coded_Password__kerberosKey_16_good");
        (new testcases.CWE259_Hard_Coded_Password.J18874()).runTest("CWE259_Hard_Coded_Password__kerberosKey_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18891()).runTest("CWE259_Hard_Coded_Password__passwordAuth_02_good");
        (new testcases.CWE259_Hard_Coded_Password.J18890()).runTest("CWE259_Hard_Coded_Password__passwordAuth_02_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18883()).runTest("CWE259_Hard_Coded_Password__kerberosKey_41_good");
        (new testcases.CWE259_Hard_Coded_Password.J18882()).runTest("CWE259_Hard_Coded_Password__kerberosKey_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18805()).runTest("CWE259_Hard_Coded_Password__driverManager_03_good");
        (new testcases.CWE259_Hard_Coded_Password.J18804()).runTest("CWE259_Hard_Coded_Password__driverManager_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18829()).runTest("CWE259_Hard_Coded_Password__driverManager_15_good");
        (new testcases.CWE259_Hard_Coded_Password.J18828()).runTest("CWE259_Hard_Coded_Password__driverManager_15_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18899()).runTest("CWE259_Hard_Coded_Password__passwordAuth_06_good");
        (new testcases.CWE259_Hard_Coded_Password.J18898()).runTest("CWE259_Hard_Coded_Password__passwordAuth_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18911()).runTest("CWE259_Hard_Coded_Password__passwordAuth_12_good");
        (new testcases.CWE259_Hard_Coded_Password.J18910()).runTest("CWE259_Hard_Coded_Password__passwordAuth_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18879()).runTest("CWE259_Hard_Coded_Password__kerberosKey_21_good");
        (new testcases.CWE259_Hard_Coded_Password.J18878()).runTest("CWE259_Hard_Coded_Password__kerberosKey_21_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18895()).runTest("CWE259_Hard_Coded_Password__passwordAuth_04_good");
        (new testcases.CWE259_Hard_Coded_Password.J18894()).runTest("CWE259_Hard_Coded_Password__passwordAuth_04_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18915()).runTest("CWE259_Hard_Coded_Password__passwordAuth_14_good");
        (new testcases.CWE259_Hard_Coded_Password.J18914()).runTest("CWE259_Hard_Coded_Password__passwordAuth_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18857()).runTest("CWE259_Hard_Coded_Password__kerberosKey_07_good");
        (new testcases.CWE259_Hard_Coded_Password.J18856()).runTest("CWE259_Hard_Coded_Password__kerberosKey_07_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18929()).runTest("CWE259_Hard_Coded_Password__passwordAuth_42_good");
        (new testcases.CWE259_Hard_Coded_Password.J18928()).runTest("CWE259_Hard_Coded_Password__passwordAuth_42_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18827()).runTest("CWE259_Hard_Coded_Password__driverManager_14_good");
        (new testcases.CWE259_Hard_Coded_Password.J18826()).runTest("CWE259_Hard_Coded_Password__driverManager_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18905()).runTest("CWE259_Hard_Coded_Password__passwordAuth_09_good");
        (new testcases.CWE259_Hard_Coded_Password.J18904()).runTest("CWE259_Hard_Coded_Password__passwordAuth_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18871()).runTest("CWE259_Hard_Coded_Password__kerberosKey_14_good");
        (new testcases.CWE259_Hard_Coded_Password.J18870()).runTest("CWE259_Hard_Coded_Password__kerberosKey_14_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18867()).runTest("CWE259_Hard_Coded_Password__kerberosKey_12_good");
        (new testcases.CWE259_Hard_Coded_Password.J18866()).runTest("CWE259_Hard_Coded_Password__kerberosKey_12_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18821()).runTest("CWE259_Hard_Coded_Password__driverManager_11_good");
        (new testcases.CWE259_Hard_Coded_Password.J18820()).runTest("CWE259_Hard_Coded_Password__driverManager_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18817()).runTest("CWE259_Hard_Coded_Password__driverManager_09_good");
        (new testcases.CWE259_Hard_Coded_Password.J18816()).runTest("CWE259_Hard_Coded_Password__driverManager_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18919()).runTest("CWE259_Hard_Coded_Password__passwordAuth_16_good");
        (new testcases.CWE259_Hard_Coded_Password.J18918()).runTest("CWE259_Hard_Coded_Password__passwordAuth_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18863()).runTest("CWE259_Hard_Coded_Password__kerberosKey_10_good");
        (new testcases.CWE259_Hard_Coded_Password.J18862()).runTest("CWE259_Hard_Coded_Password__kerberosKey_10_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18927()).runTest("CWE259_Hard_Coded_Password__passwordAuth_41_good");
        (new testcases.CWE259_Hard_Coded_Password.J18926()).runTest("CWE259_Hard_Coded_Password__passwordAuth_41_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18859()).runTest("CWE259_Hard_Coded_Password__kerberosKey_08_good");
        (new testcases.CWE259_Hard_Coded_Password.J18858()).runTest("CWE259_Hard_Coded_Password__kerberosKey_08_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18913()).runTest("CWE259_Hard_Coded_Password__passwordAuth_13_good");
        (new testcases.CWE259_Hard_Coded_Password.J18912()).runTest("CWE259_Hard_Coded_Password__passwordAuth_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18843()).runTest("CWE259_Hard_Coded_Password__driverManager_45_good");
        (new testcases.CWE259_Hard_Coded_Password.J18842()).runTest("CWE259_Hard_Coded_Password__driverManager_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18825()).runTest("CWE259_Hard_Coded_Password__driverManager_13_good");
        (new testcases.CWE259_Hard_Coded_Password.J18824()).runTest("CWE259_Hard_Coded_Password__driverManager_13_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18837()).runTest("CWE259_Hard_Coded_Password__driverManager_31_good");
        (new testcases.CWE259_Hard_Coded_Password.J18836()).runTest("CWE259_Hard_Coded_Password__driverManager_31_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18811()).runTest("CWE259_Hard_Coded_Password__driverManager_06_good");
        (new testcases.CWE259_Hard_Coded_Password.J18810()).runTest("CWE259_Hard_Coded_Password__driverManager_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18861()).runTest("CWE259_Hard_Coded_Password__kerberosKey_09_good");
        (new testcases.CWE259_Hard_Coded_Password.J18860()).runTest("CWE259_Hard_Coded_Password__kerberosKey_09_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18831()).runTest("CWE259_Hard_Coded_Password__driverManager_16_good");
        (new testcases.CWE259_Hard_Coded_Password.J18830()).runTest("CWE259_Hard_Coded_Password__driverManager_16_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18849()).runTest("CWE259_Hard_Coded_Password__kerberosKey_03_good");
        (new testcases.CWE259_Hard_Coded_Password.J18848()).runTest("CWE259_Hard_Coded_Password__kerberosKey_03_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18855()).runTest("CWE259_Hard_Coded_Password__kerberosKey_06_good");
        (new testcases.CWE259_Hard_Coded_Password.J18854()).runTest("CWE259_Hard_Coded_Password__kerberosKey_06_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18865()).runTest("CWE259_Hard_Coded_Password__kerberosKey_11_good");
        (new testcases.CWE259_Hard_Coded_Password.J18864()).runTest("CWE259_Hard_Coded_Password__kerberosKey_11_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18931()).runTest("CWE259_Hard_Coded_Password__passwordAuth_45_good");
        (new testcases.CWE259_Hard_Coded_Password.J18930()).runTest("CWE259_Hard_Coded_Password__passwordAuth_45_bad");
        (new testcases.CWE259_Hard_Coded_Password.J18885()).runTest("CWE259_Hard_Coded_Password__kerberosKey_42_good");
        (new testcases.CWE259_Hard_Coded_Password.J18884()).runTest("CWE259_Hard_Coded_Password__kerberosKey_42_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
