package testcases.CWE606_Unchecked_Loop_Condition;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */
        (new testcases.CWE606_Unchecked_Loop_Condition.J20017()).runTest("CWE606_Unchecked_Loop_Condition__database_21_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20016()).runTest("CWE606_Unchecked_Loop_Condition__database_21_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19973()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_21_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19972()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_21_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20317()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_14_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20316()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_14_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20099()).runTest("CWE606_Unchecked_Loop_Condition__File_15_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20098()).runTest("CWE606_Unchecked_Loop_Condition__File_15_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20313()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_12_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20312()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_12_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19899()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_03_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19898()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_03_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19955()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_09_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19954()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_09_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20357()).runTest("CWE606_Unchecked_Loop_Condition__Property_12_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20356()).runTest("CWE606_Unchecked_Loop_Condition__Property_12_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20365()).runTest("CWE606_Unchecked_Loop_Condition__Property_16_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20364()).runTest("CWE606_Unchecked_Loop_Condition__Property_16_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20385()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_04_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20384()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_04_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20009()).runTest("CWE606_Unchecked_Loop_Condition__database_14_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20008()).runTest("CWE606_Unchecked_Loop_Condition__database_14_b");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20303()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_07_gd");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20302()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_07_b");
        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
