package testcases.CWE606_Unchecked_Loop_Condition;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                        "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            /* User supplied some class names on the command line, just use those with introspection
             *
             * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
             *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
             * could read class names from command line or use
             * http://sadun-util.sourceforge.net/api/org/sadun/util/
             * ClassPackageExplorer.html
             */

            for (String className : args) {

                try {

                    /* String classNameWithPackage = "testcases." + className; */

                    /* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass
                            .newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); /* leave a blank line between classes */

            }

        } else {

            /* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

        /* END-AUTOGENERATED-JAVA-TESTS-1 */
    }

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

        /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

        /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }

    private static void runTestCWE4() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

        /* END-AUTOGENERATED-JAVA-TESTS-4 */
    }

    private static void runTestCWE5() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

        /* END-AUTOGENERATED-JAVA-TESTS-5 */
    }

    private static void runTestCWE6() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */
        (new testcases.CWE606_Unchecked_Loop_Condition.J19915()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19914()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20043()).runTest("CWE606_Unchecked_Loop_Condition__Environment_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20042()).runTest("CWE606_Unchecked_Loop_Condition__Environment_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19987()).runTest("CWE606_Unchecked_Loop_Condition__database_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19986()).runTest("CWE606_Unchecked_Loop_Condition__database_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20369()).runTest("CWE606_Unchecked_Loop_Condition__Property_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20368()).runTest("CWE606_Unchecked_Loop_Condition__Property_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20021()).runTest("CWE606_Unchecked_Loop_Condition__database_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20020()).runTest("CWE606_Unchecked_Loop_Condition__database_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19937()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19936()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20063()).runTest("CWE606_Unchecked_Loop_Condition__Environment_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20062()).runTest("CWE606_Unchecked_Loop_Condition__Environment_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20363()).runTest("CWE606_Unchecked_Loop_Condition__Property_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20362()).runTest("CWE606_Unchecked_Loop_Condition__Property_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20305()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20304()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19963()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19962()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20273()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20272()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20017()).runTest("CWE606_Unchecked_Loop_Condition__database_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20016()).runTest("CWE606_Unchecked_Loop_Condition__database_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19943()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19942()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19949()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19948()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19909()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19908()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20011()).runTest("CWE606_Unchecked_Loop_Condition__database_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20010()).runTest("CWE606_Unchecked_Loop_Condition__database_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20323()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20322()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19973()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19972()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20341()).runTest("CWE606_Unchecked_Loop_Condition__Property_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20340()).runTest("CWE606_Unchecked_Loop_Condition__Property_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20405()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20404()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20249()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20248()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19923()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19922()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19917()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19916()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19967()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19966()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20033()).runTest("CWE606_Unchecked_Loop_Condition__Environment_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20032()).runTest("CWE606_Unchecked_Loop_Condition__Environment_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19953()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19952()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20315()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20314()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20377()).runTest("CWE606_Unchecked_Loop_Condition__Property_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20376()).runTest("CWE606_Unchecked_Loop_Condition__Property_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19947()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19946()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20083()).runTest("CWE606_Unchecked_Loop_Condition__File_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20082()).runTest("CWE606_Unchecked_Loop_Condition__File_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20037()).runTest("CWE606_Unchecked_Loop_Condition__Environment_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20036()).runTest("CWE606_Unchecked_Loop_Condition__Environment_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20269()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20268()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20081()).runTest("CWE606_Unchecked_Loop_Condition__File_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20080()).runTest("CWE606_Unchecked_Loop_Condition__File_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20299()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20298()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20039()).runTest("CWE606_Unchecked_Loop_Condition__Environment_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20038()).runTest("CWE606_Unchecked_Loop_Condition__Environment_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20023()).runTest("CWE606_Unchecked_Loop_Condition__database_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20022()).runTest("CWE606_Unchecked_Loop_Condition__database_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20295()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20294()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19945()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19944()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20049()).runTest("CWE606_Unchecked_Loop_Condition__Environment_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20048()).runTest("CWE606_Unchecked_Loop_Condition__Environment_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20317()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20316()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20407()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20406()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20093()).runTest("CWE606_Unchecked_Loop_Condition__File_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20092()).runTest("CWE606_Unchecked_Loop_Condition__File_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19999()).runTest("CWE606_Unchecked_Loop_Condition__database_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19998()).runTest("CWE606_Unchecked_Loop_Condition__database_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19895()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19894()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20411()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20410()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20335()).runTest("CWE606_Unchecked_Loop_Condition__Property_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20334()).runTest("CWE606_Unchecked_Loop_Condition__Property_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19911()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19910()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19941()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19940()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20263()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20262()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20059()).runTest("CWE606_Unchecked_Loop_Condition__Environment_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20058()).runTest("CWE606_Unchecked_Loop_Condition__Environment_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20091()).runTest("CWE606_Unchecked_Loop_Condition__File_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20090()).runTest("CWE606_Unchecked_Loop_Condition__File_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19979()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19978()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20099()).runTest("CWE606_Unchecked_Loop_Condition__File_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20098()).runTest("CWE606_Unchecked_Loop_Condition__File_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20313()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20312()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19965()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19964()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20391()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20390()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20265()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20264()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20001()).runTest("CWE606_Unchecked_Loop_Condition__database_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20000()).runTest("CWE606_Unchecked_Loop_Condition__database_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20279()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20278()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19899()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19898()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20291()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20290()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20325()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20324()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19919()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19918()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20105()).runTest("CWE606_Unchecked_Loop_Condition__File_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20104()).runTest("CWE606_Unchecked_Loop_Condition__File_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20379()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20378()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20413()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20412()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19977()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19976()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20025()).runTest("CWE606_Unchecked_Loop_Condition__database_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20024()).runTest("CWE606_Unchecked_Loop_Condition__database_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19995()).runTest("CWE606_Unchecked_Loop_Condition__database_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19994()).runTest("CWE606_Unchecked_Loop_Condition__database_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20247()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20246()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20387()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20386()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20253()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20252()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20327()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20326()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19901()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19900()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19955()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19954()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19935()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19934()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20003()).runTest("CWE606_Unchecked_Loop_Condition__database_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20002()).runTest("CWE606_Unchecked_Loop_Condition__database_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20307()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20306()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20067()).runTest("CWE606_Unchecked_Loop_Condition__Environment_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20066()).runTest("CWE606_Unchecked_Loop_Condition__Environment_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20333()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20332()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19989()).runTest("CWE606_Unchecked_Loop_Condition__database_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19988()).runTest("CWE606_Unchecked_Loop_Condition__database_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20355()).runTest("CWE606_Unchecked_Loop_Condition__Property_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20354()).runTest("CWE606_Unchecked_Loop_Condition__Property_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20089()).runTest("CWE606_Unchecked_Loop_Condition__File_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20088()).runTest("CWE606_Unchecked_Loop_Condition__File_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19921()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19920()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20271()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20270()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20357()).runTest("CWE606_Unchecked_Loop_Condition__Property_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20356()).runTest("CWE606_Unchecked_Loop_Condition__Property_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20007()).runTest("CWE606_Unchecked_Loop_Condition__database_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20006()).runTest("CWE606_Unchecked_Loop_Condition__database_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20359()).runTest("CWE606_Unchecked_Loop_Condition__Property_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20358()).runTest("CWE606_Unchecked_Loop_Condition__Property_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19993()).runTest("CWE606_Unchecked_Loop_Condition__database_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19992()).runTest("CWE606_Unchecked_Loop_Condition__database_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20073()).runTest("CWE606_Unchecked_Loop_Condition__File_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20072()).runTest("CWE606_Unchecked_Loop_Condition__File_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20381()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20380()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19991()).runTest("CWE606_Unchecked_Loop_Condition__database_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19990()).runTest("CWE606_Unchecked_Loop_Condition__database_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20013()).runTest("CWE606_Unchecked_Loop_Condition__database_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20012()).runTest("CWE606_Unchecked_Loop_Condition__database_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20107()).runTest("CWE606_Unchecked_Loop_Condition__File_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20106()).runTest("CWE606_Unchecked_Loop_Condition__File_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20085()).runTest("CWE606_Unchecked_Loop_Condition__File_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20084()).runTest("CWE606_Unchecked_Loop_Condition__File_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20109()).runTest("CWE606_Unchecked_Loop_Condition__File_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20108()).runTest("CWE606_Unchecked_Loop_Condition__File_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19933()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19932()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20275()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20274()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20421()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20420()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20061()).runTest("CWE606_Unchecked_Loop_Condition__Environment_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20060()).runTest("CWE606_Unchecked_Loop_Condition__Environment_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20301()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20300()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19969()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19968()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20365()).runTest("CWE606_Unchecked_Loop_Condition__Property_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20364()).runTest("CWE606_Unchecked_Loop_Condition__Property_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20293()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20292()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20343()).runTest("CWE606_Unchecked_Loop_Condition__Property_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20342()).runTest("CWE606_Unchecked_Loop_Condition__Property_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20353()).runTest("CWE606_Unchecked_Loop_Condition__Property_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20352()).runTest("CWE606_Unchecked_Loop_Condition__Property_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20015()).runTest("CWE606_Unchecked_Loop_Condition__database_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20014()).runTest("CWE606_Unchecked_Loop_Condition__database_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20321()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20320()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20385()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20384()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20419()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20418()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19959()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19958()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19907()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19906()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20401()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20400()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19931()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19930()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20373()).runTest("CWE606_Unchecked_Loop_Condition__Property_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20372()).runTest("CWE606_Unchecked_Loop_Condition__Property_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20399()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20398()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19897()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19896()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19913()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19912()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19997()).runTest("CWE606_Unchecked_Loop_Condition__database_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19996()).runTest("CWE606_Unchecked_Loop_Condition__database_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20319()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20318()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20261()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20260()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20259()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20258()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20027()).runTest("CWE606_Unchecked_Loop_Condition__Environment_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20026()).runTest("CWE606_Unchecked_Loop_Condition__Environment_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20069()).runTest("CWE606_Unchecked_Loop_Condition__Environment_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20068()).runTest("CWE606_Unchecked_Loop_Condition__Environment_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20285()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20284()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20031()).runTest("CWE606_Unchecked_Loop_Condition__Environment_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20030()).runTest("CWE606_Unchecked_Loop_Condition__Environment_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20251()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20250()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20383()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20382()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20367()).runTest("CWE606_Unchecked_Loop_Condition__Property_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20366()).runTest("CWE606_Unchecked_Loop_Condition__Property_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20113()).runTest("CWE606_Unchecked_Loop_Condition__File_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20112()).runTest("CWE606_Unchecked_Loop_Condition__File_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20101()).runTest("CWE606_Unchecked_Loop_Condition__File_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20100()).runTest("CWE606_Unchecked_Loop_Condition__File_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20051()).runTest("CWE606_Unchecked_Loop_Condition__Environment_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20050()).runTest("CWE606_Unchecked_Loop_Condition__Environment_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20417()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20416()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19971()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19970()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20347()).runTest("CWE606_Unchecked_Loop_Condition__Property_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20346()).runTest("CWE606_Unchecked_Loop_Condition__Property_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20281()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20280()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19961()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19960()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20277()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20276()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20351()).runTest("CWE606_Unchecked_Loop_Condition__Property_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20350()).runTest("CWE606_Unchecked_Loop_Condition__Property_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20403()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20402()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20077()).runTest("CWE606_Unchecked_Loop_Condition__File_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20076()).runTest("CWE606_Unchecked_Loop_Condition__File_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19903()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19902()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20375()).runTest("CWE606_Unchecked_Loop_Condition__Property_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20374()).runTest("CWE606_Unchecked_Loop_Condition__Property_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20009()).runTest("CWE606_Unchecked_Loop_Condition__database_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20008()).runTest("CWE606_Unchecked_Loop_Condition__database_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19983()).runTest("CWE606_Unchecked_Loop_Condition__database_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19982()).runTest("CWE606_Unchecked_Loop_Condition__database_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20087()).runTest("CWE606_Unchecked_Loop_Condition__File_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20086()).runTest("CWE606_Unchecked_Loop_Condition__File_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20345()).runTest("CWE606_Unchecked_Loop_Condition__Property_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20344()).runTest("CWE606_Unchecked_Loop_Condition__Property_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19925()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19924()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20371()).runTest("CWE606_Unchecked_Loop_Condition__Property_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20370()).runTest("CWE606_Unchecked_Loop_Condition__Property_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20075()).runTest("CWE606_Unchecked_Loop_Condition__File_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20074()).runTest("CWE606_Unchecked_Loop_Condition__File_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20057()).runTest("CWE606_Unchecked_Loop_Condition__Environment_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20056()).runTest("CWE606_Unchecked_Loop_Condition__Environment_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20309()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20308()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20339()).runTest("CWE606_Unchecked_Loop_Condition__Property_03_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20338()).runTest("CWE606_Unchecked_Loop_Condition__Property_03_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20349()).runTest("CWE606_Unchecked_Loop_Condition__Property_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20348()).runTest("CWE606_Unchecked_Loop_Condition__Property_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20005()).runTest("CWE606_Unchecked_Loop_Condition__database_12_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20004()).runTest("CWE606_Unchecked_Loop_Condition__database_12_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20283()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20282()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20303()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20302()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20053()).runTest("CWE606_Unchecked_Loop_Condition__Environment_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20052()).runTest("CWE606_Unchecked_Loop_Condition__Environment_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20329()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20328()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20297()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_04_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20296()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_04_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20267()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20266()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20103()).runTest("CWE606_Unchecked_Loop_Condition__File_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20102()).runTest("CWE606_Unchecked_Loop_Condition__File_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20055()).runTest("CWE606_Unchecked_Loop_Condition__Environment_15_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20054()).runTest("CWE606_Unchecked_Loop_Condition__Environment_15_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20095()).runTest("CWE606_Unchecked_Loop_Condition__File_13_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20094()).runTest("CWE606_Unchecked_Loop_Condition__File_13_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20041()).runTest("CWE606_Unchecked_Loop_Condition__Environment_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20040()).runTest("CWE606_Unchecked_Loop_Condition__Environment_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20395()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_09_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20394()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_09_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20035()).runTest("CWE606_Unchecked_Loop_Condition__Environment_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20034()).runTest("CWE606_Unchecked_Loop_Condition__Environment_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20389()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20388()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20065()).runTest("CWE606_Unchecked_Loop_Condition__Environment_41_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20064()).runTest("CWE606_Unchecked_Loop_Condition__Environment_41_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19905()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19904()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19957()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19956()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20393()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_08_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20392()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_08_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20287()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20286()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20019()).runTest("CWE606_Unchecked_Loop_Condition__database_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20018()).runTest("CWE606_Unchecked_Loop_Condition__database_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19981()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19980()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19951()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_07_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19950()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_07_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20289()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_45_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20288()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_45_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20255()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20254()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19975()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19974()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20397()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20396()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19929()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_21_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19928()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_21_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19985()).runTest("CWE606_Unchecked_Loop_Condition__database_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19984()).runTest("CWE606_Unchecked_Loop_Condition__database_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20079()).runTest("CWE606_Unchecked_Loop_Condition__File_05_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20078()).runTest("CWE606_Unchecked_Loop_Condition__File_05_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20111()).runTest("CWE606_Unchecked_Loop_Condition__File_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20110()).runTest("CWE606_Unchecked_Loop_Condition__File_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20045()).runTest("CWE606_Unchecked_Loop_Condition__Environment_10_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20044()).runTest("CWE606_Unchecked_Loop_Condition__Environment_10_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20361()).runTest("CWE606_Unchecked_Loop_Condition__Property_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20360()).runTest("CWE606_Unchecked_Loop_Condition__Property_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20409()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_16_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20408()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_16_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20331()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_42_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20330()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_42_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20257()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_06_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20256()).runTest("CWE606_Unchecked_Loop_Condition__listen_tcp_06_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20311()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20310()).runTest("CWE606_Unchecked_Loop_Condition__PropertiesFile_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20071()).runTest("CWE606_Unchecked_Loop_Condition__File_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20070()).runTest("CWE606_Unchecked_Loop_Condition__File_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20337()).runTest("CWE606_Unchecked_Loop_Condition__Property_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20336()).runTest("CWE606_Unchecked_Loop_Condition__Property_02_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19927()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_17_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19926()).runTest("CWE606_Unchecked_Loop_Condition__connect_tcp_17_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20047()).runTest("CWE606_Unchecked_Loop_Condition__Environment_11_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20046()).runTest("CWE606_Unchecked_Loop_Condition__Environment_11_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19939()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_01_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J19938()).runTest("CWE606_Unchecked_Loop_Condition__console_readLine_01_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20097()).runTest("CWE606_Unchecked_Loop_Condition__File_14_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20096()).runTest("CWE606_Unchecked_Loop_Condition__File_14_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20415()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_31_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20414()).runTest("CWE606_Unchecked_Loop_Condition__URLConnection_31_bad");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20029()).runTest("CWE606_Unchecked_Loop_Condition__Environment_02_good");
        (new testcases.CWE606_Unchecked_Loop_Condition.J20028()).runTest("CWE606_Unchecked_Loop_Condition__Environment_02_bad");
        /* END-AUTOGENERATED-JAVA-TESTS-6 */
    }

    private static void runTestCWE7() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

        /* END-AUTOGENERATED-JAVA-TESTS-7 */
    }

    private static void runTestCWE8() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

        /* END-AUTOGENERATED-JAVA-TESTS-8 */
    }

    private static void runTestCWE9() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

        /* END-AUTOGENERATED-JAVA-TESTS-9 */
    }
}
